### ISSUE TITLE
clean Matercomfig without presets

### ISSUE THREAD

**Issue by SupinePandora43** [mastercoms/tf2cfg#103]

**Comment by Leo40Git** [comment]
...you don't need to install a mastercomfig preset to clean up your TF2 install? Just follow [these steps](https://docs.mastercomfig.com/en/latest/setup/clean_up/).

**Comment by SupinePandora43** [comment]
@Leo40Git, i mean "install mastercomfig, without presets"

**Comment by Leo40Git** [comment]
...why would you want to do that? Just pick a preset and customize it via modules. No need to start from scratch.

**Comment by PoorPocketsMcNewHold** [comment]
I suppose this mean, to create a mastercomfig preset, with mostly just ¨optimisations¨ features. Meaning configured settings which doesn’t affects the graphics in itself. However, I doubt this would be actually useful nonetheless.

**Comment by Tiagoquix** [comment]
Make a **modules.cfg** file on **tf/cfg/user** and make your own preset. Follow the steps here: https://docs.mastercomfig.com/en/latest/customization/modules/
