### ISSUE TITLE
Why is aa_mssa=none on medium-high preset and not aa_mssa=off?

### ISSUE THREAD

**Issue by Tiagoquix** [mastercoms/tf2cfg#111]
If you see here, **aa_msaa** is **none**: https://github.com/mastercoms/mastercomfig/blob/release/config/cfg/presets/medium-high.cfg

But, in the other presets, the value is **off** instead of **none**.
https://github.com/mastercoms/mastercomfig/blob/release/config/cfg/presets/very-low.cfg
https://github.com/mastercoms/mastercomfig/blob/release/config/cfg/presets/low.cfg
https://github.com/mastercoms/mastercomfig/blob/release/config/cfg/presets/medium-low.cfg
https://github.com/mastercoms/mastercomfig/blob/release/config/cfg/presets/medium.cfg

**Comment by mastercoms** [comment]
So that it's set to the default value for their system. That's the level of performance we want on medium high.
