### ISSUE TITLE
srcds local host game crash with "-reuse"

### ISSUE THREAD

**Issue by hoffor** [mastercoms/tf2cfg#141]
Just wanted to mention that the launch option "-reuse" will crash the game to desktop when attempting to join a Source Dedicated Server hosted from the same device. Might be helpful to point out in the docs since I had no pointers online and had to figure it out on my own. The error message it gives is "Couldn't allocate any server IP port"

Crashes when connecting with internal and external IP. Default port was used

**Comment by mastercoms** [comment]
Honestly, reuse should be removed from the launch options.

**Comment by hoffor** [comment]
edit: The error message it gives is: " Couldn't allocate any server ip port."

**Comment by mastercoms** [comment]
Fixed in https://github.com/mastercoms/mastercomfig/commit/af99b679344315e09f4bed25030100d1c74121de.
