### ISSUE TITLE
do we just not care about linux anymore?

### ISSUE THREAD

**Issue by ghost** [mastercoms/tf2cfg#142]
ubuntu 19.XX, and distros based on it BOTH cannot run mastercomfig. previous distros can, and i have used 18.04 lts, but since that is going to not work within a few years, i wanted to know if MCFG will continue to be supported by linux, and bring this issue to light if no one else knows about this yet.
Regards, a concerend linux user.

**Comment by mastercoms** [comment]
mastercomfig 7 isn't being supported anymore.
