### ISSUE TITLE
mastercomfig 8.0.0 significantly slower than masterconfig 6.14.1 (medium preset)

### ISSUE THREAD

**Issue by kamild1996** [mastercoms/tf2cfg#143]
mastercomfig 8.0.0 is significantly slower compared to the version I was using previously, which is 6.14.1. Using medium preset with no pyroland, no soundscapes, no tutorial and mouse tweaks/flat mouse addons.

Result of your benchmark_test timedemo:
- 8.0.0: `4812 frames 36.438 seconds 132.06 fps ( 7.57 ms/f) 7.925 fps variability`
- 6.14.1: `4812 frames 34.453 seconds 139.67 fps (7.16 ms/f) 6.380 fps variability`
~8 fps from these benchmarks don't seem like a lot, but just by playing I can clearly feel I'm having much more noticable fps drops, although I'm not quite sure how I can measure that. Tell me how I can do that and I can provide measurements.

Launch parameters used for testing both versions:
`-novid -nojoy -nosteamcontroller -softparticlesdefaultoff -nohltv -particles 1 -primarysound -snoforceformat`

Module settings changed (based on medium preset) when testing both versions:
- textures=very_high
- hud_player_model=on
- ragdolls=medium

Additional graphics related commands in my autoexec.cfg (some of them are probably redundant, aren't they?):
- mat_picmip 0
- mat_hdr_level 0
- tf_spec_xray_disable 0
- sv_forcepreload 1
- cl_ragdoll_collide 1
- cl_ragdoll_fade_time 15 // Fade out ragdolls in 5 seconds
- cl_ragdoll_forcefade 0
- cl_ragdoll_physics_enable 1
- g_ragdoll_fadespeed 500
- g_ragdoll_lvfadespeed 10000 // ^ but in low violence
- ragdoll_sleepaftertime 1

Fullscreen optimization disabled.

Specs: Ryzen 7 3700X 4.4 GHz, 16GB DDR4-3466, GTX 1070, Windows 10 Pro x64 build 1903

**Comment by mastercoms** [comment]
Thank you for bringing this to my attention. Could you test the following settings independently and give me the results:

```
r_ForceWaterLeaf 0
```

```
r_occludeemaxarea .5
r_occluderminarea 3
r_occludermincount 2
```

```
r_lightcache_zbuffercache 0
```

To resolve your config redundancies, remove the following from your autoexec:

```
mat_picmip 0
mat_hdr_level 0
sv_forcepreload 1
cl_ragdoll_collide 1
cl_ragdoll_fade_time 15 // Fade out ragdolls in 5 seconds
cl_ragdoll_forcefade 0
cl_ragdoll_physics_enable 1
g_ragdoll_fadespeed 500
g_ragdoll_lvfadespeed 10000 // ^ but in low violence
ragdoll_sleepaftertime 1
```

change modules:

```
textures=high
hud_player_model=on
ragdolls=medium
post_processing=low
```

**Comment by kamild1996** [comment]
Hm, after rebooting my PC and removing these commands from the autoexec I'm now getting pretty much equal (~0.2 fps diff) performance on both versions... Didn't expect any of these autoexec commands to break things but ok.
I will keep using 8.0.0 and if I manage to experience the performance regression again, I'll let you know via this issue.
