### ISSUE TITLE
The module effects set to medium does not show first person tracers, and enables muzzle flashes and shell casing ejection

### ISSUE THREAD

**Issue by ghost** [mastercoms/tf2cfg#147]
**Describe the bug**
The module `effects` set to `medium` enables shell casing ejection and muzzle flashes, and does not show first person tracers, whilst the value is supposed to:
> **disables shell casing ejection**, **disables muzzle flashes**, **shows first person tracers**, enables water splashes

**How you encountered the issue**
I play the game on the Medium Low preset with the `effects=medium` override to enable first person tracers.

**Screenshots**
![notracers](https://user-images.githubusercontent.com/27376783/69382290-058e9400-0cb7-11ea-8410-47abf23f5b8c.png)

**Desktop:**
* Config version: mastercomfig November version 19 : 2019 8.2.0
* Config preset and addon(s): Medium Low, no addons
* Custom values (if any): from `modules.log` - `alias sound sound_ultra`, `alias effects_medium effects ` 
* DX level: None. Playing on Linux.
* Launch options: -novid
* Operating system (OS): Fedora Silverblue 31
* Graphics card (GPU): AMD RX560
* Graphics driver version: Mesa 19.3.0-devel with ACO patches (https://gitlab.com/freedesktop-sdk/freedesktop-sdk/tree/19.08/elements/extensions/mesa-aco)
* Processor (CPU): Intel i7 3770
* TF2 on HDD or SSD: HDD
* Memory (RAM) size in MB or GB: 16GB

**Comment by mastercoms** [comment]
These settings do not affect all forms of these effects. The Minigun is a noticeable exception to most of these. But, everything is correct in terms of cvar values in the effects medium module level.
