### ISSUE TITLE
Random fps lag spikes

### ISSUE THREAD

**Issue by T-oasterO-ven** [mastercoms/tf2cfg#15]
* How you encountered the issue
Recently, if even one pyro is on the server.... (I still don't know for sure if thats why) I get lag spikes from 60 to 24 fps.... It might be the extremely poor optimization on Valve's part, but i've heard Comanglia's [http://www.teamfortress.tv/25328/comanglia-s-config-fps-guide](url) config helps out with these huge lag spikes; people have said that mastercomfig does not help as good. (for what ever reason) But, I don't feel like switching configs. (this is more updated). Before the update i've had no lag spikes like this, where fps suddenly drops to unplayable frames (sometimes 8-19!) for sometimes 20 seconds!
    * Config version
Latest
    * Config preset(s)
Max performance, igpu
    * Custom values (if any)
fps_max 60  //so my laptop does not burn up
    * DX levelnoticable
90
    * Launch options
-nojoy -console -full -w 1280 -h 720 -novid -dxlevel 90 -nosteamcontroller -noff -nohltv -softparticlesdefaultoff -reuse -primarysound -snoforceformat -swapcores -limitvsconst -force_vendor_id 0x10DE -force_device_id 0x1180
    * Operating system (OS)
Linux; Ubuntu 16.04
    * Graphics card (GPU)
Intel® HD Graphics 400 (Braswell)
    * Processor (CPU)
Intel® Celeron(R) CPU N3060 @ 1.60GHz × 2 
    * HDD or SSD
SSD
    * RAM size in MB or GBDisscussion
3.8 GB

Many others have been experiencing this, so it's probably valves poor optimization: (could use your help though for the time being; maybe it's something Comanglia set, that you did not, idk).

Discussion about Comanglia's config/mastercomfig (lag spikes): 
[https://www.reddit.com/r/tf2/comments/77tmu0/anyone_getting_lag_whenever_the_dragons_fury_is/](url)

More lag issues:
[https://steamcommunity.com/app/440/discussions/0/1480982338953497145/](url)
Disscussion
It's defiantly noticeable lag when your `fps_max` is 60.
Btw, the highest tf2 most of the time runs at is 60-70 fps (with out cap)

**Comment by mastercoms** [comment]
I think it is the launch options to get Pyro flames to show up.

Could you try without `-dxlevel 90 -force_vendor_id 0x10DE -force_device_id 0x1180`

also, people have reported that using window and resolution parameters reduce FPS so remove these as well `-full -w 1280 -h 720`

**Comment by PoorPocketsMcNewHold** [comment]
I do have some Lags Spike issues as well, with the same situations.

* Config version
Latest
* Config preset(s)
Max quality (Using max performance didn't help at all).
* Custom values (if any)
fps_max 60 //Simply because i doesn't need more.
sv_forcepreload 1
cl_forcepreload 1
snd_async_fullyasync 1 //All three of them are supposed to fix this issue, by precaching the textures when you first load a game. "Apparently". Seems to have enhanced a bit the situation, Could be a placebo effect.
* DX levelnoticable
95
* Launch options
-borderless -noborder -windowed -console -novid +snd_surround_speakers 7 -nojoy -nosteamcontroller -noff -nohltv -softparticlesdefaultoff -reuse -primarysound -snoforceformat -swapcores
* Operating system (OS)
Windows 10, Insider build 17025.
* Graphics card (GPU)
Nvidia GeForce GTX 1060 6GB
* Processor (CPU)
Intel® Core i7-4790
* HDD or SSD
HDD
* RAM size in MB or GBDisscussion
32GB (8*4)

I will try what you've proposed to T-Oaster.

**Comment by mastercoms** [comment]
I wouldn't recommend using max quality, you can try the default config with no presets or the midquality preset. Max quality is extremely graphically and CPU intensive with lots of unoptimized values for quality's sake.

Although you may not need the frame output, lots of other operations run per frame including input and networking. In your case, there is no reason not to use `fps_max 300`, so I would recommend removing that extra command. `cl_forcepreload` was removed in the Tough Break update because it was causing stuttering issues. Do not use `sv_forcepreload`, as it causes the same thing. `snd_async_fullyasync 1` is already in the config.

**Comment by mastercoms** [comment]
@T-oasterO-ven @PoorPocketsMcNewHold Any updates on this?

**Comment by PoorPocketsMcNewHold** [comment]
Seems to be working well for me. Issue closed for me then.

**Comment by mastercoms** [comment]
Alright, closing the issue then. @T-oasterO-ven feel free to reopen if you still have issues.

**Comment by T-oasterO-ven** [comment]
Update: Sorry I've very busy this week; I haven't been able to check up on things recently. I'll go ahead and take your advice on this and report back soon. (Tomorrow it's like 12:30 am here)

**Comment by T-oasterO-ven** [comment]
Ok so it kinda worked... kinda. The random lag is gone (mostly), but now there is systematic lag. Everytime the console spams this (often)--the whole game lags to unplayable frames.

Attemped to precache unknown particle system "rockettrail_RocketJumper"!
Attemped to precache unknown particle system "furious_flyer_activated"!
Attemped to precache unknown particle system "furious_flyer_activated_burst"!
Attemped to precache unknown particle system "furious_flyer_activated_fire"!
Attemped to precache unknown particle system "rd_robot_explosion_bits"!
Attemped to precache unknown particle system "rd_robot_explosion_smoke"!
Attemped to precache unknown particle system "rd_robot_explosion"!
Attemped to precache unknown particle system "rd_robot_explosion_smoke_linger"!
Attemped to precache unknown particle system "rd_robot_exposion_glow"!
Attemped to precache unknown particle system "rd_robot_explosion_shockwave"!
Attemped to precache unknown particle system "rd_robot_explosion_shockwave2"!
Attemped to precache unknown particle system "rd_robot_explosion_bits2"!
Attemped to precache unknown particle system "rd_robot_explosion_trail_smoke3"!
Attemped to precache unknown particle system "rd_robot_explosion_trail"!
Attemped to precache unknown particle system "rd_robot_explosion_trail_smoke2"!
Attemped to precache unknown particle system "ExplosionCore_Wall_Jumper"!
Attemped to precache unknown particle system "ExplosionCore_MidAir_Jumper"!
Attemped to precache unknown particle system "taunt_gasblast_01"!
Attemped to precache unknown particle system "torch_red_core_1"!
Attemped to precache unknown particle system "flamethrower_rope"!
Attemped to precache unknown particle system "flamethrower_pilot_rope"!
Attemped to precache unknown particle system "flamethrower_drips_rope"!
Attemped to precache unknown particle system "flamethrower_fire_1_rope"!
Attemped to precache unknown particle system "torch_player_burn"!
Attemped to precache unknown particle system "torch_red_temp"!
Attemped to precache unknown particle system "flamethrower_fire_singular"!
Attemped to precache unknown particle system "new_flame_fan"!
Attemped to precache unknown particle system "new_flame_fan_drips_a"!
Attemped to precache unknown particle system "new_flame_fan_drips_b"!
Attemped to precache unknown particle system "new_flame_rope"!
Attemped to precache unknown particle system "new_flame_fan_crit_blue"!
Attemped to precache unknown particle system "new_flame_fan_crit_red"!
Attemped to precache unknown particle system "taunt_pyro_gasblast_rainbow"!
Attemped to precache unknown particle system "new_flame_waterfall"!
Attemped to precache unknown particle system "new_flame_waterfall_core"!
Attemped to precache unknown particle system "new_flame_waterfall_pilot"!
Attemped to precache unknown particle system "flamethrower_halloween_crit_red_new_flame"!
Attemped to precache unknown particle system "flamethrower_halloween_new_flame"!
Attemped to precache unknown particle system "flamethrower_halloween_crit_blue_new_flame"!
Attemped to precache unknown particle system "dragons_fury_effect_parent"!
Attemped to precache unknown particle system "dragons_fury_FloatieEmbers"!
Attemped to precache unknown particle system "flamethrower_rainbow_new_flame"!A
Attemped to precache unknown particle system "flamethrower_rainbow_new_flame_stars"!
Attemped to precache unknown particle system "flamethrower_rainbow_new_flame_pilot"!
Attemped to precache unknown particle system "blood_impact_red"!

Attemped to precache unknown particle system "ExplosionCore_Wall_Jumper"!
^This one happens the most... and lags the game.

**Comment by mastercoms** [comment]
I would verify game cache.

**Comment by T-oasterO-ven** [comment]
Tried that twice; it did not work.

Did not have these issues before....

**Comment by T-oasterO-ven** [comment]
@mastercoms So, if it's not the game cache, then what is it?

**Comment by mastercoms** [comment]
That's really strange. I guess your only option is to reinstall and see if that fixes it.

**Comment by T-oasterO-ven** [comment]
I tried that before I found out about the 'vendor/device' fix--did not work.

I'll try again...

**Comment by T-oasterO-ven** [comment]
@mastercoms 
Tried reinstalling twice, did not work. (Precache errors spamming every so often still, causes lag spikes)
Options?
Will the "vendor cmds" fix it? Or will that cause lag spikes like before still? (except this time on `-dxlevel 92`)

Any other help is appreciated.
Thanks.

**Comment by mastercoms** [comment]
Do you have any custom particles or anything like that?

**Comment by T-oasterO-ven** [comment]
@mastercoms
yes (Longer needle trails and light particle pack, Unzipped from vpk via GCFScape, and I customized it for the new update) but using it does not change anything in the console (regardless I get the errors).

**Comment by mastercoms** [comment]
So even without any custom files, you still get the precache errors?

**Comment by T-oasterO-ven** [comment]
@mastercoms 
Yes

**Comment by mastercoms** [comment]
I have no idea then. Try reporting it to Valve: https://github.com/valvesoftware/source-1-games

**Comment by T-oasterO-ven** [comment]
@mastercoms 
I did what you said and reported it to valve. If you still want to help, then feel free to head over.
I found out some more info from console logs, system specs, and combing through the mastercoms (in /tf/custom) folder with the fps stuff. 

I uploaded your "comfig" (customized a bit) in case you want to inspect it. (I changed some things, previously forgot) 

Thanks for your continued support so far.

**Comment by mastercoms** [comment]
Oh, it might be the -limitvsconst launch option.

**Comment by T-oasterO-ven** [comment]
@mastercoms 

Tried removing that option..... it did not work.

**Comment by T-oasterO-ven** [comment]
@mastercoms
I did a lot of research and found that for **integrated Intel GPUs (Laptops)** use this specific id pair; for some reason using this over the other id pair **fixed all the lag**.

-force_vendor_id 0x8086 -force_device_id 0x22b1 

Intel's vendor ID is: 0x8086
Using the ``hardinfo`` Linux package I identified the VGA device ID: 0x22b1
Then I plugged them in and the lag spikes don't happen under normal circumstances.

Feel free to use this info as you wish.
