### ISSUE TITLE
No Pyroland Addon doesn't work

### ISSUE THREAD

**Issue by Tiagoquix** [mastercoms/tf2cfg#158]
**Describe the bug**
The addon "No Pyroland" doesn't work. It conflicts with the already existent `mtp.cfg` in any mastercomfig presets. The addon is useless and should be descarted.

**How you encountered the issue**
I encountered the issue by exploring the files in the `.vpk` files.

**Desktop (please complete the following information):**
* Config version: don't say latest, say the actual version, found by running `version_comfig` in console: mastercomfig version: 8.2.2 | November 23 2019
* Config preset and addon(s): medium-low, no extra models, no tutorial and no pyroland for the test
* Custom values (if any): This is my modules.cfg:
download=all
lod=high
lighting=medium_high
shadows=off
effects=low
water=ultra
particles=low
post_processing=off
pyrovision=low
motion_blur=off
aa=off
aa_msaa=off
texture_filter=trilinear
characters=ultra
decals=low
decals_models=off
decals_art=on
sprays=on
gibs=off
lowviolence=off
props=medium
ragdolls=off
3dsky=on
jigglebones=off
sheens_speed=low
sheens_tint=high
textures=very_high
texture_blending=off
bumpmap=on
specular=on
ropes=ultra
hud_player_model=on
hud_panels=on
messages=enable
killfeed=on
killstreaks=high
outlines=high
dynamic_background=off
sound=ultra
* DX level: 95
* Launch options: -novid -nojoy -nosteamcontroller -softparticlesdefaultoff -nohltv -particles 1 -primarysound -snoforceformat
* Operating system (OS): Windows 10 Pro 64-bits
* Graphics card (GPU): NVIDIA GeForce GTX 1050 Ti
* Graphics driver version: 441.66
* Processor (CPU): AMD FX(tm)-6300 Six Core Processor
* TF2 on HDD or SSD: HDD
* Memory (RAM) size in MB or GB: 8 GB

**Comment by mastercoms** [comment]
This can be fixed by renaming the file. I will be changing all addons to be of the format `mastercomfig-addon-name` and presets to be `mastercomfig-preset-name`. Because you are using **m**edium-low (`mastercomfig-medium-low-preset`), **m** comes before the alphabet than **n** in **n**o-pyroland (`mastercomfig-no-pyroland-addon`).
