### ISSUE TITLE
Facial Animations Are Choppy

### ISSUE THREAD

**Issue by agunzagun** [mastercoms/tf2cfg#16]
Hello,

Quick bug to report, using the latest available download for the config, facial animations have a choppy, low quality look to them - even against the max quality set.

Doing a reset and defaulting back to my previous config (comanglia's cinema.cfg) facial animations are once again smooth. Repeating the cleanup process and dropping your configs in again yields choppy facial animations.

Steps to reproduce:

- install cfgs
- load local map, pick class (heavy is easiest taunt to see for me in this instance)
- stand near wall (for zoom), do a normal taunt, and move the camera to the face
- facial animations are choppy

Tested further, running the maxquality preset against cinema.cfg yields high quality facial animations, so the issue seems to be in comfig. I've edited the same r_lod and r_rootlod settings in comfig but it is still choppy so the issue seems to be in a command(s) I am unfamiliar with.

**Comment by mastercoms** [comment]
The `maxquality` preset should now properly smooth talking animations. It's in the latest dev version, so you'll have to download it from [here](https://github.com/mastercoms/tf2cfg/archive/d5519e989e5ac465f4cf258bb36acb5776b7d1f6.zip).

**Comment by mastercoms** [comment]
Now released in [5.0.2](https://github.com/mastercoms/tf2cfg/releases/tag/5.0.2).
