### ISSUE TITLE
Pyroland textures not appearing

### ISSUE THREAD

**Issue by AtomicTEM** [mastercoms/tf2cfg#162]
**Describe the bug**

Pyroland textures aren't appearing on certain maps.

**How you encountered the issue**
Tell us the steps on how to recreate the bug.

Playing casual.

**Screenshots**

**Desktop (please complete the following information):**
* Config version: 8.2.2
* Config preset and addon(s): Ultra
* Custom values (if any):
* DX level: 9.8
* Launch options: -novid -nojoy
* Operating system (OS): Windows 10
* Graphics card (GPU): GTX 1050 ti
* Graphics driver version: 441.87
* Processor (CPU): intel I7
* TF2 on HDD or SSD: SSD
* Memory (RAM) size in MB or GB: 24GB

**Comment by KaineWooten** [comment]
There are some maps in TF2 that don't have the pyroland textures over them like some others do. It's weird I know but that's just how it went.

**Comment by AtomicTEM** [comment]
ok so I instlled a mods that add the pyroland textures to other maps
and it works only when i dont have mastercomfig installed

**Comment by AtomicTEM** [comment]
It seems removing half of the maps in the mtp.cfg fixes the problem.
