### ISSUE TITLE
Remove mtp.cfg

### ISSUE THREAD

**Issue by Tiagoquix** [mastercoms/tf2cfg#167]
**Is your feature request related to a problem? Please describe.**
I don't think the config should change the default mtp.cfg file. If users want to have more pyroland compatible maps, they will search for a mod for this.

**Describe the solution you'd like**
Just remove mtp.cfg.

**Describe alternatives you've considered**
An alternative is to clean up the file and only include official maps (except Invasion maps).

**Additional context**
Nothing more.

**Comment by mastercoms** [comment]
What is this affecting? Disable pyroland disables pyroland, and mastercomfig is supposed to improve the defaults.
