### ISSUE TITLE
some textures look weird while using solid textures mod

### ISSUE THREAD

**Issue by Augixx** [mastercoms/tf2cfg#17]
Config version: 5.1.3
Config preset: comp
DX level: 95
Launch options: -novid -nojoy -nosteamcontroller -noff -nohltv -softparticlesdefaultoff -reuse -primarysound -snoforceformat -swapcores -high -nostartupsound
Problem:
Im uing a solid textures mod and it works fine with chris cfg, but have some problems with this cfg.
Is there any way to remove these textures like chris cfg does?

with this cfg:
![20171123105933_1](https://user-images.githubusercontent.com/29351632/33157860-417cf84a-d040-11e7-92c2-fd1f9e06044c.jpg)
![20171123105944_1](https://user-images.githubusercontent.com/29351632/33157962-07253580-d041-11e7-87d7-f9ba582a96a9.jpg)
![20171123105954_1](https://user-images.githubusercontent.com/29351632/33157963-075535e6-d041-11e7-8ef7-c8dcb1e3e84a.jpg)

with chris cfg:
![20171123114932_1](https://user-images.githubusercontent.com/29351632/33158417-d00df07e-d044-11e7-9ac0-642f4f006de8.jpg)
![20171123115004_1](https://user-images.githubusercontent.com/29351632/33158418-d0403c5a-d044-11e7-9bb6-f6501026d0b5.jpg)
![20171123115035_1](https://user-images.githubusercontent.com/29351632/33158419-d072bda6-d044-11e7-902b-a0a53c7b6527.jpg)

without solid textures mod:
![20171123111013_1](https://user-images.githubusercontent.com/29351632/33157964-07861f3a-d041-11e7-91c4-75f1939b99a8.jpg)
![20171123111042_1](https://user-images.githubusercontent.com/29351632/33157965-07b6bb90-d041-11e7-855b-5ab6d7893245.jpg)
![20171123111116_1](https://user-images.githubusercontent.com/29351632/33157966-07e864b0-d041-11e7-8c77-81d2abd3da21.jpg)

**Comment by mastercoms** [comment]
r_renderoverlayfragment 0
