### ISSUE TITLE
Let us edit from ultra to very low comfigs

### ISSUE THREAD

**Issue by Zones5656** [mastercoms/tf2cfg#197]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mastercoms** [comment]
Hi, did you mean to close this issue? I'd love to know what you wanted for this.

**Comment by Zones5656** [comment]
I just wanted to see chat aggain

**Comment by mastercoms** [comment]
You can edit the config by using user/autoexec.cfg.
