### ISSUE TITLE
Site issues

### ISSUE THREAD

**Issue by Tiagoquix** [mastercoms/tf2cfg#200]
**The issues**
I found two issues on the site.

1- The download function is slow, it takes like 2 seconds to download every file. Also, sometimes the preset doesn't download.

2- The links to "Troubleshoot issues" (Troubleshooting and feedback) and "Check them out!" (See Also) uses the latest version of docs rather than the stable version.

**Comment by mastercoms** [comment]
In the future, report each bug separately.

1) You can use the alternate "Download manually" option.
2) Fixed.
