### ISSUE TITLE
DirectX Levels

### ISSUE THREAD

**Issue by Tiagoquix** [mastercoms/tf2cfg#210]
I have a two questions about the DirectX levels.

1- Why the DirectX 8/8.1 documentation has been removed from the docs?
2- Why is DirectX 9.5 the recommended DXLevel by the docs and not 9.0, 9.2 or 9.8? In the past, the recommended DXLevel was 9.8.

That is all.

**Comment by mastercoms** [comment]
1. It is an attempt to reduce the new user rate of DirectX 8, so that the game's DX8 usage will stagnate and decline, leading to more options for Valve to optimize the game by dropping DX8 support.
2. 92 only works on Linux and Mac. 98 only works on Xbox 360. 90 is not the highest feature level and has unoptimized GPU/resource usage/management.

**Comment by Tiagoquix** [comment]
@mastercoms About the current recommended DirectX (dxlevel 100), is it really necessary?

I think not. It just makes users have to worry about something that I consider to be kind of unnecessary, since the default dxlevel for the vast majority of systems is dxlevel 95.

I suppose the Source Engine itself determines the proper value when booting the game for the first time (e.g. I think on very old systems with parts from over 15 years ago maybe TF2 puts DirectX 8.1 by default -- amazingly the game still runs on Windows XP).

**Comment by Tiagoquix** [comment]
> @mastercoms About the current recommended DirectX (dxlevel 100), is it really necessary?
> 
> I think not. It just makes users have to worry about something that I consider to be kind of unnecessary, since the default dxlevel for the vast majority of systems is dxlevel 95.
> 
> I suppose the Source Engine itself determines the proper value when booting the game for the first time (e.g. I think on very old systems with parts from over 15 years ago maybe TF2 puts DirectX 8.1 by default -- amazingly the game still runs on Windows XP).

@mastercoms Hello. Could you please reply to this? Thanks in advance.
