### ISSUE TITLE
Weird crashes mid-game

### ISSUE THREAD

**Issue by Frinzie** [mastercoms/tf2cfg#22]
### 1. Problem
When I am playing a map (I've only played on official maps since installing) after some time of playing, my game just crashes ("not responding" window pops up). I don't know the reason this might be happening.
### 2. Settings
Config version: 6.1.1
Config preset: comp (no addons)
Custom changes to the config:
- mat_levelflush 1
- mat_phong 1

Launch options: -dxlevel 95 -novid -nojoy -nosteamcontroller -nohltv -softparticlesdefaultoff -reuse -swapcores
OS: Windows 10 Home
GPU: Geforce GTX 650M
CPU: Intel i7-3610QM
Hard Drive: 2 HDDs
RAM: 8GB

My config:
https://pastebin.com/z01n8mpX

**Comment by mastercoms** [comment]
Maybe mat_levelflush 1 is the problem?

**Comment by Frinzie** [comment]
I don't know why, but after changing the launch settings to "-novid -nojoy -nosteamcontroller -nohltv -softparticlesdefaultoff -reuse -swapcores -w 1280 -h 720 -full" it seems to work now. Maybe DX95 was the problem

**Comment by mastercoms** [comment]
Well, you are supposed to remove the `-dxlevel` launch option after the first time.

**Comment by Frinzie** [comment]
oh, ok, I didn't know that. Thanks
