### ISSUE TITLE
autoexec.cfg executes addons twice

### ISSUE THREAD

**Issue by Tiagoquix** [mastercoms/tf2cfg#220]
This does not seems to be necessary. I think only executing an addon after the comfig has been loaded is the sufficient.

**Comment by mastercoms** [comment]
This was used for experimental addon, but is not used anymore. Thanks for the catch.

**Comment by Tiagoquix** [comment]
> This was used for experimental addon, but is not used anymore. Thanks for the catch.

Alright. But executing an addon before the comfig was loaded is unnecessary. Executing an addon right after the comfig is loaded is the correct and necessary, and this also possibilities the addon to override comfig defaults.

**Comment by mastercoms** [comment]
Yes, it was used in the experimental addon to override module definitions (changing snapshots module), and then run settings to override some comfig defaults. But now it's not used, so it should be removed.

**Comment by Tiagoquix** [comment]
> Yes, it was used in the experimental addon to override module definitions (changing snapshots module), and then run settings to override some comfig defaults. But now it's not used, so it should be removed.

Yes, I understood. What I have said is: you did not needed to execute the addons twice even with the experimental addon. Executing the addons right after the comfig has been executed (that is, once the main comfig has been executed) would be sufficient.

**Comment by mastercoms** [comment]
Well, modules run can apply new values after comfig, and then if experimental or any other addon overrode a value in a module, then it would be overwritten by the modules run.
