### ISSUE TITLE
setinfo command

### ISSUE THREAD

**Issue by Tiagoquix** [mastercoms/tf2cfg#224]
It is really necessary to have `setinfo` in `cl_interp` and `cl_interp_ratio` commands?
Just a question.

**Comment by mastercoms** [comment]
Not sure, it's just to be safe, and make sure to send it to the server

**Comment by Tiagoquix** [comment]
`setinfo` is used to change a custom command description, but ok.

**Comment by mastercoms** [comment]
It's not actually. It sets the value of user info console variables, which are sent to the server.

**Comment by Tiagoquix** [comment]
> It's not actually. It sets the value of user info console variables, which are sent to the server.

If we follow this logic, we would have to use `setinfo` in every command.

**Comment by mastercoms** [comment]
No, because the server doesn't read every client console variable. Only user info ones.
