### ISSUE TITLE
Effects module descriptions

### ISSUE THREAD

**Issue by Tiagoquix** [mastercoms/tf2cfg#230]
In the modules page, the `effects=high` and `effects=ultra` have the same description, but in config the only differente is that `effects_ultra` has `cl_ejectbrass` enabled, while `effects=high` doesn't have.

**Comment by mastercoms** [comment]
I think the description should be updated.

**Comment by mastercoms** [comment]
Fixed in https://github.com/mastercoms/mastercomfig/commit/1248a9be9ef481d1ba101886b4c7fcb82d0f8984
