### ISSUE TITLE
White line on all config files

### ISSUE THREAD

**Issue by Tiagoquix** [mastercoms/tf2cfg#231]
In the last changelog, it is wrote:

```
Removed all forms of extra whitespace and empty lines from packaged files
This saves some space on the VPKs.
```

This is not true. If you open any config file inside the .VPK file you can see that every file has a white line on its end.

**Comment by mastercoms** [comment]
This is just the end of line new line, which is standard on most systems.

**Comment by Tiagoquix** [comment]
> This is just the end of line new line, which is standard on most systems.

Yeah, but will you remove it?

**Comment by mastercoms** [comment]
I will look into it.

**Comment by mastercoms** [comment]
Closing this in favor of #234.
