### ISSUE TITLE
Further steps in making .vpk smaller

### ISSUE THREAD

**Issue by micwoj92** [mastercoms/tf2cfg#234]
**Is your feature request related to a problem? Please describe.**
Still some size can be easily shaved off the .vpk
**Describe the solution you'd like**
Remove all unneeded quotes for example in files like this https://github.com/mastercoms/mastercomfig/blob/release/config/addons/mastercomfig-no-extra-models-addon/scripts/extra_models.txt
**Describe alternatives you've considered**
None

**Additional context**
There are also bigger files with lots of quotes and spaces/tabs like
https://github.com/mastercoms/mastercomfig/blob/release/config/mastercomfig/glbaseshaders.cfg

but I am not 100% sure if these are needed for better formatting or not. 
This weekend/next week I will check for all files and create pr.

**Comment by micwoj92** [comment]
Pull request #235

**Comment by micwoj92** [comment]
@mastercoms  there is also lots of unnecessary characters in these files, but they are much bigger and I am not sure if you need tabs for formatting, can they be removed?


![Screenshot_20200313_120050_de baumann browser](https://user-images.githubusercontent.com/45581170/76615443-59511180-6522-11ea-9845-1792a601e583.jpg)

**Comment by mastercoms** [comment]
Removing those should be fine.

**Comment by mastercoms** [comment]
@Perkzitos @micwoj92 Thinking about it further, I think we should only be removing extraneous quotes from files, and maybe some other situation specific characters. Tabs, spaces, and comments can be stripped in the build script.

**Comment by micwoj92** [comment]
Lol why didnt I think about it, but anyway I think I did remove all in #235

**Comment by mastercoms** [comment]
Fixed in https://github.com/mastercoms/mastercomfig/commit/1248a9be9ef481d1ba101886b4c7fcb82d0f8984
