### ISSUE TITLE
AA gets set to 0 on Ultra config

### ISSUE THREAD

**Issue by thefierybreeze** [mastercoms/tf2cfg#238]
If you use the Ultra config anti aliasing is non existent
A workaround i did was use the information here:
https://old.reddit.com/r/tf2/comments/cbb6t3/can_i_set_different_settings_for_different_devices/etekmpn/
and 
change the line that makes 16x alias
![image](https://user-images.githubusercontent.com/34712913/77253735-db4ce300-6c64-11ea-9904-fd45512189a0.png)

**Desktop (please complete the following information):**
* Config version: 8.3.10
* Config preset and addon(s):
Ultra, no extra models, null canceling, no tutorial, falt mouse
* Custom values (if any):
* DX level: 9
* Launch options: none
* Operating system (OS): win10
* Graphics card (GPU): RX 5700
* Graphics driver version: 20.2.2
* Processor (CPU): R5 3600
* TF2 on HDD or SSD: SSD
* Memory (RAM) size in MB or GB: 16GB

**Comment by mastercoms** [comment]
That's not 8.3.10. This line was changed in 8.3.2.
