### ISSUE TITLE
why forcing tf_romevision_opt_in 1 by default ?

### ISSUE THREAD

**Issue by adri-hub** [mastercoms/tf2cfg#239]
I recently rearranged my config files and saw that robots had additional hats on. I found that for some reason, the command 'tf_romevision_opt_in 1' was in the comfig.cfg file.

I want to know if this is impacting the game performance in a good way, because adding the hats to the robots seems like doing the opposite + the new carrier tank look.

Therefore, how is it working ? is this an additional texture on top of the original one ? is this removing the classic one with the rome model ? and if so, which one is lighter ?

**Comment by mastercoms** [comment]
That's a good point. I never thought about the performance impact. I will look into it.
