### ISSUE TITLE
How fast in Mbps should my Internet be to handle this?

### ISSUE THREAD

**Issue by ghost** [mastercoms/tf2cfg#25]
https://github.com/mastercoms/mastercomfig/blob/a4d4ec2b7c4a767cc6b9af246b6b9aaeef3b6782/mastercomfig/cfg/comfig.cfg#L30

**Comment by alamo2914** [comment]
I'm pretty sure mastercoms wrote 100Mbps in the discord a few days ago.

**Comment by mastercoms** [comment]
Yep, but more testing should be done before I put that in the config.
