### ISSUE TITLE
SourceTV recommended optional convars in server.cfg

### ISSUE THREAD

**Issue by Wiethoofd** [mastercoms/tf2cfg#271]
**Describe the solution you'd like**
A set of *recommended* convars for STVs to be optional for server operators.

**Additional context**
Mastercomfig is, as far as I know, a mostly client focused set of configs, with high customizability, however it still provides a `server.cfg` (but no *listenserver* for local servers), which currently does not contain any Source TV related convars.

Suggestion to add some/all of the following with descriptions and default comment some out:
```
// tv_enable 1 // Enable SourceTV
tv_delay 0 // the STV Delay in seconds (recommended 90 or 0)
tv_password "tv" // Protect the SourceTV with a password

tv_allow_camera_man 0 // Spectators can be come camera man when enabled
// tv_chattimelimit 2 // Limit chat messages to every n seconds (default = 8)
tv_delaymapchange 1 // Delays map change until broadcast is complete
tv_delaymapchange_protect 1 // Protect against doing a manual map change
// tv_maxclients 15 // Limit maximum number of clients (recommend using relay for overflow), each slot takes up memory & network bandwidth
tv_maxrate 0 // Unlimited bandwidth rate (default 8k is not enough when plugin SrcTV+ is used)
tv_snapshotrate 66 // Default 16 snapshot rate results in choppy client playback
tv_transmitall 1 // Broadcast everything to client for freeroaming in STVs

// tv_name "SourceTV" // SourceTV host name
// tv_title "SourceTV" // Name of the STV that shows in a 'Spectator' slot
```
Note about `tv_maxrate` and [SrcTV+](https://github.com/dalegaard/srctvplus):
> *recommended to set this to at least 20000 or if possible 0, for unlimited bandwidth, especially with increased `tv_snapshotrate`*.

`tv_maxclients` defaults to 128, which might [cause memory problems](https://github.com/stephanieLGBT/rgl-server-resources/issues/14#issuecomment-592487328) on shared server hosting.

`tv_port` should not be set in configs, but through the launch options instead when starting the server.

**Comment by mastercoms** [comment]
https://github.com/mastercomfig/comfig-fortress/blob/master/tf2/server/tf/cfg/tv.cfg
