### ISSUE TITLE
No Pyroland causes CTD on Valve Servers

### ISSUE THREAD

**Issue by ann4belle** [mastercoms/tf2cfg#277]
**Describe the bug**
The "No Pyroland" addon occasionally causes the game to CTD when joining Valve servers (more likely, any server with sv_pure set like Valve's, but I haven't tested this).

**How you encountered the issue**
1. Install No Pyroland addon
2. Join Valve server
3. Join another Valve server

Step 3 will usually (about 90% of the time in my testing) cause a crash. Occasionally step 2 will cause a crash, but this is uncommon.

**Desktop (please complete the following information):**
* Config version: 8.101.0 | May 14 2020
* Config preset and addon(s): Ultra, No Pyroland, No Tutorials, Flat Mouse
* Custom values (if any):
* DX level: 100 (according to `mat_dxlevel`)
* Launch options: `-novid -nojoy -nosteamcontroller -nohltv -particles 1 -NoQueuedPacketThread +cl_clean_textures_on_death 1 +mat_lodin_time 0 -windowed -noborder -w 1920 -h 1080`
* Operating system (OS): Win10 Pro 1909 (18363.836)
* Graphics card (GPU): NVIDIA RTX 2080 Super
* Graphics driver version: 26.21.14.4587 (4/3/2020)
* Processor (CPU): Ryzen 7 2700X @ 4.1 GHz
* TF2 on HDD or SSD: SSD
* Memory (RAM) size in MB or GB: 32GB

**Comment by Tiagoquix** [comment]
Can you test it by downloading the mastercomfig zip package, and then removing the mtp.cfg the config provides and use only the mtp.cfg that comes along with no pyroland addon? Probably the files are conflicting with themselves.

**Comment by mastercoms** [comment]
Are you sure it is disable pyroland causing the issue? Do you have any other mods?

**Comment by ann4belle** [comment]
@mastercoms Well, now I have no idea what was causing it, because it resolved itself. I didn't have any mods other than mastercomfig, budhud, and my hitsound and killsound. I'll go ahead and close the issue.
