### ISSUE TITLE
Add gl_clear convar for Windows users

### ISSUE THREAD

**Issue by pongo1231** [mastercoms/tf2cfg#28]
When I used Windows 10, **gl_clear 1** had a small performance increase on both dxlevel 8 and 9 (about 2-3% or so). Unfortunately I can't provide a benchmark on Windows as I'm not on Windows anymore.

What I can give instead is a Linux benchmark though, but here's where the problem persists: it decreases fps on Linux. I'm not sure if it's a OpenGL issue, as I still have gotten the same fps boost on Windows with **-r_emulate_gl**.

**Benchmark with maxperformance preset + badgpu and ssd preset:**
_gl_clear 0_
> 4812 frames 79.043 seconds 60.88 fps (16.43 ms/f) 5.276 fps variability

_gl_clear 1_
> 4812 frames 82.728 seconds 58.17 fps (17.19 ms/f) 4.480 fps variability

[Benchmark used](http://www.teamfortress.tv/42867/mastercomfig-fps-customization-config/?page=19#556)

**My startup parameters:**
`-novid -nojoy -nosteamcontroller -noff -softparticlesdefaultoff -reuse -limitvsconst -nohltv -gl_enablesamplerobjects`

**My specs:**
OS: Arch Linux x86_64 (with 4.14.15 kernel in case it's relevant)
CPU: i3-7100U
iGPU: Intel HD 620
RAM: 4GB

Again, I'm sorry for not being able to provide any benchmarks on Windows.
In case this gets added, I'd suggest to add a Linux addon which reverts this convar and perhaps contains more Linux-specific convars later on.
I don't know how this convar behaves on Mac OS, this would need some testing.

If there are more information needed, I'd be happy to provide.

**Comment by mastercoms** [comment]
Hi, thanks for looking into this. However, I don't think this will be included in the config.

This convar is very OS and hardware dependent and it's not very clear what the general benefits are, if any.

**Comment by pongo1231** [comment]
Perhaps it could be added under Experimental Startup Options (+gl_clear 1) in the autoexec.cfg. It already contains some OS and spec-dependent options, so IMO it would fit there.

Like I said, I had a slight but notable fps increase when using it on Windows and there were no side effects or similar when using it.

Or maybe someone on Windows and with a Intel HD GPU could do some benchmarking to confirm if it actually has a fps increase on specific GPUs.

Otherwise I could do a clean Windows install later on to confirm if it has any positive effects whatsoever or if it was just some weird quirk that made it appear like gl_clear 1 actually increase fps.

Like I said before, I'd be happy to do some more investigations on this later on.

**Comment by pongo1231** [comment]
Perhaps someone on Windows and with a Intel HD GPU could do some benchmarking to confirm if it actually has a fps increase on specific GPUs.

Otherwise I could do a clean Windows install later on to confirm if it has any positive effects whatsoever or if it was just some weird quirk that made it appear like gl_clear 1 actually increase fps.

**Comment by mastercoms** [comment]
Ok, I will investigate this further and you can too if it isn't a problem for you to do so.

**Comment by mastercoms** [comment]
After more investigation, I don't think gl_clear improves FPS.
