### ISSUE TITLE
Hitsound not working

### ISSUE THREAD

**Issue by ghost** [mastercoms/tf2cfg#285]
**Describe the bug**

**How you encountered the issue**
Tell us the steps on how to recreate the bug.

**Screenshots**

**Desktop (please complete the following information):**
* Config version: don't say latest, say the actual version, found by running `version_comfig` in console
* Config preset and addon(s):
* Custom values (if any):
* DX level:
* Launch options:
* Operating system (OS):
* Graphics card (GPU):
* Graphics driver version:
* Processor (CPU):
* TF2 on HDD or SSD:
* Memory (RAM) size in MB or GB:

**Comment by mastercoms** [comment]
Could you provide the information as part of the template? I can't help you otherwise, since there's no information on what could cause this.
