### ISSUE TITLE
Update url on profile

### ISSUE THREAD

**Issue by micwoj92** [mastercoms/tf2cfg#288]
**Describe the bug**
The url on your(Mastercoms') Steam profile points to old url, https://github.com/mastercoms/mastercomfig

**How you encountered the issue**
Tell us the steps on how to recreate the bug.
1. Go to https://steamcommunity.com/id/mastercoms
2. Click on mastercomfig in 'Projects' text showcase.
**Screenshots**
![Screenshot_20200525_020507_com cookiegames smartcookie](https://user-images.githubusercontent.com/45581170/82768008-39946e80-9e2c-11ea-93cf-d79b659c3197.jpg)
highlighted text
![Screenshot_20200525_020513_com cookiegames smartcookie](https://user-images.githubusercontent.com/45581170/82768013-46b15d80-9e2c-11ea-9347-6a339fa541de.jpg)
Steam redirect page
**Desktop (please complete the following information):**
* Config version: don't say latest, say the actual version, found by running `version_comfig` in console not applicable
* Config preset and addon(s):not applicable
* Custom values (if any):not applicable
* DX level:not applicable
* Launch options:not applicable
* Operating system (OS): Android 9.1.0.175 EMUI 9.1.0
* Graphics card (GPU): MALI-T830
* Graphics driver version: GLES 3.2
* Processor (CPU): Hisilicon Kirin 659  arm64-v8a not overclocked
* TF2 on HDD or SSD: not applicable
* Memory (RAM) size in MB or GB: 3.0GB

**Comment by mastercoms** [comment]
Fixed, thanks!
