### ISSUE TITLE
voice_fadeouttime

### ISSUE THREAD

**Issue by Tiagoquix** [mastercoms/tf2cfg#298]
Is the value change for this command really necessary? My friend said that my voice was cutting out whenever I stop using my mic, since the voice transmition have a minor delay to transmit all properly. When I set the command to its default value, this stopped happening. The command acts like a push-to-talk delay after stop talking. My suggestion is to not touch this command, since it is primarily used to musicspam.

**Comment by mastercoms** [comment]
Fixed in https://github.com/mastercomfig/mastercomfig/commit/86dadfcbff030921eb71cb80433f6887923a4d78
