### ISSUE TITLE
add spydish? windows 10 os optimization

### ISSUE THREAD

**Issue by uesu** [mastercoms/tf2cfg#311]
https://github.com/mirinsoft/spydish

spydish supports `windows 10, version 2004`

quickly perform a **privacy check, disable telemetry, disable cortana, uninstall pre-installed apps**

easy to use, has instructions and details on what do these do

has a community package for advance scripting features based on powershell for debloating windows 10 but it's for `advance users only`

**Comment by mastercoms** [comment]
What's the benefit over Win10 Privacy?

**Comment by mastercoms** [comment]
Currently listed here: https://docs.mastercomfig.com/en/latest/os/windows/#disable-unnecessary-services

**Comment by micwoj92** [comment]
Only "benefit" I see is that it is open source, but win10privacy seems more popular, at least for me.

**Comment by mastercoms** [comment]
There's no license, but I guess source available is good too.

**Comment by micwoj92** [comment]
Ah didnt even notice

nvm lol https://github.com/mirinsoft/spydish/issues/1

**Comment by mastercoms** [comment]
Oh, well, I don't think there's any reason then to add it over W10Privacy which has more features and is more popular.

**Comment by uesu** [comment]
Sorry for the late reply,

I haven't used w10privacy before, but after testing it, it was the same when you want to clean and debloat windows, but w10privacy has more features and you can create a system restore point incase something is wrong.

Conclusion: I believe that w10privacy is better than spydish. W10Privacy offers a lot of things and has that color of safety that indicates whether is it safe to disable that service or not.
