### ISSUE TITLE
Steam about page has typo

### ISSUE THREAD

**Issue by micwoj92** [mastercoms/tf2cfg#323]
**Describe the bug**
The page of mastercomfig's group on Steam has a typo.

**How you encountered the issue**
Tell us the steps on how to recreate the bug.
1. Go to https://steamcommunity.com/groups/comfig
2. Read the about section.
3. Find that "Ko-fi" brand name is missspelled.
**Screenshots**
![Screenshot_20200622_005722_org mozilla fennec_fdroid](https://user-images.githubusercontent.com/45581170/85237027-73549700-b423-11ea-8981-1d723463dd87.jpg)
Webpage
![Screenshot_20200622_005733_org mozilla fennec_fdroid](https://user-images.githubusercontent.com/45581170/85237034-794a7800-b423-11ea-98be-424f72aa8e9f.jpg)
Highlighted text
![Screenshot_20200622_005743_org mozilla fennec_fdroid](https://user-images.githubusercontent.com/45581170/85237040-810a1c80-b423-11ea-99a0-516e1fa777ca.jpg)
webpage in reader mode
![Screenshot_20200622_005756_org mozilla fennec_fdroid](https://user-images.githubusercontent.com/45581170/85237043-89625780-b423-11ea-8355-ace3cdd28a1f.jpg)
webpage in reader mode with highlighted text

**Desktop (please complete the following information):**
* Config version: don't say latest, say the actual version, found by running `version_comfig` in console:
![Screenshot_20200622_005943_com termoneplus](https://user-images.githubusercontent.com/45581170/85237053-b3b41500-b423-11ea-8756-0c92f1d77886.jpg)
command not found
* Config preset and addon(s):not applicable
* Custom values (if any):not applicable
* DX level:not applicable
* Launch options:not applicable
* Operating system (OS): Android 9.1.0.203 EMUI 9.1.0
* Graphics card (GPU): MALI-T830
* Graphics driver version: GLES 3.2
* Processor (CPU): Hisilicon Kirin 659  arm64-v8a not overclocked
* TF2 on HDD or SSD: not applicable
* Memory (RAM) size in MB or GB: 3.0GB

**Comment by mastercoms** [comment]
Fixed, thanks!
