### ISSUE TITLE
Add source to 3 quotes in faq

### ISSUE THREAD

**Issue by micwoj92** [mastercoms/tf2cfg#337]
**Is your feature request related to a problem? Please describe.**
Currently there are no source links on https://docs.mastercomfig.com/en/latest/faq/
**Describe the solution you'd like**
Add links to source of quotes

**Describe alternatives you've considered**
Add alternative link
**Additional context**
So one can easily read more about subject without wasting time on finding the sources of quotes.

**Comment by mastercoms** [comment]
Links can't be added, as they are in TF2 files (`tf/custom/readme.txt` and `tf/gameinfo.txt`)

**Comment by mastercoms** [comment]
Actually, scratch that, we can use SteamDB game tracking:

https://github.com/SteamDatabase/GameTracking-TF2/blob/master/tf/custom/readme.txt
https://github.com/SteamDatabase/GameTracking-TF2/blob/master/tf/gameinfo.txt
