### ISSUE TITLE
mat_phong 0 not working

### ISSUE THREAD

**Issue by Minib31** [mastercoms/tf2cfg#34]
i have the latest version of the config and when i put mat_phong 0 in the autoexec file it wont work it worked before i got the config but it wont work now please help

*EDIT* my full autoexec file is:

mat_phong 0
hud_combattext_batching 1
hud_combattext_batching_window 2.0
cl_updaterate 66
cl_cmdrate 66
cl_interp .033

**Comment by mastercoms** [comment]
As written in the [installation instructions](https://github.com/mastercoms/mastercomfig#5-customcfg-optional), your `autoexec.cfg` will not be used. Instead, use a `custom.cfg` file.

**Comment by Minib31** [comment]
it still wont work

**Comment by Minib31** [comment]
if you need reference here's my full autoexec file
mat_phong 0
hud_combattext_batching 1
hud_combattext_batching_window 2.0
cl_updaterate 66
cl_cmdrate 66
cl_interp .033

**Comment by angrynerd** [comment]
Rename autoexec.cfg to custom.cfg which should be in /tf/cfg.

**Comment by Minib31** [comment]
already tried that but it still wont work

**Comment by mastercoms** [comment]
Can you share a picture of your `tf/cfg/` folder?

**Comment by Minib31** [comment]
file:///C:/Users/Brandon/Pictures/Screenshots/Screenshot%20(1).png my .cfg folder

**Comment by mastercoms** [comment]
You have to upload the picture to a service like imgur and then link it here.

**Comment by Minib31** [comment]
https://imgur.com/a/AMvcZ like this

**Comment by mastercoms** [comment]
Ok can you also share a screenshot of your custom folder?

Also what exact version of the config do you have? 6.4.2 or the latest beta, 6.5.0-b7?

**Comment by Minib31** [comment]
https://imgur.com/a/dAjLs I have 6.5.0-b7

**Comment by mastercoms** [comment]
Ah, you are using the ZIP installation method so you will have to go into the `mastercomfig_exec/cfg` folder and then open up `autoexec.cfg`. Then, go to the bottom and remove the `//` in front of `exec custom`.

**Comment by Minib31** [comment]
Thanks for all the help it works now

**Comment by Minib31** [comment]
*Closes #34*

**Comment by Minib31** [comment]
fix #34
