### ISSUE TITLE
A question regarding custom config list.

### ISSUE THREAD

**Issue by micwoj92** [mastercoms/tf2cfg#348]
Some custom configs on [the custom configs list](https://docs.mastercomfig.com/en/latest/customization/custom_config_list/) aren't really "mastercomfig custom configs by members of the community". 
I believe that jarconfig and starter config are separate projects that  have mastercomfig compatibility built in and therefore should be moved to the "See Also" section.
rm's config is just an autoexec, same goes for Jack Stanley, which mentions mastercomfig, but maxperformance preset which does not exist anymore.
NegativeOnion's config is basically empty and the demoman.cfg contains `demo` command which is hmmm, questionable?

**Comment by mastercoms** [comment]
Those are fine in my opinion. They're all just examples of things that work out of the box with mastercomfig's config framework, to give ideas about structure and what can generally be put in.

**Comment by micwoj92** [comment]
Even the NegativeOnion? My biggest "fear" is the demo command.

**Comment by mastercoms** [comment]
Yes
