### ISSUE TITLE
dxlevel on linux?

### ISSUE THREAD

**Issue by micwoj92** [mastercoms/tf2cfg#354]
**Is your feature request related to a problem? Please describe.**
On my machine i can choose between 90 and 92.

**Describe the solution you'd like**
Add this info to launch options so its same as macOS.

**Describe alternatives you've considered**
Explain why it isnt included.

**Additional context**
n/a

**Comment by mastercoms** [comment]
-dxlevel is removed on Linux as far as I know. Can you demonstrate how you were able to choose?

**Comment by micwoj92** [comment]
Oh, I used the mat_dxlevel and it only worked with 90 and 92 So I assumed it mirrors the functionality with the -dxlevel launchoption.
