### ISSUE TITLE
disallowhwmorph needs removed from the launch option suggestions in the docs

### ISSUE THREAD

**Issue by backgroundman** [mastercoms/tf2cfg#377]
**Describe the bug**
-disallowhwmorph is still in the "recommended launch options"

**How you encountered the issue**
Tell us the steps on how to recreate the bug.
https://docs.mastercomfig.com/en/stable/customization/launch_options/

**Comment by mastercoms** [comment]
You're visiting the wrong page. This is the official link on every official mastercomfig page, as far as I am aware. https://docs.mastercomfig.com/page/customization/launch_options/

Please let me know if any place links to the stable version of documentation.

**Comment by backgroundman** [comment]
Ah, my bad. Thanks
