### ISSUE TITLE
Possible competitive lag fix launch option

### ISSUE THREAD

**Issue by SeasonalFerret** [mastercoms/tf2cfg#38]
`-force_vendor_id 0x10DE -force_device_id 0x1180`

https://www.reddit.com/r/tf2/comments/52bgsm/psa_i_found_a_potential_fix_for_a_common

Seems to also [increase frame rate in competitive](https://www.reddit.com/r/tf2/comments/8ac0h7/valve_matchmaking_competitive_queuing_seems_fixed/dwxlmes/).

Could be put in [Experimental Launch Options](https://github.com/mastercoms/mastercomfig/wiki/Launch-Options#experimental-launch-options) until you can test it yourself.

**Comment by mastercoms** [comment]
This is wrong because it's forcing a device for dxsupport. FPS increases from this specific ID are only coincidental and will ruin FPS on other systems.

**Comment by SeasonalFerret** [comment]
In that case, is it not possible to add this into Niche Launch Options, with a disclaimer that says "FPS increase or decrease depends on system", just for awareness? I could've used this launch option months ago.

**Comment by mastercoms** [comment]
No, I will not be adding this specific ID to any launch options section. The ID is at best a random one that works for a few people with similar cards, but it's much better to determine which IDs work best for each category of newer cards.

**Comment by SeasonalFerret** [comment]
In that case, could you remove some of the other Niche launch options? Some of them ruin my FPS on a few systems.

**Comment by mastercoms** [comment]
No, because those don't have hundreds of variations. They are single launch options with zero parameters. It doesn't seem beneficial to recommend something so obviously system dependent that it literally specifies a system configuration.

**Comment by sir-bubbles** [comment]
But would this increase FPS if you put in your card's specific IDs?

**Comment by mastercoms** [comment]
Yes, or we could modify dxsupport registrations to add more cards, which I believe would be an even better solution.
