### ISSUE TITLE
Feature request: Add the No Bullet Dust script as an addon

### ISSUE THREAD

**Issue by ghost** [mastercoms/tf2cfg#386]
I have always used the No Bullet Dust script (`surfaceproperties.txt` edit) from [here](https://pastebin.com/64x5E1AT) when I play TF2, since I find the bullet dust to be distracting and hinder performance, especially with shotguns (or x100 servers) on low-end hardware like mine.

I noticed that some mastercomfig addons do contain scripts (like no soundscapes) so I though "why not have this as an addon as well?". I'd like if this script were added as an addon to mastercomfig so that it's easier for other players to find and install. It should be fairly simple to implement, by simply having the file in a VPK.

**Comment by mastercoms** [comment]
The particle module control this: https://docs.mastercomfig.com/en/stable/customization/modules/#particles
