### ISSUE TITLE
[SOLVED] Custom animations don't work with Filesystem cvars

### ISSUE THREAD

**Issue by JackStanley** [mastercoms/tf2cfg#4]
```
// --- Filesystem ---
filesystem_buffer_size 32768 // keep files up to 32KB away in buffer
filesystem_max_stdio_read 32 // read more files
filesystem_native 1 // use native IO, which is faster
filesystem_unbuffered_io 0 // buffer IO, which decreases disk reads, faster
mod_load_anims_async 0 // don't load animations async
mod_load_mesh_async 0 // don't load meshes async
mod_load_vcollide_async 0 // don't load vcollides async
```
Yttrium's competitive viewmodels mod (I suppose every single animations mod) doesn't work in multiplayer game, but works fine in singleplayer (eg local tr_walkway server).

**Comment by mastercoms** [comment]
Are your multiplayer servers running `sv_pure`?

**Comment by JackStanley** [comment]
It doesn't matter because it is preloads every time i run the game (map_background preload_room; wait 20; disconnect), so it works even on valve servers

**Comment by mastercoms** [comment]
Maybe try changing the mod load convars to 1

**Comment by JackStanley** [comment]
Welp, I haven't fully tested yet, but i suppose it's not the filesystem cvars issue. As long as I remember I removed filesystem section and removed config.cfg, but it didn't help me. Going to test it out soon

**Comment by JackStanley** [comment]
Sorry for keeping this opened w/o any reminder about the issue being closed. 

Loading anims async causes custom animations to not load at public servers.
