### ISSUE TITLE
Blocky textures and lightning addon?

### ISSUE THREAD

**Issue by ghost** [mastercoms/tf2cfg#40]
I just came up with an idea of adding "Blocky graphics" addon which apparently makes all textures and lightning blocky. This is super cool to use with low textures and extremely recommended to use with [LOD Tweak](http://etf2l.org/forum/customise/topic-17728/).

```
 alias blocky_on "mat_filthertextures 1; mat_filtherlightmaps 1; mat_filthertextures 0; mat_filtherlightmaps 0"
 alias blocky_off "mat_filthertextures 0 ;mat_filtherlightmaps 0; mat_filthertextures 1; mat_filtherlightmaps 1"   //I guess you put this into comfig.cfg
 
 blocky_on  //and this into blocky.cfg
```

I haven't tested that alias honestly, but as far as I know you need to execute it exactly in that order to work. I actually don't have time to test it now + I use a scoreboard script for this. Otherwise, the script is even simplier than I proposed:

```
 alias blocky_on "mat_filthertextures 0; mat_filtherlightmaps 0"
 alias blocky_off "mat_filthertextures 1; mat_filtherlightmaps 1"   //I guess you put this into comfig.cfg
 
 blocky_on  //and this into blocky.cfg
```

I believe it would be hard to implement it simply as an alias, not an addon.
It has nothing to do with frames (practically), but it may look fabulous actually :)

**Comment by shapetf2** [comment]
minecraft textures are cool

**Comment by mastercoms** [comment]
I don't think this fits as an addon, as it is part of a quality level and is already included in the lighting and texture modules.
