### ISSUE TITLE
Ragdolls linger

### ISSUE THREAD

**Issue by rtsui-harmonicinc** [mastercoms/tf2cfg#42]
Hey dev, I am using compquality preset and I find a problem using it since the update last week(should be 6.5.4.
## Reproducing the issue
1. Kill a player
2. The player sometimes remains in the air/ one the ground where he is killed, note that ragdoll is disabled by default in this preset.

What makes it special is, sometimes the player model is like running when this happen, usually it stays for a few minutes.

## Environment
System:    Host: GlaDOS Kernel: 4.16.1-1-MANJARO x86_64 bits: 64 Desktop: KDE Plasma 5.12.4 
           Distro: Manjaro Linux 17.1.7 Hakoila 
Machine:   Type: Desktop System: ASUS product: All Series v: N/A serial: N/A 
           Mobo: ASUSTeK model: H81M-E v: Rev X.0x serial: N/A UEFI: American Megatrends v: 3601 
           date: 12/15/2017 
CPU:       Dual Core: Intel Celeron G1840 type: MCP speed: 800 MHz min/max: 800/2800 MHz 
Graphics:  Card-1: NVIDIA GP108 [GeForce GT 1030] driver: nvidia v: 390.48 
           Display Server: x11 (X.Org 1.19.6) driver: nvidia unloaded: intel resolution: 1920x1080~60Hz 
           OpenGL: renderer: GeForce GT 1030/PCIe/SSE2 v: 4.6.0 NVIDIA 390.48 
Network:   Card-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet driver: r8169 
Drives:    HDD Total Size: 698.65 GiB used: 210.06 GiB (30.1%) 
Info:      Processes: 216 Uptime: 2h 37m Memory: 7.73 GiB used: 2.61 GiB (33.7%) Shell: bash inxi: 2.9.12

**Comment by mastercoms** [comment]
What mastercomfig version are you on now?

**Comment by ghost** [comment]
The lastest one

**Comment by mastercoms** [comment]
Could you say the version number? It's easier for tracking purposes.

**Comment by rtsui-harmonicinc** [comment]
ok, let me find it, and i am making a clip of this

**Comment by mastercoms** [comment]
You don't need to make a clip, I know what the issue looks like already. But thank you for the offer.

**Comment by ghost** [comment]
6.5.8

**Comment by mastercoms** [comment]
Alright, thanks. This will be fixed in the next bug fix release.
