### ISSUE TITLE
TF2 starts in wrong resolution

### ISSUE THREAD

**Issue by jitterdev** [mastercoms/tf2cfg#420]
**Describe the bug**
TF2 starts in wrong resolution

**How you encountered the issue**
Tell us the steps on how to recreate the bug.
Install mastercomfig (I have medium-high)
Launch tf2

**Screenshots**

**Desktop (please complete the following information):**
* Config version: 9.1.0 November 1st, 2020
* Config preset and addon(s): Medium-high, No tutorial, flat mouse, null movement
* Custom values (if any):
* DX level: 98
* Launch options: -novid -nojoy -nosteamcontroller -nohltv -particles 1 -precachefontchars -full -autoconfig
* Operating system (OS): Windows 10 Pro (Version 2004)
* Graphics card (GPU): Nvidia 1060 3gb
* Graphics driver version: 452.06
* Processor (CPU): i5-8400
* TF2 on HDD or SSD: Installed on HDD, (D drive) Windows and other stuff is SSD (C drive)
* Memory (RAM) size in MB or GB: 16gb

----

Some additional info on the bug
I have already tried putting `mat_setvideomode` in my autoexec, and it gives me `Changing resolutions from (1280, 720) -> (1280, 720)` In console.
I have already tried adding -h and -w with the resolution I want. No dice.

**Comment by micwoj92** [comment]
Why do you have "-autoconfig" in your launch options?

**Comment by JitterDev** [comment]
Sorry for the hassle. I reinstalled the vpk and it's functioning as normal now. If you need more info about it, I can give you some. the +autoconfig thing, was a mistype, meant for that to be +exec autoexec

**Comment by jitterdev** [comment]
@micwoj92 Someone told me to add something to my launch options, and that fixed it, but it didn't before for some reason when I tried it on my own. Sorry for the time waste. The weird thing about this is that I normally don't need -h and -w in my launch options, but when I installed mastercomfig for some reason it didn't use my default resolution. The -autoexec was a typo, meant for that to say +exec autoexec. Sorry about that

**Comment by micwoj92** [comment]
you dont need "exec autoexec" it automatically executes on start.

**Comment by Tiagoquix** [comment]
Remove `-full` and `-autoconfig` from your launch options. Then, launch the game and use the options window to set your resolution. The problem should be fixed.
Also, I recommend you to try [DX Level 100](https://docs.mastercomfig.com/en/latest/customization/launch_options/#dxlevel-launch-options).

**Comment by jitterdev** [comment]
> you dont need "exec autoexec" it automatically executes on start. @micwoj92 

mastercomfig's logo prints twice when i have "+exec autoexec" so I have to name my config autoex and do +exec autoex or else mastercomfig prints to console twice.

**Comment by micwoj92** [comment]
> mastercomfig's logo prints twice when i have "+exec autoexec" 


yes?????


> so I have to name my config autoex and do +exec autoex or else mastercomfig prints to console twice.

or you just read instructions on how to add custom configs without bad workarounds.
