### ISSUE TITLE
Some commands present in the No Tutorial addon

### ISSUE THREAD

**Issue by Tiagoquix** [mastercoms/tf2cfg#439]
https://github.com/mastercomfig/mastercomfig/blob/develop/config/addons/mastercomfig-no-tutorial-addon/cfg/no-tutorial/second.cfg#L2

`cl_mainmenu_updateglow` : What does this command do?

**Comment by Tiagoquix** [comment]
https://github.com/mastercomfig/mastercomfig/blob/develop/config/addons/mastercomfig-no-tutorial-addon/cfg/no-tutorial/second.cfg#L16

`cl_promotional_codes_button_show` : This command is not related to a tutorial message. It should be removed or moved to the main comfig.cfg file instead.

https://wiki.teamfortress.com/w/index.php?title=Main_menu&oldid=1709821#View_Promotional_Codes

**Comment by Tiagoquix** [comment]
https://github.com/mastercomfig/mastercomfig/blob/develop/config/addons/mastercomfig-no-tutorial-addon/cfg/no-tutorial/second.cfg#L29

`tf_weapon_select_demo_time` : What does this command do?

**Comment by Tiagoquix** [comment]
https://github.com/mastercomfig/mastercomfig/blob/develop/config/addons/mastercomfig-no-tutorial-addon/cfg/no-tutorial/second.cfg#L30

`tf_hud_notification_duration` : This command is useful, even if it shows some tutorial messages, it is used on some community servers by plugins to show notifications to players. A good example is Jailbreak. I think it should be removed from the No Tutorial addon.

**Comment by Tiagoquix** [comment]
https://github.com/mastercomfig/mastercomfig/blob/develop/config/addons/mastercomfig-no-tutorial-addon/cfg/no-tutorial/second.cfg#L34

`tf_inspect_hint_count 11` : Why 11?

**Comment by Tiagoquix** [comment]
https://github.com/mastercomfig/mastercomfig/blob/develop/config/addons/mastercomfig-no-tutorial-addon/cfg/no-tutorial/second.cfg#L39

`tf_taunt_always_show_hint` : What does this command do?

**Comment by Tiagoquix** [comment]
https://github.com/mastercomfig/mastercomfig/blob/develop/config/addons/mastercomfig-no-tutorial-addon/cfg/no-tutorial/second.cfg#L45

https://github.com/mastercomfig/mastercomfig/blob/develop/config/addons/mastercomfig-no-tutorial-addon/cfg/no-tutorial/second.cfg#L46

Doesn't `cl_training_class_unlock_all` already set `cl_training_completed_with_classes 511`?

**Comment by Tiagoquix** [comment]
https://github.com/mastercomfig/mastercomfig/blob/develop/config/addons/mastercomfig-no-tutorial-addon/cfg/no-tutorial/second.cfg#L47

`tf_romevision_skip_prompt 1` : I believe this command prevents the game from asking if the player wants to use the RomeVision. I think it should be removed from the No Tutorial addon.

**Comment by Tiagoquix** [comment]
https://github.com/mastercomfig/mastercomfig/blob/develop/config/addons/mastercomfig-no-tutorial-addon/cfg/no-tutorial/second.cfg#L49

`tf_matchmaking_ticket_help` : What does this command do?

**Comment by mastercoms** [comment]
cl_mainmenu_updateglow adds a glow around featured items in the shop slider after an update comes out
promotional codes are probably only something you'd want to view once, and they're barely used in game anymore
this highlights each of your equipped items if you have fast switch off when you spawn
good point, i will give it some thought
11 is what the check requires to not tell you the hint anymore
this disables always showing the hint for high five taunts
the training commands affect different things, unlock all being a file separate from the command
no tutorial should be removing all prompts that veterans have already encountered
it shows you info about mvm tickets before you search for a match
