### ISSUE TITLE
in_usekeyboardsampletime

### ISSUE THREAD

**Issue by Tiagoquix** [mastercoms/tf2cfg#441]
Should not it be set to 0 in all presets and not only in the very low preset?

https://github.com/mastercomfig/mastercomfig/blob/develop/config/cfg/presets/very-low.cfg#L76
https://www.teamfortress.tv/28370/in-usekeyboardsampletime

**Comment by mastercoms** [comment]
It's for keylook. No reason to not have it on the default for a better experience if you use keylook. For everything else, it does nothing.
