### ISSUE TITLE
zoom_sensitivity_ratio

### ISSUE THREAD

**Issue by Tiagoquix** [mastercoms/tf2cfg#443]
Shouldn't the Flat Mouse addon use the value `0.793471413188092` instead of just `0.7934714`?

Reference: https://github.com/JarateKing/jarconfig/blob/master/docs/zoom_sensitivity_ratio.md

**Comment by ghost** [comment]
TF2 only reads floats to a 6-digit precision (which is why `cl_interp` is `0.030303` and not any longer) so any extra length is redundant and makes no difference.

**Comment by Tiagoquix** [comment]
> TF2 only reads floats to a 6-digit precision (which is why `cl_interp` is `0.030303` and not any longer) so any extra length is redundant and makes no difference.

Then the last number 4 should be removed.
