### ISSUE TITLE
Texture preload list

### ISSUE THREAD

**Issue by Tiagoquix** [mastercoms/tf2cfg#444]
Why the comfig doesn't use the default texture preload list file?

These are the differences between the original and the comfig's file:

https://github.com/Tiagoquix/mastercomfig/commit/da3890c29e547653eb8a26792f7f24f7ce392628

Removals mean that the specific lines are only present in the comfig's version of the texture preload list file. Additions mean the [original file](https://github.com/SteamDatabase/GameTracking-TF2/blob/master/tf/tf2_misc_dir/texture_preload_list.txt).

If there are not enough reasons to keep the currently comfig's version of the texture preload list, I suggest its removal, since the original file isn't updated since 2017.

**Comment by mastercoms** [comment]
> since the original file isn't updated since 2017

Why would this be a reason to remove the comfig version?

> Why the comfig doesn't use the default texture preload list file?

It removes things which do not exist in the game, and are likely part of a in-development build. There are also some additions of some missing weapon textures that do exist.
