### ISSUE TITLE
Client precache

### ISSUE THREAD

**Issue by Tiagoquix** [mastercoms/tf2cfg#445]
Comparing the [comfig's version of the client precache file](https://github.com/mastercomfig/mastercomfig/blob/develop/config/mastercomfig/scripts/client_precache.txt) and the [original file](https://github.com/SteamDatabase/GameTracking-TF2/blob/master/tf/tf2_misc_dir/scripts/client_precache.txt), I can understand why Passtime isn't cached.
But I can't understand why sounds aren't cached. Why they aren't?

**Comment by mastercoms** [comment]
because they should already be cached by the entities that play them
