### ISSUE TITLE
Docs - list XanMod kernel under OS Optimizations for Linux

### ISSUE THREAD

**Issue by backgroundman** [mastercoms/tf2cfg#457]
Some might find XanMod useful, or potentially beneficial to those running AMD Zen 3. Or at least the Ryzen 9 5900X:
https://www.phoronix.com/scan.php?page=article&item=xanmod-liquorix-510

Project's website: https://xanmod.org/

**Comment by micwoj92** [comment]
Now we wait.

**Comment by mastercoms** [comment]
#458 merged, closing.

**Comment by micwoj92** [comment]
hmmm, weird that it didnt close automatically

**Comment by mastercoms** [comment]
Should be part of the commit message or title I think.
