### ISSUE TITLE
Add monke

### ISSUE THREAD

**Issue by HurricanePootis** [mastercoms/tf2cfg#462]
**Is your feature request related to a problem? Please describe.**
Mastercomfig is not enticing enough to single-celled TF2 players, who will go on saying its fine to stik with what they're on

**Describe the solution you'd like**
Add monke to the project, so it becomes more enticing.

**Describe alternatives you've considered**
Pay people to use mastercomfig

**Additional context**
ohe oheoh hoeo eeho hoehoeho hoheoho hoeHO Eho OHHEO hoe hoHO HO

**Comment by micwoj92** [comment]
You are taking it too far.

**Comment by HurricanePootis** [comment]
No such thing

**Comment by micwoj92** [comment]
Long distance sharting competition!

**Comment by HurricanePootis** [comment]
:flushed:
