### ISSUE TITLE
Alt-tab generating lag

### ISSUE THREAD

**Issue by DeWolfRobin** [mastercoms/tf2cfg#470]
**Describe the bug**
When the game is in the background, the sound lags and is chopped up. I am assuming that this is for performance reasons but is there a way to turn this of? I have multiple screens and every time I do something on another screen the audio is chopping up.

**How you encountered the issue**
Open the game in borderless fullscreen. alt-tab to another program when there is sound in tf2.

**Screenshots**
N/A

**Desktop:**
* Config version: mastercomfig version : 9.1.0 | November 1, 2020 
* Config preset and addon(s): medium-high preset, flat mouse, no tutorial, null canceling movement, budhud
* Custom values (if any): N/A
* DX level: 98
* Launch options: -novid -noborder -nojoy -nosteamcontroller -softparticlesdefaultoff -reuse -nohltv -freq 144 -threads 8 -high -dxlevel 98 -w 3440 -h 1440 -windowed -particles 1 -NoQueuedPacketThread +cl_clean_textures_on_death 1 +mat_lodin_time 0 +mat_queue_mode 0
* Operating system (OS): Windows 10
* Graphics card (GPU): GTX1080
* Graphics driver version: 461.92 (latest)
* Processor (CPU): Intel(R) core(TM) i7-6700K CPU @ 4.00GHz
* TF2 on HDD or SSD: SSD
* Memory (RAM) size in MB or GB: 16GB

**Comment by micwoj92** [comment]
Please update your mastercomfig and your launch options.

**Comment by DeWolfRobin** [comment]
What can I update about my launch options?

**Comment by micwoj92** [comment]
https://docs.mastercomfig.com/en/latest/customization/launch_options/
https://docs.mastercomfig.com/en/latest/tf2/misconceptions/
read

**Comment by micwoj92** [comment]
noob
