### ISSUE TITLE
player model not showing up in hud after enabling it in config

### ISSUE THREAD

**Issue by KevinRommens** [mastercoms/tf2cfg#488]
**Describe the bug**
i have to manually set the playermodel to be displayed in my hud all the time even if its enabled in the config

**How you encountered the issue**
download any preset with low

**Desktop (please complete the following information):**
version mastercomfig : 9.2.0 | March 20, 2021
Low with no tutorial, no pyroland..
* DX level: no idea
* Launch options: -novid -frequency 144
* Operating system (OS): windows 10
* Graphics card (GPU): 1660 super
* Graphics driver version: dont know
* Processor (CPU): amd ryzen 5 3600x
* TF2 on HDD or SSD: ssd
* Memory (RAM) size in MB or GB: 32gb

**Comment by KaineWooten** [comment]
It could be that you have the command to disable the panel in your autoexec or game_overrides files if you have either or. There is also the chance that modules.cfg could be conflicting as well

**Comment by KevinRommens** [comment]
> It could be that you have the command to disable the panel in your autoexec or game_overrides files if you have either or. There is also the chance that modules.cfg could be conflicting as well

no, all panels are enabled. maybe its my modules.cfg but i highly doubt it

**Comment by KaineWooten** [comment]
> > It could be that you have the command to disable the panel in your autoexec or game_overrides files if you have either or. There is also the chance that modules.cfg could be conflicting as well
> 
> 
> 
> no, all panels are enabled. maybe its my modules.cfg but i highly doubt it

always worth a check

**Comment by KevinRommens** [comment]
> > > It could be that you have the command to disable the panel in your autoexec or game_overrides files if you have either or. There is also the chance that modules.cfg could be conflicting as well
> > 
> > 
> > no, all panels are enabled. maybe its my modules.cfg but i highly doubt it
> 
> always worth a check

no, my modules.cfg doesnt  seem to be interfering

**Comment by Tiagoquix** [comment]
Please post your autoexec.cfg and your modules.cfg here.

**Comment by KevinRommens** [comment]
> Please post your autoexec.cfg and your modules.cfg here.

I dont  have an autoexec.cfg
I deleted my modules.cfg yesterday in the hopes that that would fix it. didnt work.

**Comment by KaineWooten** [comment]
> > Please post your autoexec.cfg and your modules.cfg here.
> 
> I dont have an autoexec.cfg
> I deleted my modules.cfg yesterday in the hopes that that would fix it. didnt work.

What hud are you using? That could also be a factor but also not, minus well check

**Comment by KevinRommens** [comment]
> > > Please post your autoexec.cfg and your modules.cfg here.
> > 
> > 
> > I dont have an autoexec.cfg
> > I deleted my modules.cfg yesterday in the hopes that that would fix it. didnt work.
> 
> What hud are you using? That could also be a factor but also not, minus well check

flawhud

**Comment by Tiagoquix** [comment]
> > Please post your autoexec.cfg and your modules.cfg here.
> 
> I dont have an autoexec.cfg
> I deleted my modules.cfg yesterday in the hopes that that would fix it. didnt work.

Low presets disable the HUD player model by default. Only High and Ultra enable it by default.

Create a modules.cfg in `Team Fortess 2\tf\cfg\user` and type `hud_player_model=on` inside the file and save it. Your problem should be fixed.
