### ISSUE TITLE
Remove the SourceTV Compatibility module

### ISSUE THREAD

**Issue by Tiagoquix** [mastercoms/tf2cfg#490]
The most useless module present in the whole config. Probably one out of 50 thousand people use the `sourcetv=off` setting.

**Comment by treacherousfiend** [comment]
personally i'd say its the opposite, most users don't use sourcetv at all or even know what it is. I don't see an issue with it being in comfig.

**Comment by Tiagoquix** [comment]
> personally i'd say its the opposite, most users don't use sourcetv at all or even know what it is. I don't see an issue with it being in comfig.

I also don't see a issue with being in comfig. However, like you said, "most users don't use sourcetv at all or even know what it is."

`sourcetv=off` isn't even used on any preset by default.

**Comment by treacherousfiend** [comment]
its a good point, but i feel like disabling something that is in the game by default could cause issues with the players that _do_ use it having it not work after installing comfig. Maybe we could disable it as the default in very low?

**Comment by Tiagoquix** [comment]
> its a good point, but i feel like disabling something that is in the game by default could cause issues with the players that _do_ use it having it not work after installing comfig. Maybe we could disable it as the default in very low?

https://docs.mastercomfig.com/en/latest/customization/modules/#sourcetv-compatibility

The default setting is `sourcetv=on` on all presets. You can turn the compatibility off to reduce the latency of changing spectator targets, and I doubt anyone prefers the off setting.

`sourcetv=on` (which is the default) does literally nothing. https://github.com/mastercomfig/mastercomfig/blob/develop/config/mastercomfig/cfg/comfig/comfig.cfg#L63

With this in mind, I conclude that this module is pretty useless.

**Comment by treacherousfiend** [comment]
Ah, I see. Remove it in the same way that the opengl module technically only has one option and the other just clears the alias (https://github.com/mastercomfig/mastercomfig/blob/develop/config/mastercomfig/cfg/comfig/comfig.cfg#L843), I agree with that.

**Comment by Tiagoquix** [comment]
> Ah, I see. Remove it in the same way that the opengl module technically only has one option and the other just clears the alias (https://github.com/mastercomfig/mastercomfig/blob/develop/config/mastercomfig/cfg/comfig/comfig.cfg#L843), I agree with that.

The OpenGL module is pretty useless too. mastercoms created it just for people to avoid the "Unknown command" spam from the developer console.

The SourceTV Compatibility, however, has a real function other than just skipping the commands, but like I said, I doubt anyone prefers the off setting.

**Comment by mastercoms** [comment]
Why do you doubt anyone prefers the off setting? Many people do not use SoutceTV and I have personally seen many uses of this module. I don't know what benefit removing it does. It's not default because of new mastercomfig policy to be as compatible as possible out of the box. This does not mean we remove non-default options with clear benefit. This is a customization config.

**Comment by Tiagoquix** [comment]
> Why do you doubt anyone prefers the off setting? Many people do not use SoutceTV and I have personally seen many uses of this module. I don't know what benefit removing it does. It's not default because of new mastercomfig policy to be as compatible as possible out of the box. This does not mean we remove non-default options with clear benefit. This is a customization config.

Yes, I know this is a customization config and I know that the module isn't enabled by default because of the policy. However, I feel like this module is more an ornament to the config rather than a really useful module.

Probably, most people who know what SourceTV is would see the module in the docs and think: "Nah maybe I will need this someday" so they don't disable it.

People who don't know what SourceTV is wouldn't mess with the module.

**Comment by TheThunderGuyS** [comment]
I use `sourcetv=off`, I exist.

**Comment by Sirbucket** [comment]
SourceTV is actually required on some levels of comp so, having it off or on without knowing what it does is not exactly smart.
