### ISSUE TITLE
Add raw input to the Flat Mouse addon again

### ISSUE THREAD

**Issue by Tiagoquix** [mastercoms/tf2cfg#491]
https://github.com/mastercomfig/mastercomfig/commit/10c278f3a990ce393dce687063463c1bd52628de

The raw input has been present in this module for years. I think most people use it because of the raw input, which as far as I know, also disables some mouse acceleration from Windows.

I don't know for what reasons it could be considered as "suspect", but I can say it is enabled by default in CS:GO and mostly important: it does work, so it should be added back to the Flat Mouse addon.

**Comment by mastercoms** [comment]
Flat Mouse already disables Windows mouse acceleration through other means. Source's usage of the Raw Input API is suspect because it is very naive and does not handle many mouse movement cases properly.

**Comment by Tiagoquix** [comment]
> Flat Mouse already disables Windows mouse acceleration through other means. Source's usage of the Raw Input API is suspect because it is very naive and does not handle many mouse movement cases properly.

Even if it is suspect I think it should be enabled by default. CS:GO enables it by default. And it works.

Removing raw input from the Flat Mouse addon will just cause people to enable it manually. And also, even if it remains removed, it will remain saved on the users' config.cfg.

**Comment by Tiagoquix** [comment]
And also, this is an addon, people aren't forced to use it, so there isn't any real benefit from removing raw input from this addon. And, like I said, "I think most people use it because of the raw input".

**Comment by melvyn2** [comment]
> And also, this is an addon, people aren't forced to use it, so there isn't any real benefit from removing raw input from this addon. And, like I said, "I think most people use it because of the raw input".

Do you have a source for this? The addon is called “flat mouse,” not “raw input” and focuses of the mouse being 1:1 (not low latency which is what I assume raw input is for).

And people won’t install it just to enable that cause it’s in the options menu.

**Comment by mastercoms** [comment]
> And it works.
Like I said, it doesn't handle some mouse input cases correctly. So no, it does not work despite this statement. I am going to close this issue, because it doesn't seem there is a tangible case being made for raw input to stay forced on.
