### ISSUE TITLE
Thread on tf.gg

### ISSUE THREAD

**Issue by JackStanley** [mastercoms/tf2cfg#5]
I would love to see your config on http://www.teamfortress.tv since Comanglia had discontinued their own config.

**Comment by mastercoms** [comment]
I don't think the config is ready quite yet. I still need to investigate and document CVars more before I'm comfortable with sharing with TFTV.

Besides, I'm expecting some sort of engine update in this next major update and I'd like to focus on that before the config gets popular.

**Comment by mastercoms** [comment]
http://www.teamfortress.tv/42867/mastercomfig-fps-customization-config
