### ISSUE TITLE
[Need to investigate] fps_max and loading times

### ISSUE THREAD

**Issue by ghost** [mastercoms/tf2cfg#50]
https://i.imgur.com/zJHuCpQ.png

I've recently watched a video about things affecting loading times in CS:GO. 

fps_max 999 increased map loading times a lot in this game, while fps_max 59 decreased it 3 times. So does it have the same impact in TF2? Sorry, I wish I could find it out by myself.

**Comment by mastercoms** [comment]
Yes.
