### ISSUE TITLE
Localization for the docs.

### ISSUE THREAD

**Issue by micwoj92** [mastercoms/tf2cfg#500]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to help someone but that person does not speak English very well and has trouble understanding docs.

**Describe the solution you'd like**
Enable translation support.

**Describe alternatives you've considered**
none

**Additional context**
https://www.mkdocs.org/about/release-notes/#version-12-2021-06-04
Mkdocs only supports theme localization. For now only Spanish and French are supported by it, but I think it is a good start.

"Translations only apply to text contained within a theme's template, such as "next" and "previous" links. The Markdown content of a page is not translated. If you wish to create multilingual documentation, you need to combine theme localization with a third-party internationalization/localization plugin."

**Comment by treacherousfiend** [comment]
i wonder if we could have the sidebar go to different links based on the translation, that might workaround the fact that markdown isn't transtlated

**Comment by mastercoms** [comment]
This needs to be done by publishing docs to github.io using [mike](https://github.com/jimporter/mike) instead of using Read the Docs.

**Comment by micwoj92** [comment]
> This needs to be done by publishing docs to github.io using [mike](https://github.com/jimporter/mike) instead of using Read the Docs.

Read the Docs doesn't support it? For example in url page there is /en/ which indicates that it should be possible to use other languages?

**Comment by mastercoms** [comment]
Only for Sphinx

**Comment by mastercoms** [comment]
Fixed in 214ae6a8e7d97bc935d367b79ffe1db9c97196f6 and beyond!

**Comment by micwoj92** [comment]
Thank you for removing Polish support, I will never forget that.

**Comment by mastercoms** [comment]
Unfortunately, in mkdocs strict mode builds, we cannot include Polish since it is not supported in the search plugin: https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#built-in-search

> Language 'pl' is not supported by lunr.js, not setting it in the 'plugins.search.lang' option

https://github.com/mastercomfig/mastercomfig/runs/2919738772?check_suite_focus=true#step:6:8

**Comment by micwoj92** [comment]
oh

**Comment by mastercoms** [comment]
Since you said "For now only Spanish and French are supported by it, but I think it is a good start." I hope you are ok with this.

**Comment by mastercoms** [comment]
Contribute here: https://github.com/MihaiValentin/lunr-languages/blob/master/CONTRIBUTING.md

**Comment by micwoj92** [comment]
> Since you said "For now only Spanish and French are supported by it, but I think it is a good start." I hope you are ok with this.

Yes, but I saw that you used mike now so I thought that more languages will be supported. I didn't have much time to read the details which I should have done prior to commenting.
