### ISSUE TITLE
config not working in comp mode

### ISSUE THREAD

**Issue by chrisjiang1** [mastercoms/tf2cfg#504]
I tried using "mm_override" but the config does not use the "low" preset I specified and is stuck on high settings in competitive mode. The config works normally in community servers

**Comment by micwoj92** [comment]
mm_override is to prevent from crashing. The way you are supposed to use it is to execute it before joining competitive mode if your game crashes without doing it.

**Comment by Tiagoquix** [comment]
https://docs.mastercomfig.com/en/latest/next_steps/troubleshoot/#tf2-crashes-when-entering-a-competitive-mode-match

> Additionally, Competitive Mode locks a bunch of settings that are normally only accessible via the console.
Run `mm_override` in the console on the main menu before joining a Competitive Mode match to make the config compatible.
You will have to restart the game to unlock the hidden settings and revert the config back to normal.
