### ISSUE TITLE
mastercomfig is no longer config but a framework.

### ISSUE THREAD

**Issue by micwoj92** [mastercoms/tf2cfg#514]
**Describe the bug**
According to one of recent commits on the main site https://github.com/mastercomfig/mastercomfig.github.io/commit/7ad0bffe6fc87c3117030fed08e0d477bf395080#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051 mastercomfig is no longer "A modern Team Fortress 2 performance and customization config" but  "a modern customization framework".

**How you encountered the issue**
I visited the homepage and then clicked on docs to read them. I noticed that the text was not consistent. At first I wanted to open pull request to fix this issue, but there are many instances where the word "config" is used and it is not 100% clear for when to leave it as config or change to framework. Also the repo description on GitHub is not possible to be changed using pull requests.

**Screenshots**
Main page as of today (2021-06-16)
![image](https://user-images.githubusercontent.com/45581170/122211947-93d4f700-cea7-11eb-8630-0eb6f3e0b75e.png)

Main page as of 2021-05-27 (Latest webarchive snapshot at the time of writing issue)
![image](https://user-images.githubusercontent.com/45581170/122214279-33938480-ceaa-11eb-929a-1267140feb0c.png)

Docs index
![image](https://user-images.githubusercontent.com/45581170/122212261-eca48f80-cea7-11eb-87c5-a556066a61d1.png)

Search on docs.mastercomfig.com
![image](https://user-images.githubusercontent.com/45581170/122214071-f3cc9d00-cea9-11eb-9db6-00cbe3aa7a24.png)

**Desktop:**
* Config version: 9.5.2 but the issue started with 9.4.0.
* Config preset and addon(s): Low preset, No soundscapes addon, no pyroland
* Custom values (if any): +duck is bound to shift, lighting medium and lighting_ex high
* DX level: n/a (Linux :sob:)
* Launch options: -novid -nojoy -nosteamcontroller -nohltv -particles 1 -precachefontchars -gl_enablesamplerobjects 
* Operating system (OS): Arch Linux 5.10.43-1-lts  x86_64 GNU/Linux
* Graphics card (GPU): AMD Radeon™ RX 560
* Graphics driver version: mesa 21.1.2
* Processor (CPU): AMD Athlon X4 845
* TF2 on HDD or SSD: HDD
* Memory (RAM) size in MB or GB: 8GB

**Comment by mastercoms** [comment]
A subset of the framework is a config, so some instances of the word config are fine. I'll update the usages where appropriate, thank you for bringing this to my attention!
