### ISSUE TITLE
Readd micwoj92 to the Discord

### ISSUE THREAD

**Issue by mastercoms** [mastercoms/tf2cfg#516]
**Describe the bug**
I'm always frustrated when I think about micwoj92 and his antics, and how they are sorely missing from the [mastercomfig Discord server](https://discord.gg/CuPb2zV).

**How you encountered the issue**
I wanted to ping @micwoj92 with a meme but found that he was not in the members list. Then we all cried.

**Describe alternatives you've considered**
micwoj92 could explain why he left the Discord to give us closure if he does not want to come back.

**Screenshots**

![micwoj92 left the server](https://user-images.githubusercontent.com/2672245/122287633-27fe8880-cebf-11eb-8ecb-6f3ad3daab04.png)

![micwoj92 funny](https://user-images.githubusercontent.com/2672245/122287931-80358a80-cebf-11eb-864e-0d0202bfe672.png)

![micwoj92 last message](https://user-images.githubusercontent.com/2672245/122288007-96dbe180-cebf-11eb-80ad-c99d07a7d835.png)

**Desktop:**
* Config version: 9.5.2
* Config preset and addon(s): ultra preset
* Custom values (if any): None
* DX level: 100
* Launch options: -novid -nojoy -nosteamcontroller -nohltv -particles 1 -precachefontchars
* Operating system (OS): Windows 10 21H1
* Graphics card (GPU): GTX 1080
* Graphics driver version: 462.59 Studio
* Processor (CPU): Intel i7-8700K
* TF2 on HDD or SSD: SSD
* Memory (RAM) size in MB or GB: 64GB

**Comment by micwoj92** [comment]
> and how they are sorely missing

I'm always frustrated with mis-pronoun-ciation.

> **Describe alternatives you've considered**
> micwoj92 could explain why he left the Discord to give us closure if he does not want to come back.

I will be back on 12th September.

**Comment by mastercoms** [comment]
I intended for 'they' to refer to the plural group of you and your antics. I'm sorry that it seemed like a misusage of your pronouns.

Thank you for the update, we eagerly await your return.

**Comment by micwoj92** [comment]
If you miss me: I can't help.
If you miss my antics:  [here's a short video](https://www.youtube.com/watch?v=TRR8LxA1HYE) which can help you.

**Comment by melvyn2** [comment]
Note that TF CAT’s nitro will be active until ~September 12 and not July 12 as it was claimed from the 3 month EGS Nitro promotion. @micwoj92

**Comment by wgetJane** [comment]
poll: disable external emojis
