### ISSUE TITLE
macOS crash on server join

### ISSUE THREAD

**Issue by irefl** [mastercoms/tf2cfg#54]
3. Include the following information in your report:
    * How you encountered the issue
Playing on casual or community (mge), about once every two or three times i'd join a server or the map would switch my game would hang and crash. Removing the custom vpks and switching back to my old config (b4nny) solved the problem.

    * Config version (don't say latest, say the actual version, found in the
      startup console output)

    * Config preset and addon(s)
Competitive (now medium after update, present with both)
badgpu (present with and without)

    * Custom values (if any)
none

    * DX level
92
    * Launch options
-novid -nojoy -nosteamcontroller -noff -softparticlesdefaultoff -reuse

    * Operating system (OS)
OSX Yosemite 10.10.3

    * Graphics card (GPU)
Intel HD 5000

    * Processor (CPU)
i5-4260U

    * HDD or SSD
500gb HDD

    * RAM size in MB or GB
8gb ddr3 1600

**Comment by mastercoms** [comment]
Would you happen to know your config version?

**Comment by irefl** [comment]
sorry forgot to include that,
comp (original): 6.5.8
medium (troubleshoot): 6.7.0

**Comment by mastercoms** [comment]
Could you try the 7.0.0a2 pre-release?

https://github.com/mastercoms/mastercomfig/releases/tag/v7.0.0a2

**Comment by irefl** [comment]
Okay, I'll get back to you with that

**Comment by mastercoms** [comment]
@ireperson Any updates?

**Comment by irefl** [comment]
lol sorry, never finished responding to this, have had this open in a tab and not send for a couple of days.
using the vpk in the a2 release seems to have fixed it!
