### ISSUE TITLE
Add redneck localization

### ISSUE THREAD

**Issue by micwoj92** [mastercoms/tf2cfg#547]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when going to mastercomfig documentation page, redneck localization could help brighten my day.

**Describe the solution you'd like**
Add redneck, same as Redhat had back in the day

**Describe alternatives you've considered**
none

**Additional context**
![image](https://user-images.githubusercontent.com/45581170/124404238-635fda80-dd3a-11eb-97b3-c4bc9e811f26.png)
https://imgur.com/gallery/yX5uw

**Comment by Sirbucket** [comment]
Ahh good ol RHEL.

**Comment by mastercoms** [comment]
I don't think there's much capability to add this dialect, nor do I think it provides anything meaningful.

**Comment by micwoj92** [comment]
> nor do I think it provides anything meaningful.

Easter egg better than "hehe amogas"

**Comment by mastercoms** [comment]
Maybe for April Fools then?
