### ISSUE TITLE
Bug/glitch

### ISSUE THREAD

**Issue by ThatFunkiChick** [mastercoms/tf2cfg#55]
Well, I installed it and was not satisfied I went back to my original configuration but when I went back to my old config, the floating health tf2 was not working and this is a problem because I play Medic and I need to see the life of my partners team
And I also can not see who is healing me and the life of the healer
And this is super annoying

I'm Brazilian, I used the google translator. Sorry and I hope you guys will help me.

**Comment by mastercoms** [comment]
I would recommend [cleaning your config](https://github.com/mastercoms/mastercomfig/blob/release/docs/README.md#clean-up) to prevent any conflicts.

But, for this specific issue, this was set by the very low preset. You can revert it with the following:

```c
tf_hud_target_id_disable_floating_health 0
tf_hud_target_id_offset 0
tf_healthicon_height_offset 10
```

And if you don't mind, what did you not like about mastercomfig? I would love to improve it.

**Comment by ThatFunkiChick** [comment]
Thank you! I'm sorry it looked like I did not like the config and I was a bit desperate! The config is perfect greatly increased my fps but I liked, visually, my old config :+1:
