### ISSUE TITLE
'Console' is separated into two sections in comfig.cfg

### ISSUE THREAD

**Issue by NekoAlosama** [mastercoms/tf2cfg#553]
**Describe the bug**
In [comfig.cfg](https://github.com/mastercomfig/mastercomfig/blob/develop/config/mastercomfig/cfg/comfig/comfig.cfg), the '-- Console --' block is placed into two sections, around lines 1156 and 1252. They both contain `//con_enable 1`, but the former has the aliases for the console flip. These sections should be collapsed into one.

**How you encountered the issue**
Go into [comfig.cfg](https://github.com/mastercomfig/mastercomfig/blob/develop/config/mastercomfig/cfg/comfig/comfig.cfg) and Ctrl+F for `'-- Console --'`. There should be two sections inside.

**Screenshots**
![Screenshot_172](https://user-images.githubusercontent.com/47763383/124821161-5d394c00-df3c-11eb-8a23-1e844f01abf8.png)
![Screenshot_173](https://user-images.githubusercontent.com/47763383/124821164-5f030f80-df3c-11eb-8460-3d27cf61eb62.png)

**Desktop (please complete the following information):**
* mastercomfig version: 9.5.2, transitioning to 9.6.0
Others are irrelevant

**Comment by Tiagoquix** [comment]
Fixed in #543
