### ISSUE TITLE
Nav-mesh areas with certain attributes make graphical artifacts.

### ISSUE THREAD

**Issue by WhyIsEvery4thYearAlwaysBad** [mastercoms/tf2cfg#554]
**Describe the bug**
Some navigation mesh attributes make rainbow-colored artifacts. I have only seen this bug happen with `TF_NAV_RED_SPAWN_ROOM` and `TF_NAV_BLUE_SPAWN_ROOM`, but I haven't fully narrowed down the attributes yet. I'm uncertain if `nav_edit` affects this bug in any way, but I know `tf_show_mesh_decoration` does.

This bug does not happen with none-preset or stock/clean TF2, but I have only tested with low preset. I have however verified that this bug works in any TF2 map.

**How you encountered the issue**
1. Launch TF2.
2. Launch a map.
3. Add a bot
4. Do `tf_show_mesh_decoration 1`. (Do *not* use `tf_show_mesh_decoration_manual`.)

**Screenshots**
With low-preset:
![Graphical glitches all over the screen.](https://user-images.githubusercontent.com/67948198/124854233-98686900-df96-11eb-9fa4-bf53e80dcebe.png)
![Graphical glitches all over the screen.](https://user-images.githubusercontent.com/67948198/124854237-9900ff80-df96-11eb-84ef-4f9793bb4b7a.png)

With none-preset:
![No graphical glitches.](https://user-images.githubusercontent.com/67948198/124854238-99999600-df96-11eb-8ee6-68c661ad338b.png)

With stock/clean TF2:
![No graphical glitches.](https://user-images.githubusercontent.com/67948198/124854240-99999600-df96-11eb-8e6e-af45afd423dd.png)
![No graphical glitches.](https://user-images.githubusercontent.com/67948198/124854243-9acac300-df96-11eb-9ff3-8f3ac9d36625.png)

**Desktop (please complete the following information):**
* mastercomfig version: `9.5.2 (Latest dev branch)`
* Preset and addon(s): `low-preset, disable-pyroland, no-soundscapes, no-tutorial, and null-canceling-movement`.
* Custom values (if any):
* DX level: `90`
* Launch options: `MANGOHUD_CONFIG="fps_limit=60,no_display" mangohud %command% -novid -nojoy -nosteamcontroller -nohltv -particles 1 -precachefontchars` (I tried testing without launch options, but it crashes my game for some reason.)
* Operating system (OS): `Linux Mint 20.1 Ulyssa (MATE) x86-64 (Kernel Linux 5.4.0-77-generic)` 
* Graphics card (GPU): `Intel UHD Graphics (x64) @ 33Mhz`
* Graphics driver version: Unknown.
* Processor (CPU): `Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (64 bits)`
* TF2 on HDD or SSD: `SSD`
* Memory (RAM) size in MB or GB: `8GiB`

**Comment by Tiagoquix** [comment]
Can you please test this bug with the Ultra preset so we can see if the problem is a graphical command?

**Comment by micwoj92** [comment]
I think the problem is your GPU running at only 33Mhz.

**Comment by WhyIsEvery4thYearAlwaysBad** [comment]
> Can you please test this bug with the Ultra preset so we can see if the problem is a graphical command?

TF2 is crashing on me at the moment when I try to launch it for some reason, but when I can get it working again, I will test this bug with the Ultra preset.

EDIT: Actually looking at it further, it's seems like the low and ultra presets crash the game for me.

**Comment by Tiagoquix** [comment]
Try this:

https://docs.mastercomfig.com/9.5.2/setup/clean_up/

**Comment by WhyIsEvery4thYearAlwaysBad** [comment]
Turns out this craptop can't handle the Ultra or High presets, as I've managed to launch TF2 just fine with medium-high, so that preset is the max I can handle. This bug does seem to also occur on medium-high (with no custom modules.cfg) though:

![Rainbow-colored artifacts all over the screen.](https://user-images.githubusercontent.com/67948198/125146085-b7d8d080-e113-11eb-9940-271a8d76bc3e.png)
![More rainbow-colored artifacts all over the screen.](https://user-images.githubusercontent.com/67948198/125146088-b8716700-e113-11eb-8402-a82b14fa9935.png)

Also it turns out that my main caption data file is what keeps crashing the game. I need that thing to use most of my binds though, so I'm stuck on what else to do.

**Comment by mastercoms** [comment]
Try mat_bufferprimitives 0

**Comment by WhyIsEvery4thYearAlwaysBad** [comment]
Yeah that seems to have fixed the issue.

**Comment by mastercoms** [comment]
Fixed in https://github.com/mastercomfig/mastercomfig/commit/f2f6eec7e4d41a830a1b477d3ebdc5c59893a293.
