### ISSUE TITLE
Random Glitches On My Screen

### ISSUE THREAD

**Issue by wweony23** [mastercoms/tf2cfg#557]
**Describe the bug**

**How you encountered the issue**
Tell us the steps on how to recreate the bug.

**Screenshots**
![image](https://user-images.githubusercontent.com/72761693/125525403-3d3adb3d-e82b-4c27-b59c-73dd883a3b23.png)
![image](https://user-images.githubusercontent.com/72761693/125525516-ac42ebb3-e1df-415d-92ff-cf91c926ca7e.png)

Video Attachment
https://youtu.be/QxVBFfHQKHA
https://youtu.be/2jO7bQ5-JUE
P.S. Sometimes they are even stronger and longer, that's what I caught on video.

**Desktop (please complete the following information):**
* mastercomfig version:
Build Label:           6623512   # Uniquely identifies each build

* Preset and addon(s): Ultra preset || Null Movement || Disable Pyroland || No tutorial

* Custom values (if any): any
* DX level: cannot find way to check it
* Launch options: -heapsize 3145728 
* Operating system (OS): Ubuntu 20.04
* Graphics card (GPU): GeForce RTX 2070 SUPER
* Graphics driver version:  a1
* Processor (CPU):  AMD Ryzen7
* TF2 on HDD or SSD: SSD
* Memory (RAM) size in MB or GB: default (don't know how to check it)

**Comment by micwoj92** [comment]
Your  problem is using launch option that doesnt work

**Comment by AethWolf** [comment]
Does it glitch out in any other game? Looks kind of like a dying GPU to me.

**Comment by mastercoms** [comment]
I don't recognize `6623512`. What is this supposed to be? Can you try the latest dev build?

**Comment by mastercoms** [comment]
I am very sure that this is fixed in the latest dev build, as of https://github.com/mastercomfig/mastercomfig/commit/f2f6eec7e4d41a830a1b477d3ebdc5c59893a293.

**Comment by wweony23** [comment]
> I don't recognize `6623512`. What is this supposed to be? Can you try the latest dev build?

9.5.2

**Comment by wweony23** [comment]
> Does it glitch out in any other game? Looks kind of like a dying GPU to me.

No, it only happens here and only after mastercomfig download.
