### ISSUE TITLE
Multiple "unknown command"'s on startup.

### ISSUE THREAD

**Issue by SeasonalFerret** [mastercoms/tf2cfg#56]
>mastercomfig 6.8.0b5

Encountered in console upon startup of the game. Error indicates that commands were invoked during game launch that do not exist. Console log is provided below, and I have linked to each instance of the unknown command in this git.

Unknown command "gl_pow2_tempmem" > [1](https://github.com/mastercoms/mastercomfig/blob/70673136e26b7782c8951a992b0c0f81a91af872/config/mastercomfig/cfg/comfig.cfg#L1100)
Unknown command "gl_mtglflush_at_tof" > [1](https://github.com/mastercoms/mastercomfig/blob/70673136e26b7782c8951a992b0c0f81a91af872/config/mastercomfig/cfg/comfig.cfg#L1110), [2](https://github.com/mastercoms/mastercomfig/blob/9eda7beb7b8bc0db25d18ddfa23563db2c22572a/config/cfg/presets/very-low.cfg#L52)
Unknown command "gl_debug_output" > [1](https://github.com/mastercoms/mastercomfig/blob/70673136e26b7782c8951a992b0c0f81a91af872/config/mastercomfig/cfg/comfig.cfg#L1111)
Unknown command "gl_magnify_resolve_mode" > [1](https://github.com/mastercoms/mastercomfig/blob/70673136e26b7782c8951a992b0c0f81a91af872/config/mastercomfig/cfg/comfig.cfg#L1112)
Unknown command "gl_paircache_rows_lg2" > [1](https://github.com/mastercoms/mastercomfig/blob/70673136e26b7782c8951a992b0c0f81a91af872/config/mastercomfig/cfg/comfig.cfg#L1113)
Unknown command "gl_paircache_ways_lg2" > [1](https://github.com/mastercoms/mastercomfig/blob/70673136e26b7782c8951a992b0c0f81a91af872/config/mastercomfig/cfg/comfig.cfg#L1114)

I am unsure if I am the only one having this "issue", so information of my installation can be found below.
<details>
  <summary>TF2 Information (Click to expand)</summary>
Launch options: 

```
-dxlevel 95 -novid -nojoy -nosteamcontroller -softparticlesdefaultoff -reuse -console -r_emulate_gl -nohltv -limitvsconst -windowed -noborder -w 1360 -h 768
```

Modules:
```models_low
world_high
shaders_ultra
textures_ultra
shadows_low
effects_high
water_very_low
post_processing_low
pyrovision_low
motion_blur_off
antialiasing_off
texture_filter_aniso_8x
characters_ultra
decals_ultra
sprays_on
gibs_ultra
ragdolls_on
outlines_ultra
sound_high
```
Unrelated: I understand that "outlines_ultra" and "ragdolls_on" are invalid as of 6.8.0b.
</details>

<details>
  <summary>System information</summary>
Windows 10 Pro 1803, 8GB Ram

CPU: Intel Core i5-4460 @ 3.20GHz

GPU: AMD Radeon R7 240

OS and programs installed on SSD, Steam Games Library found on seperate HDD.
</details>

**Comment by mastercoms** [comment]
These messages are harmless, the cvars are for OpenGL users.

**Comment by SeasonalFerret** [comment]
Have you ever wrote something and re-read it just to make sure everything is correct, then the moment you post it you realize you've made a mistake?

Just realized these are commands for linux users.
