### ISSUE TITLE
Viewmodel is invisable

### ISSUE THREAD

**Issue by Determinationvoid** [mastercoms/tf2cfg#57]
my viewmodel is not showing up
everytime i launch the game and started playing 
my weapon on my screen does not show up
no one knows this problem i check your
troble shoting no fixes there is working 
and the only vpk i had was the very low preset
and thats it so i tried to install the madiem preset and the high
and ultra preset the madiem one did not work the high preset
also did not work there i tried the ultra preset it work there and i tried the low preset
did not work there also please help me i cannot play tf2 all the old configs are dead

feature that should be included
when downloading you can
chose to have your viewmodel on or off

launch option
there was nothing in my launch option i find doing anything ti my launch option well result in some sort of bad issue

my computer
intelcore i5
gtx m670
windows 8.1
ram 4 gigs

**Comment by mastercoms** [comment]
Add `r_drawviewmodel 1` to your `custom.cfg`.

**Comment by Determinationvoid** [comment]
it does not work

**Comment by Determinationvoid** [comment]
wait wait it works

**Comment by Determinationvoid** [comment]
nope it does not work it work for the frist start but then stoped again

**Comment by Aerden** [comment]
Are you sure that nothing else is setting r_drawviewmodel to 0? Did you even put it in your custom.cfg

**Comment by Determinationvoid** [comment]
i did

**Comment by Determinationvoid** [comment]
why the fuck would i put a setting to always make it r_drawviewmodel 0 im new plus i hate not seing my gun and i dont find it better to aim withour my viewmodel

**Comment by Determinationvoid** [comment]
this is what i did to my custom.cfg


mat_phong 0
bind w +mfwd
bind s +mback
bind a +mleft
bind d +mright

alias +mfwd "-back;+forward;alias checkfwd +forward"
alias +mback "-forward;+back;alias checkback +back"
alias +mleft "-moveright;+moveleft;alias checkleft +moveleft"
alias +mright "-moveleft;+moveright;alias checkright +moveright"
alias -mfwd "-forward;checkback;alias checkfwd none"
alias -mback "-back;checkfwd;alias checkback none"
alias -mleft "-moveleft;checkright;alias checkleft none"
alias -mright "-moveright;checkleft;alias checkright none"
alias checkfwd none
alias checkback none
alias checkleft none
alias checkright none
alias none

r_drawviewmodel 1

**Comment by Aerden** [comment]
Any mods?

**Comment by Determinationvoid** [comment]
i have hypnotize hud with no smoke script inside hitsound and all the master config and nohatsmod.vpk

**Comment by Determinationvoid** [comment]
and if you are going to ask me to remove them just no i tried that befor even uninstalling the game clearing my reposetory its the same even without the custom.cfg

**Comment by mastercoms** [comment]
I'm looking into what causes this, and will fix it in a later 7.0.0 release.

**Comment by mastercoms** [comment]
I forgot that very low also sets the FOV to 0.1 to hide any tracers.

```c
r_drawviewmodel 1
viewmodel_fov 54
```
