### ISSUE TITLE
Domination Sound & Miss Pauling Messages Sound Removal - Addon Request

### ISSUE THREAD

**Issue by differentiaI** [mastercoms/tf2cfg#581]
**Is your feature request related to a problem? Please describe.**
Several users now turn to play community servers due to the casual servers being populated by bots and cheaters. As a result most of these community server hosters have sv_cheats 1 enabled. I noticed that when you get dominated the sound produced by the game is extremely annoying as well as the alerts made by Miss Pauling when you respawn since most of these are server side. Disabling these alerts clientside is possible by using empty audio files in their place.

**Describe the solution you'd like**
Solution proposed involved using empty sound or audio files that replaces the original sound files. I would like to see if these files are added to the Addons section of the mastercomfig site so users can download them with ease. The Domination Removal mod removes the "NEW NEMESIS!" text in the killcam whenever a player dominates you, it further removes the revenge icon on the leaderboards.

Both the files are attached.
Both these folder and the file goes under the tf/customs.

**Describe alternatives you've considered**
I believe the domination removal folder can be converted to a .VPK folder but so far this solution has helped me and I have used them for 2+ years without any issues.

**Additional context**
The first file was made by the community and is licensed under Creative Commons whereas the second one is just empty sound file. 
https://gamebanana.com/mods/36617
[Domination Removal.zip](https://github.com/mastercomfig/mastercomfig/files/7145254/Domination.Removal.zip)
[Miss Pauling Messages.zip](https://github.com/mastercomfig/mastercomfig/files/7145273/Miss.Pauling.Messages.zip)

**Comment by micwoj92** [comment]
Hello John Fitzgerald Kennedy

**Comment by mastercoms** [comment]
I think this is out of scope for mastercomfig, but I'm not sure. It can help with quality of life.

**Comment by differentiaI** [comment]
I agree with you. However I believe you can create a separate section called Third party Add-Ons for these files.

**Comment by differentiaI** [comment]
> Hello John Fitzgerald Kennedy

Hello loyal citizen.

**Comment by micwoj92** [comment]
> I agree with you. However I believe you can create a separate section called Third party Add-Ons for these files.

You mean just like https://docs.mastercomfig.com/9.5.2/customization/see_also/ ?

**Comment by differentiaI** [comment]
> You mean just like https://docs.mastercomfig.com/9.5.2/customization/see_also/ ?

I did, but unlike the customizations webpage these are sound mods equivalent to "No Soundscapes" and "No Footsteps" in the Official Addons page since at that point we are just objectively removing annoying game sounds.

**Comment by Tiagoquix** [comment]
While I think this is a good idea, I also see that this is out of the scope for mastercomfig. It is very specific.

So, for now, your addon will be rejected. Thanks for the suggestion.

**Comment by Tiagoquix** [comment]
To clarify what I mean: your suggestion is something very specific and personal. For example, we wouldn't put an addon of a HHH's skin, because that depends on each player's personal preference.

The idea of ​​your addon here is the same: the removal of Miss Pauling's lines and the domination sound is a personal preference that varies from player to player.

Personally, I have never seen anyone complaining about these sounds.

Anyway, thanks again for the suggestion. You are free to suggest new things at any time.

**Comment by differentiaI** [comment]
> To clarify what I mean: your suggestion is something very specific and personal. For example, we wouldn't put an addon of a HHH's skin, because that depends on each player's personal preference.
> 
> The idea of ​​your addon here is the same: the removal of Miss Pauling's lines and the domination sound is a personal preference that varies from player to player.
> 
> Personally, I have never seen anyone complaining about these sounds.
> 
> Anyway, thanks again for the suggestion. You are free to suggest new things at any time.

I understand and its fine, but I believe you could add these to the extra mods section. Just a personal opinion. The Miss Pauling lines are active on community servers but won't work on them if you exclusively just play 2Fort or Hightower. But I understand its beyond the scope. Also I don't know a single person who actually likes the domination sound but then again you're right. The experience is anecdotal.

Cheers.

**Comment by Tiagoquix** [comment]
About adding it to the extra mods section: no problem, this has been done here: https://github.com/mastercomfig/mastercomfig/commit/20fa49fed82f1c58e1a8d9523623c8ddf29e89f4.

The Miss Pauling Messages mod isn't published anywhere, it's just a direct download link. If you upload it to GameBanana, I can also add it.

Thank you for your interest in not giving up on the addon.

**Comment by differentiaI** [comment]
Since you asked so nicely I have added Miss Pauling's Message mod into gamebanana myself. Please consider adding it. Thank you.

https://gamebanana.com/mods/325900

**Comment by Tiagoquix** [comment]
[Done](https://github.com/mastercomfig/mastercomfig/commit/10ca5d7995fe2717576f688df90b9d9af23d8281). Thanks!
