### ISSUE TITLE
[Linux beta-7.0.0 a10] Now requires root?

### ISSUE THREAD

**Issue by T-oasterO-ven** [mastercoms/tf2cfg#59]
Version: [Beta-Release] 7.0.0 a10

Updated from [Beta-Release] 7.0.0 a7

Now the program requires root to run:
```
bash: /usr/local/bin/mastercomfig-app: Permission denied
sudo mastercomfig-app
```

Is this an intended Linux change?
Also the config files are now locked in the tf2 folder and I run tf2 as a non-root user.

**Comment by mastercoms** [comment]
The app doesn't require root to run, the file permissions are just wrong in the package. Just `sudo chmod -R 755 /opt/mastercomfig /usr/share/applications/mastercomfig-app.desktop` to fix it.

**Comment by T-oasterO-ven** [comment]
Yep, that worked! Thanks.
