### ISSUE TITLE
Use very advanced, cutting-edge git/GitHub features which allow one to edit multiple files at once.

### ISSUE THREAD

**Issue by micwoj92** [mastercoms/tf2cfg#596]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when my RSS reader gets spammed with 200 notifications in 5 minutes. 
https://github.com/mastercomfig/mastercomfig/commits/develop.atom

**Describe the solution you'd like**
Teach one of mastercomfig developers/contributors how to use advanced features. That will lead to increased productivity and decreased annoyance of all people (sample size=1).

**Describe alternatives you've considered**
Remove push access so the person has to go back to using Pull requests feature.

**Additional context**
There are multiple ways to edit multiple files in one commit.The most simple one (which requires no additional software) is simply editing files in your favourite text editor and then [uploading multiple ones to GitHub via webbrowser](https://github.com/mastercomfig/mastercomfig/upload/develop). The drawback is that you can't delete multiple files this way. Second option is to use the [radical GitHub feature called Pull requests](https://github.com/mastercomfig/mastercomfig/pulls). Third option is using [official GitHub desktop client](https://desktop.github.com/). Fourth option is using [any thirdparty git compatible program which has graphical user interface](https://git-scm.com/downloads/guis). And my final, fifth option is just simply using [the git](https://git-scm.com/).

**Comment by ghost** [comment]
Important issue, needs to be resolved quickly.
Also consider amending commits when changes are small, writing helpful commit messages describing the type of change, grouping only relevant changes into one commit/pull request, and squash merging pull requests that have too many commits.
