### ISSUE TITLE
Black artifacts

### ISSUE THREAD

**Issue by StellaSmith** [mastercoms/tf2cfg#609]
In the [next step page about the black artifacts in linux](https://docs.mastercomfig.com/page/next_steps/quick_fixes/#black-artifacts-all-over-the-screen-on-linux) has the wrong commands, at least for me. The commands i use to fix this are
```
mat_bumpmap 1
mat_phong 1
```

**Comment by mastercoms** [comment]
lighting_ex=high as recommended in that sets mat_phong 1.

**Comment by StellaSmith** [comment]
but then `mat_specular 1` is unnecessary right?

**Comment by mastercoms** [comment]
This is a general solution on the documentation. It can't speak specifically for your case, but it may be needed for some users so it's listed.

**Comment by StellaSmith** [comment]
Gotcha
