### ISSUE TITLE
Linux package repositories

### ISSUE THREAD

**Issue by T-oasterO-ven** [mastercoms/tf2cfg#61]
Is auto-update a thing for beta package updates or for full releases? (or is it a option i'm not aware of)

Also, I've been just overwriting between beta builds all this time, is that the best way to update right now on Linux?

**Comment by mastercoms** [comment]
Autoupdating doesn't work on Linux, since the app is handled through your package manager. There will be repositories soon for them.

**Comment by T-oasterO-ven** [comment]
Ok, update through installing again for now, got it.

**Comment by mastercoms** [comment]
Closing because the mastercomfig 7 app is discontinued.
