### ISSUE TITLE
Modules not working

### ISSUE THREAD

**Issue by CrashedNLanded** [mastercoms/tf2cfg#612]
Currently for me the modules don't work at all no matter what preset I have and the module adjustments I use.

**How you encountered the issue**
With both the browser and the app

**Screenshots**
I can't show screenshots atm.

**Desktop (please complete the following information):**
* mastercomfig version 9.6.3
* Preset and addon(s): Null canceling, flat mouse, no tutorial, and disable pyroland
* Custom values (if any):
* DX level: both 9.5 and 8.1
* Launch options: -novid -nojoy -nosteamcontroller -nohltv -particles 1 -precachefontchars -noquicktime
* Operating system (OS): Windows 10
* Graphics card (GPU): 1660 ti
* Graphics driver version: 497.29
* Processor (CPU): i7-4790
* TF2 on HDD or SSD: SSD
* Memory (RAM) size in MB or GB: 16GB

**Comment by Kenajcrap** [comment]
once you are able to show screenshots, please screenshot your `tf\cfg\user` folder and `tf\custom` folder.

**Comment by mastercoms** [comment]
Hi! Just to get some clarification, what do you mean by "with both the browser and the app"?

Also, did you download customizations and put them in a user folder tf/cfg?

**Comment by micwoj92** [comment]
> Hi! Just to get some clarification, what do you mean by "with both the browser and the app"?

tf2 browser game

**Comment by CrashedNLanded** [comment]
Yeah i dont know what I meant from that, I mean from the .exe, and yes I did send the send the customizations to the user folder in that folder location.

**Comment by CrashedNLanded** [comment]
I tried from both the SSD and my storage drive and neither worked.

**Comment by CrashedNLanded** [comment]
Ok I dont know how but I just fixed the problem, sorry for wasting your guy's time.
