### ISSUE TITLE
Crashes "out of memory.." and "failed to lock vertex buffer.."

### ISSUE THREAD

**Issue by ChaoticSlacker** [mastercoms/tf2cfg#62]
## Reporting an issue

Hello, 

I have to first say that I'm new to gaming on Linux so please bear with me. Also, the config makes playing the game on this specific machine a great experience if it weren't for these occasional crashes.
The vanilla Steam settings were very stable and I never had a crash once (18hr of play) but the game was essentially unplayable in comparison to how it performed w/ the mastercomfig settings. Unfortunately it was only after I started using the settings that I began to experience crashes. 

Thanks to everyone that worked on this! :+1: 

The crash errors that I get are : 

"Out of memeory or address space, texture quality settings may be too high" 
-this one happens frequently 

"failed to lock vertex buffer in CMeshDX::LockVertexBuffer: nVertexCount=616, nFirstVertex=0"
-this happened once on a map I've never been on, not sure if it was a custom map or what but tf2 crashed so i'm adding it to the post. 

Issue seems to happen randomly when trying to join a casual map or when swapping maps. Honestly I can't pinpoint exactly what it is as I'm not exactly sure what I'm looking for. 

mastercomfig Version : 6.10.0 (i did attempt Version 7 but it hung on the speed test, does it normally take over ~3min?)

Other than that I have the "mouse-tweaks" and "no soundscape" vpk's. No thing else.
  
Launch Options are : -novid -nojoy -nosteamcontroller -softparticlesdefaultoff -reuse -dxlevel 90 -gl_enablesamplerobjects ( i have dxlevel 90 but dxlevel 92 has same issues and I changed it to 90 in an attempt to troubleshoot myself )

System Info cut and pasted from Steam : 

Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:         Intel(R) Core(TM) i5-3427U CPU @ 1.80GHz
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  2800 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Ubuntu 16.04.5 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.15.0-30-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11906000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-beta-release_2018-06-14

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Ivybridge Mobile x86/MMX/SSE2
    Driver Version:  3.0 Mesa 18.0.5
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x8086
    DeviceID:  0x166
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1440 x 900
    Desktop Resolution: 1440 x 900
    Primary Display Size: 16.14" x 10.08" (19.02" diag)
                                            41.0cm x 25.6cm (48.3cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: IDT 92HD93BXX

Memory:
    RAM:  15944 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Total Hard Disk Space Available:  142546 Mb
    Largest Free Hard Disk Block:  32818 Mb
    VR Headset: None detected

Recent Failure Reports:

Hope someone can help me out with this as tf2 is absolutely horrible w/ vanilla/no-settings ...

Thanks!

**Comment by mastercoms** [comment]
Are you not using the badgpu addon for your Intel HD Graphics card?

**Comment by pasimko** [comment]
I had this problem as well while using an integrated GPU. You should use the badgpu addon. 
Integrated GPUs will often crash when using higher than low settings. 

If the badgpu addon doesn't fix it, try deleting glshaders.cfg

**Comment by mastercoms** [comment]
This is a TF2 issue.
