### ISSUE TITLE
Resolution of double running addons

### ISSUE THREAD

**Issue by Tiagoquix** [mastercoms/tf2cfg#625]
I'm opening this issue to possibly find a solution to the addons system that went back to the old way, leaving aside the pre and post system.

The only problem I've seen so far is the fact that the Transparent Viewmodels addon executes the module commands after the modules are applied. This will, for example, cause a user who uses post_processing=high in their modules.cfg to be replaced with post_processing=off when using run_modules.

The simplest solution is to remove the second run of addons.

And, out of context, I noticed that you removed support for the move_bind module. I don't think it was on purpose, so I sent a pull request that changes the execution of the addons and adds the move_bind module again: #626

**Comment by mastercoms** [comment]
Yes I just hadn't updated the package script yet for the addons change. move_bind is intentionally removed because the app will handle keybinds.
