### ISSUE TITLE
Only `user/modules.cfg` is executed, despite the supposed change to use overrides instead.

### ISSUE THREAD

**Issue by WhyIsEvery4thYearAlwaysBad** [mastercoms/tf2cfg#639]
**Describe the bug**
Only `user/modules.cfg` is executed, despite the supposed change to use overrides instead.

**How you encountered the issue**
1. Create the file `overrides/modules.cfg`.

**Screenshots**

**Desktop (please complete the following information):**
* mastercomfig version: 9.8.0 | March 18, 2022 
* Preset and addon(s): Disable Pyroland, No Tutorial, Null Canceling movement, and OpenGL.
* Custom values (if any): `mat_bumpmap 1`
* DX level: 92
* Launch options: -novid -nojoy -nosteamcontroller -nohltv -particles 1 -precachefontchars -noquicktime
* Operating system (OS): Linux (Manjaro)
* Graphics card (GPU):
* Graphics driver version:
* Processor (CPU):
* TF2 on HDD or SSD: SSD
* Memory (RAM) size in MB or GB: 8GB

**Comment by mastercoms** [comment]
This is something on your end. https://github.com/mastercomfig/mastercomfig/blob/develop/config/mastercomfig/cfg/comfig/comfig.cfg#L1955
