### ISSUE TITLE
Unbinding problem

### ISSUE THREAD

**Issue by DemoMain234** [mastercoms/tf2cfg#64]
So i have problem that whenever i boot up tf2 all my movement keys and my call for medic keys unbind.Its really frustrating bc it happens everytime and it stops when i delete masterscomfig.Its really a shame bc its very good config .

    
    * Config version-Medium low (problem happens on every one)
    * Config preset and addon(s)- Chris config
    * Custom values (if any)-none
    * DX level-95 (it happens on each one)
    * Launch options- -dxlevel 95 -refresh 120 -heapsize 1048576 -full -w 800 -h 600 -console -novid -useforcedmparms -noforcemaccel -noforcemspd -nosteamcontroller -softparticlesdefaultoff -reuse -lv -autoexec.cfg
    * Operating system (OS)- windows 7 64bit
    * Graphics card (GPU)-ATI Radeon HD 3400 Series
    * Processor (CPU)- AMD Athlon(tm) 64 X2 Dual Core Processor 6000+ 3.00 GHz
    * HDD or SSD-none
    * RAM size in MB or GB- 6 GB

I hope you fix it and thanks in advance!

**Comment by mastercoms** [comment]
> * Config preset and addon(s)- Chris config

?

Also, do you use custom.cfg?

**Comment by DemoMain234** [comment]
Nvm i fixed it.There were some shenanigans with my config file so i reinstalled it and it works fine
