### ISSUE TITLE
Null-Canceling Movement script doesn't work...

### ISSUE THREAD

**Issue by oXrayXo** [mastercoms/tf2cfg#646]
**Describe the bug**
Null-Canceling Movement script just doesn't work.

**How you encountered the issue**
I followed Mastercomfig Clean Up setup, downloaded medium low preset and Null-canceling Movement script, I put those files in tf_custom, I ran the game, I typed in map_itemtest in console and entered, the script didn't work.

**Comment by micwoj92** [comment]
don't use it

**Comment by mastercoms** [comment]
did you follow the instructions listed on the addon to bind it?
