### ISSUE TITLE
Typo on Linux Optimization Documentation.

### ISSUE THREAD

**Issue by AmandaRoseChaqueta** [mastercoms/tf2cfg#654]
**Describe the bug**
The page for optimizations for linux on Mastercomfig documentation (https://docs.mastercomfig.com/page/os/linux/) has an error on the Native Libraries instruction section, specifically the Debian/Ubuntu-based distributions installation command where instead of saying "sudo apt install libsdl2-2.0-0:i386" it shows up as "sudo apt install apt install libsdl2-2.0-0:i386".
**Screenshots**
![Screenshot from 2022-07-20 12-43-59](https://user-images.githubusercontent.com/89411895/180047951-834cfbd4-5090-420d-ba06-5b79fbae2ace.png)

**Comment by micwoj92** [comment]
ON IT!

**Comment by AmandaRoseChaqueta** [comment]
![Screenshot from 2022-07-30 13-52-52](https://user-images.githubusercontent.com/89411895/181937676-f7fa0e7b-a82e-48ec-b7d2-abce8f0cefd8.png)
Looks like the website still displays the same typo even after the github change https://docs.mastercomfig.com/page/os/linux/#native-libraries
