### ISSUE TITLE
Engine issue "Out of memory/address space" on macOS

### ISSUE THREAD

**Issue by irefl** [mastercoms/tf2cfg#66]
* Config version (don't say latest, say the actual version, found in the
      startup console output)
6.10.0 
    * Config preset and addon(s)
Medium Low 
   * Custom values (if any)
N/A
   * DX level
92
   * Launch options
-novid -nojoy -nosteamcontroller -softparticlesdefaultoff -reuse -dxlevel 92
   * Operating system (OS)
macOS Mojave 10.14.1
   * Graphics card (GPU)
intel hd 5000
   * Processor (CPU)
Core i5 4260u (2c/4t)
   * HDD or SSD
500gb HDD
   * RAM size in MB or GB
8gb DDR3 @ 1600

Consistently getting a crash preceded by a popup reading along the lines of engine error: out of memory/address space, and suggesting to turn down texture quality. This would occur often on casual map switch, or on class change which I couldn't replicate with consistency.
I've tried reinstalling the config from scratch/cleaning my install, and running it without other addons or custom.cfg. I would try mastercomfig 7 but I get the "App not supported" error on the website, and don't know how to compile from source

Any help appreciated, thanks!

**Comment by mastercoms** [comment]
This is an issue with TF2 that has been attempted to be addressed by the developers in the last few patches.
