### ISSUE TITLE
Tf2 does not recognize reset.cfg

### ISSUE THREAD

**Issue by wweony23** [mastercoms/tf2cfg#668]
**Describe the bug**
My game does not recognize reset.cfg 
**How you encountered the issue**
Saw error message in a console after I switched from scout to pyro.

**Screenshots**

**Desktop (please complete the following information):**
* mastercomfig version: 9,6,3
* Preset and addon(s):
![изображение](https://user-images.githubusercontent.com/72761693/185954967-f6bd05a9-167f-4888-b070-b910b643d3da.png)

* Custom values (if any): not sure what does it mean
* DX level: 12 
* Launch options: -
* Operating system (OS): Windows 10
* Graphics card (GPU): Geforce RTX 2070 Super
* Graphics driver version: 512.15
* Processor (CPU): AMD Ryzen 7
* TF2 on HDD or SSD: SSD
* Memory (RAM) size in MB or GB: 69 GB

Recently played tf2 when suddenly reset.cfg is no longer seen by tf2
I use reset.cfg as a reset file in order to prevent any class overwrites during gaming session. 
Whenever you type "exec reset" console responds.
`'reset' not present; not executing.
`
Screenshots
![изображение](https://user-images.githubusercontent.com/72761693/185957086-7cf45ef6-37bc-4268-a536-9653ae80f55e.png)
At first I tried to visit mastercomfig website.
Made overrides.cfg but nothing seems to change.
![изображение](https://user-images.githubusercontent.com/72761693/185957374-df269ec9-9149-4f42-be7e-643668acadae.png)
I do not know what really happened since it was working fine for a couple of month until that day.
I tried my best to fix it by myself but after a couple of hours of intense researching I did not find any working solution.

**Comment by micwoj92** [comment]
You can use game_overrides.cfg instead of reset.cfg

**Comment by mastercoms** [comment]
also shouldn't have your normal cfgs in overrides folder if you are using exec reset, etc. either update to exec overrides/reset, etc or move them back to the main cfg folder

**Comment by wweony23** [comment]
i deleted all overrides but reset.cfg is still broken

**Comment by mastercoms** [comment]
no one asked you to delete anything, could you follow the instructions regarding moving a few files selectively out of overrides?

**Comment by wweony23** [comment]
ok i moved all files back and left game_overrides only
![изображение](https://user-images.githubusercontent.com/72761693/185985335-651ee331-969b-478a-a641-2c539bebe176.png)
`'reset' not present; not executing.
`
Still have this issue

**Comment by micwoj92** [comment]
Where do you have reset.cfg then now?

**Comment by mastercoms** [comment]
Your class configs, autoexec and modules should also be in overrides, but yes, where is your reset.cfg now?

**Comment by wweony23** [comment]
![изображение](https://user-images.githubusercontent.com/72761693/185991525-0e2d41c0-4ccf-411d-9692-88e916dab85f.png)

**Comment by wweony23** [comment]
Those copies and other weird files are for test so ignore them.

**Comment by wweony23** [comment]
> errides folder if you are using exec reset, etc. either update to exec overrides/reset, etc or move them back to the main cfg folder

what does mean "normal cfgs"
is that classes one?
I did not get it at all
at first you say me to bring them back to cfg folder and then you say me to bring them back

**Comment by mastercoms** [comment]
Please refer to the installation guide: https://docs.mastercomfig.com/latest/setup/install#custom-configs

It specifies exactly which files to put in overrides, as I have also said. You should have them in `tf/cfg/overrides`. All other files should be in `tf/cfg`.

**Comment by wweony23** [comment]
ok what should I do if I want to make resetting system with overrides instead of reset.cfg?

**Comment by mastercoms** [comment]
That's how you do it. `reset.cfg` would be in `tf/cfg`. Or, you can move `reset.cfg` to `tf/cfg/overrides`, but then you have to change `exec reset.cfg` to `exec overrides/reset.cfg`.

If you mean how to use `game_overrides.cfg`, just have a `game_overrides.cfg` in `tf/cfg/overrides`. Copy and paste from `reset.cfg` into `game_overrides.cfg`. Remove all `exec reset.cfg`. `game_overrides.cfg` will be automatically executed by mastercomfig on class change.

**Comment by wweony23** [comment]
Well, I picked 2nd variant. Thank you for your help! 
 Also, for some reason I cannot make my cl_interp higher then 0.030303.
 Is it caused by game limits or mastercomfig settings?

**Comment by mastercoms** [comment]
How are you trying to set it?

**Comment by wweony23** [comment]
cl_interp 5

**Comment by mastercoms** [comment]
Where are you setting it?

**Comment by wweony23** [comment]
ingame console

**Comment by wweony23** [comment]
~ button

**Comment by wweony23** [comment]
before joining a match

**Comment by mastercoms** [comment]
put it in game_overrides.cfg, also I don't recommend it just so you know

**Comment by wweony23** [comment]
tried it but it did not help me

**Comment by wweony23** [comment]
for some reason it goes back to cl_interp 0.030303

**Comment by wweony23** [comment]
![изображение](https://user-images.githubusercontent.com/72761693/187926426-0759f76e-2d2b-47e3-80d7-c3290ba20f7f.png)

**Comment by wweony23** [comment]
the thing is it keeps resetting whenever I join a match

**Comment by wweony23** [comment]
i surfed the net and all thoose cases have one thing similar, all of them used mastercomfig

**Comment by mastercoms** [comment]
what file is that

**Comment by wweony23** [comment]
![изображение](https://user-images.githubusercontent.com/72761693/187937345-27662d86-864a-4639-86b3-aa7ed0ef6e3c.png)

**Comment by wweony23** [comment]
game_overrides.cfg

**Comment by wweony23** [comment]
anything wrong?

**Comment by mastercoms** [comment]
You should also put snapshot_buffer=custom in modules.cfg

**Comment by wweony23** [comment]
okay let me try

**Comment by wweony23** [comment]
'user/game_overrides.cfg' not present; not executing.

**Comment by wweony23** [comment]
i just noticed it

**Comment by wweony23** [comment]
maybe that's why

**Comment by wweony23** [comment]
here it is C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\tf\cfg\overrides

**Comment by mastercoms** [comment]
Can you put `version_comfig` in console and tell me what it says?

**Comment by wweony23** [comment]
ok i fixed it by moving game_overrides into user folder
] version comfig
Build Label:           7431962   # Uniquely identifies each build
Network PatchVersion:  7431962   # Determines client and server compatibility
Server AppID:           232250
Protocol version:           24   # High level network protocol version
Client version:        7431962
Server version:        7431962
Client AppID:              440

**Comment by wweony23** [comment]
Also for some reason I cannot use weapon taunt
I press G button and it shows taunt menu, but when i press G again nothing happens

**Comment by wweony23** [comment]
I can change cl_interp but I still cannot call game_overrides.cfg via console which is really weird

**Comment by treacherousfiend** [comment]
you have to type specifically `version_comfig` with an _ between the 2 words. Because you used a space it just used the default source engine `version` command.
The fact that it worked after you moved it to the user folder means you have a pretty outdated version of comfig, and probably should update
And as for the weapon taunt, there's a couple of weapons that don't have weapon taunts, do _none_ of the weapon taunts work?
when you try and call game_overrides.cfg via the console (which you shouldn't need to do) are you typing `exec game_overrides.cfg` or `exec user/game_overrides.cfg`?

**Comment by wweony23** [comment]
i type exec game_overrides.cfg
mastercomfig version : 9.6.3 | September 20, 2021 
speaking of taunts it applies to every single weapon I use so it is definetly a bug

**Comment by treacherousfiend** [comment]
the exec command requires filepaths relative to the cfg folder, so because its in the user folder, you'd need to type `exec user/game_overrides.cfg`
Also, that version of comfig is nearly a year old, and you probably should update.
If you do update, you'll need to rename the `user` folder to `overrides`.
