### ISSUE TITLE
Linux app nonfunctional

### ISSUE THREAD

**Issue by Leo40Git** [mastercoms/tf2cfg#67]
So the Linux version of the app straight up doesn't work. Trying to run it (with or without sudo) results in `Segmentation fault`. It also made a core dump the first time I tried to run it, but I don't know how to retrieved it. I've tried both the Ubuntu/Debian package and the generic Linux tar.xz archive.

**Comment by David024** [comment]
I've tested this mod on Linux Mint 19.1, It works there at least, But Doesn't work on Solus OS, other distro's I'm unsure.

**Comment by 1337miro** [comment]
Having the same issue on Ubuntu 19.04 Disco.

**Comment by mastercoms** [comment]
The app requires certain dependencies. I forgot what they were at this point, but will try to look around.

**Comment by mastercoms** [comment]
Closing because the mastercomfig 7 app is discontinued.
