### ISSUE TITLE
Medium-high preset and above causing issues on Wayland

### ISSUE THREAD

**Issue by getchoo** [mastercoms/tf2cfg#672]
**Describe the bug**
When using a clean/fresh install, TF2 is able to run normally on Wayland. However, after installing a preset that is medium-high and above, the main menu will be invisible; and on the second launch, nothing will render and it will just be a black screen. This will persist even after everything has been removed from custom, and the only way i've found to reverse this is through the clean up launch options or installing a lower preset. This does not happen under Xorg, and i'm not sure if it is specific to NVIDIA cards yet. I've also been able to reproduce this issue on KDE and GNOME, as well as on separate distros including Arch and Fedora

**How you encountered the issue**
- Use medium-high, high, or ultra preset
- Launch the game twice

**Screenshots**
Reproducible launch on fresh install/after cleanup:
![image](https://user-images.githubusercontent.com/48872998/189239635-02aa1f67-a4b0-4243-bff9-ae6fef2baca3.png)

First launch with any of the presets mentioned:
![image](https://user-images.githubusercontent.com/48872998/189239553-ae032618-4abe-4f25-ae58-fd2f75161103.png)

**Desktop (please complete the following information):**
* mastercomfig version: 9.10.0
* Preset and addon(s): None
* Custom values (if any): None
* DX level: n/a
* Launch options: None
* Operating system (OS): Fedora 36
* Graphics card (GPU): NVIDIA GTX 1660 SUPER
* Graphics driver version: 515.65.01
* Processor (CPU): AMD Ryzen 5 5600x
* TF2 on HDD or SSD: SSD
* Memory (RAM) size in MB or GB: 16GB

**Comment by mastercoms** [comment]
Can you test if setting anti_aliasing=off fixes it?

**Comment by getchoo** [comment]
thanks, turning it off worked! i do want to ask though: is this due to mat_alphacoverage or just mat_antialias?

**Comment by mastercoms** [comment]
probably msaa because it changes the video mode

**Comment by getchoo** [comment]
ah shame, i like msaa :( but i've been dealing with this for months, so i'm glad to have a fix
