### ISSUE TITLE
Change the logo module to an echo module

### ISSUE THREAD

**Issue by Tiagoquix** [mastercoms/tf2cfg#682]
Change it to

echo=simple
echo=detailed (default)

where echo=simple simply displays "mastercomfig loaded version with number", and echo=detailed displays everything plus the logo.

I personally don't like the current long and spacious echo the config has.

I can do a PR for this, but I need your (mastercoms) approval first.

**Comment by mastercoms** [comment]
I don't agree with customizing the echo past the logo.
