### ISSUE TITLE
Figure out cl_interp on NPCs

### ISSUE THREAD

**Issue by mastercoms** [mastercoms/tf2cfg#684]
Fixed laggy animations on Halloween bosses, skeletons, ghosts and other ghoul-like beings

https://youtu.be/TGulB0MfxPs?t=235

For some reason, this doesn't work consistently, will have to investigate why

**Comment by mastercoms** [comment]
I'm not too sure what this change actually entailed.

**Comment by Tiagoquix** [comment]
Try this, maybe it works:

```
cl_interp 0
cl_interp_ratio 0
sv_client_min_interp_ratio -1
```

> sv_client_max_interp_ratio               : 5        : , "rep"          : This can be used to limit the value of cl_interp_ratio for connected clients (only while they are connected). If sv_client_min_interp_ratio is -1, then this cvar has no effect.
sv_client_min_interp_ratio               : 1        : , "rep"          : This can be used to limit the value of cl_interp_ratio for connected clients (only while they are connected).               -1 = let clients set cl_interp_ratio to anything  any other value = set minimum value for cl_interp_ratio

**Comment by Sloofy** [comment]
Not sure how much of a good lead this is, but from https://github.com/ValveSoftware/Source-1-Games/issues/4413#issuecomment-1282123531

> **nb_update_frequency** is the culprit for this.
Changing the value to 0.05 (default is 0.1) fixes the stuttering for bosses and skeletons,
but it may increase usages on server or client PC's.
> 
> _(the prediction on increased usages are just speculations from my side)_

**Comment by mastercoms** [comment]
No, that's not a real solution.

**Comment by Ashetf2** [comment]
Indeed. From the same issue.

> while this would fix issues with laggy NPC entities, it would cause issues with TFBot pathing (most notable on mann vs machine) where bots trying to move past a body-blocking obstacle like a player or sentry gun would just jitter in place instead of trying to move around whatever's blocking them. it also changes the timing on stuff like when horsemann's attack is sent out (watch for sparks flying from his axe) monoculus' rate of fire when firing rockets (most notable before he's only firing 1 rocket at a time, the downtime between rockets is much shorter) so it's not a end-all solution for this issue.

**Comment by mastercoms** [comment]
Seems like this is not working properly in the game, not sure what the patch note is.
