### ISSUE TITLE
A question about r_fastzreject

### ISSUE THREAD

**Issue by Tiagoquix** [mastercoms/tf2cfg#687]
I've seen changes in the value of this cvar several times. Honestly, I don't know what it does, but wouldn't the ideal perhaps be to remove it from comfig.cfg and let the default value take effect?

Thanks for the attention.

**Comment by Tiagoquix** [comment]
🤔

**Comment by mastercoms** [comment]
> wouldn't the ideal perhaps be to remove it from comfig.cfg and let the default value take effect?

What does it matter if the default value comes from comfig or the game? It's about picking a default value in the end for the user. So I'm not sure what this question is about.

**Comment by Tiagoquix** [comment]
> > wouldn't the ideal perhaps be to remove it from comfig.cfg and let the default value take effect?
> 
> What does it matter if the default value comes from comfig or the game? It's about picking a default value in the end for the user. So I'm not sure what this question is about.

Well, it's just an honest question. [Doing a quick internet search](https://duckduckgo.com/?q=r_fastzreject), it seems good to enable it for users with ATI graphics cards (but they are old; forum threads are from the HL2 era). But anyway, thanks for the answer.

**Comment by mastercoms** [comment]
Well the initial question wasn't asking what it does. It does a full z prepass, you might find better results searching that.

**Comment by mastercoms** [comment]
The reason I flip between it is because of fillrate vs prepass is very hard to measure especially on such a wide range of cards. The cost tradeoffs are not immediately clear but it also depends on a variety of other settings within the config.

**Comment by aSeriousDeveloper** [comment]
I noticed that according to the [Valve Developer Wiki](https://developer.valvesoftware.com/wiki/Console_Command_List/R) that r_fastzreject supports a value of -1 to defer to hardware settings. 

Is this something supported in TF2 / useful? Or is this just more likely to cause inconsistency between different installations of mastercomfig?

**Comment by mastercoms** [comment]
No such hardware query exists. A non-zero value enables it.
