### ISSUE TITLE
GitHub workflow badges are broken in README.md, docs/index.md, docs/index.ru.md

### ISSUE THREAD

**Issue by micwoj92** [mastercoms/tf2cfg#691]
https://github.com/badges/shields/issues/8671

**Comment by getchoo** [comment]
i miss you

**Comment by hyperventilation** [comment]
i do too

**Comment by getchoo** [comment]
hamborg from hambur

**Comment by micwoj92** [comment]
> i miss you

https://www.fsf.org/bulletin/2022/spring/unjust-algorithms

**Comment by getchoo** [comment]
i've come to agree with you micwoj
having chatgpt talk to me about how "good" manjaro is really changed me as a person. i will never use such unjust and biased algorithms against you again
