### ISSUE TITLE
Add "custom" or "auto" to more modules that affect advanced options and other settings.

### ISSUE THREAD

**Issue by ghost** [mastercoms/tf2cfg#692]
**Is your feature request related to a problem? Please describe.**
I would like more modules that effect certain settings to have an option to not touch the setting.

**Describe the solution you'd like**
Add a simple "custom" setting for the options that effect chat, voice chat, hud player model, console, HTML MOTD, and any other settings that might already be set manually in the settings and advanced settings. This does not have to change very low because that's practically a nuke everything option and I see the reason for it existing. However, currently mastercomfig presets assume you want chat enabled, voice chat enabled, etc, even if you might have changed that in settings. I would also suggest that this becomes the default for these settings.

**Describe alternatives you've considered**
None.

**Additional context**
For my specific use case this would be a very welcome change. I have a relatively robust config which changes basically every setting in a config file, including every advanced option, so it would be nice to have the option to make sure that mastercomfig does not touch those settings.

I understand that it is possible to customize presets easily, but a user might assume that those settings are untouched by mastercomfig, or they just might want the setting to be easily changed in the settings menu without mastercomfig overriding that next time you launch the game.

**Comment by mastercoms** [comment]
I don't agree that just because something is exposed in the UI, that should be able to be skipped. After all, mastercomfig is meant to provide new tools for customization and there is some expectation for users to integrate their own settings to use mastercomfig.

**Comment by ghost** [comment]
Well, graphics settings are also exposed in settings but I am fine with this mod. It's mainly a convenience consideration. I would prefer that if I change a setting such as this that it stays that way after I reopen the game. Instead, I would have to reinstall mastercomfig with these changes in the app or be expected to create my own modules.cfg overrides and learn how to use it by reading documentation. As a new user, neither of these are as simple as just changing the setting in game and expecting it to stay, and as an advanced user, it's annoying that I need to shape my configs around mastercomfig.

I'm not asking that every single graphics setting and network setting be allowed to be disabled by the user to the point where they can just disable all of mastercomfig, just some of the more basic and commonly accessed settings not be touched by mastercomfig if its not necessary.

I guess I could probably explain this a little better. Basically: the pendulum swings the other way for such simple configuration options. For graphics and networking settings mastercomfig is a life saver, I am fine with opening a modules.cfg to change a setting that I wouldn't know how to change otherwise. However, it goes in the other direction and approaches being an inconvenience when the setting is already a basic switch in advanced options. It becomes more inconvenient to use mastercomfig for that.

**Comment by mastercoms** [comment]
> neither of these are as simple as just changing the setting in game and expecting it to stay

mastercomfig is an up to date, one stop shop for customizing the game. That's what makes it easy for people. The advanced option menu isn't organized very well, doesn't explain or expose options correctly. While with the app, there's potential for it be continually improved. I understand the concerns regarding having to redownload VPKs each time, and this will be improved in future app revisions to allow for incremental updates. I hope this addresses your points regarding the simple options you're talking about throughout the post.

> it's annoying that I need to shape my configs around mastercomfig

Once you do, it's a lot easier. This is why it's expected and encouraged.

**Comment by ghost** [comment]
But there are already modules that have this option, like snapshot_buffer and downloads. I don't see much reason that these options are required to be set by mastercomfig with no option to disable mastercomfig touching them. You guys already removed the move keys setting so I think you at least somewhat agree, there are some settings that some people just might not want mastercomfig to touch.

More options are always good, and I think giving people the option to set these elsewhere and disable them in mastercomfig would be good. I already have put a lot of effort into shaping my configs around mastercomfig, but the one thing that irks me about it is the fragmentation of settings, and how some settings (voice and text chat, htmlmotd) are set by mastercomfig while others (demo support, monitor gamma, crosshair settings) go into a separate config file that I created. It would be nice if some of the "general" settings would be an opt in or a don't touch thing.

**Comment by mastercoms** [comment]
Move keys weren't removed, just moved to another part of the app.

Settings which had these things added were very specific cases, and weren't justified by a general blanket statement regarding all settings.

Eventually mastercomfig will handle all of these settings, so it won't make much of a difference if it's a module or not at the moment.

I feel like this discussion could go on ad nauseam, closing.
