### ISSUE TITLE
I can't hear footsteps anymore.

### ISSUE THREAD

**Issue by ZIIkII** [mastercoms/tf2cfg#70]
Hello, I recently did some changes in my config (Mastercomfig_7) My preset was on very low, the only things that I've changed is turning on outlines in "HUD" and Footsteps in "Sound".

I went to check "community" afterwards to enable transparent viewmodels, but sadly when I entered the game I could no longer hear any kind of footstep sound.

It's a really irritating me, it's a huge annoyance and I tried everything to get them back I tried removing my autoexec and config files checked the integrity of game files and still nothing worked, I tried to look for a script to enable them but I can't seem to find anything about it in google.

So I hope you can help me with this. I'd be forever grateful if you do.
Thanks!

**Comment by JarateKing** [comment]
The "footsteps" option should be what removes them.

It'd be the "mastercomfig-addon-no-footsteps.vpk" in your custom folder that you should delete if you want them back.

**Comment by ZIIkII** [comment]
Thanks that helped alot !
