### ISSUE TITLE
Crash on linux

### ISSUE THREAD

**Issue by ghost** [mastercoms/tf2cfg#703]
Team Fortress 2 is consistently crashing after the initial loading, before the main menu. Happened on 9.10.1 and 9.10.0. No problem with 9.9.3. Happens with or without the launch options. 9.9.3 works with these modules while 9.10.x don't.

Recreating:
Consistently happens when I tried to start the game with any mastercomfig vpk files on /custom folder. Crashes without expection. Most of the time before the first loading screen but sometimes crashes seconds after main menu loads.

mastercomfig version: 9.10.x
Preset and addon(s): Medium-High Preset. OpenGL, No Tutorial and Flat Mouse addons. 
Custom values (if any):pyrovision=high, romevision=on, sheens_speed=fast, sheens_tint=full, textures=very_high, sprays=on
Launch options: -novid -nojoy -nosteamcontroller -nohltv -particles 1 -precachefontchars -noquicktime 
Operating system (OS): openSUSE Tumbleweed with 6.1.12 kernel
Graphics card (GPU): Intel Iris Xe
Graphics driver version: Mesa 22.3.5
OpenGL version: 4.6
Processor (CPU): i7 1165G7
TF2 on SSD
Memory (RAM): 16GB

**Comment by ghost** [comment]
Ok, might be a distro specific problem, or a problematic package. Fedora 37 KDE, on the same hardware works fine.

**Comment by HelpMePleasepls** [comment]
I'm also experiencing the same problem on Tumbleweed.

**Comment by HelpMePleasepls** [comment]
Nevermind, it appears that using proton with mastercomfig does not work well with each other. Once I disabled using any compatibility tool and started the game with the steam linux runtime, everything worked perfectly.
