### ISSUE TITLE
Consideration of possible removal of certain modules

### ISSUE THREAD

**Issue by Tiagoquix** [mastercoms/tf2cfg#708]
Some modules can be changed with existing options in the game. Here are some I suggest removing from mastercomfig:

- [Downloads](https://docs.mastercomfig.com/latest/customization/modules/#downloads). Controled from the options menu.
- [Pyrovision](https://docs.mastercomfig.com/latest/customization/modules/#pyrovision). Controled from the advanced options menu.
- [Romevision](https://docs.mastercomfig.com/latest/customization/modules/#romevision). Same reason as before.
- [Contracts](https://docs.mastercomfig.com/latest/customization/modules/#contracts). Same reason as Pyrovision.

(If the idea is approved, I will make the module removal pull request myself.)

**Comment by mastercoms** [comment]
I don't think modules should be removed because they're available in the options menu. Graphics options are controllable as well. The next update includes settings to skip mastercomfig setting these options and makes them more consistent.
