### ISSUE TITLE
Two modules that I personally don't think deserve to be a module

### ISSUE THREAD

**Issue by Tiagoquix** [mastercoms/tf2cfg#709]
Straight to the point:

- FPS Cap: as much as TF2 is an old game, I personally disagree in terms of setting the maximum FPS cap. Yes, it reduces the input lag, but it weighs more on the processing of more powerful machines (making them generate more frames per second for basically "nothing"). We should respect TF2's default limit of 300, or even use 400 like CS:GO. I don't think the input lag reduction compensates for the "wasted" performance on more powerful computers (higher FPS cap = consumes even more CPU and GPU unnecessarily).

- HUD Achievements: as much as I understand that this can cause performance losses, I think that removing the achievement effect is a bad thing. It's always nice to achieve something, and TF2 only has 513 achievements (some of them unobtainable, but still...). What I want to say is: I don't think it pays to remove such an effect and lose the joy of achieving an achievement. I think HUD Achievements should only be disabled by individual tweaks on the very low preset.

That's it. Thank you for your attention.

**Comment by mastercoms** [comment]
I agree with setting a lower FPS cap by default but not removing the module.

HUD achievements don't affect the achievement effect. It disables the HUD achievement tracker, a custom UI you can use to track up to 3 achievements you would like to focus on getting/monitoring progress for.

**Comment by Tiagoquix** [comment]
> a custom UI you can use to track up to 3 achievements you would like to focus on getting/monitoring progress for.

I think there is no need to disable them, because such tracking only happens if the user explicitly activates it in the achievements menu. The tracking (the thing in the HUD) isn't displayed by default afaik.

**Comment by mastercoms** [comment]
As noted, some parts of it run in the background even if not enabled by the user.
