### ISSUE TITLE
Modules not working

### ISSUE THREAD

**Issue by minimaster36** [mastercoms/tf2cfg#71]
Created a few aliases in modules.cfg tf/cfg and none of them are working:
'preset_ultra
alias run_n_packet_buffer n_packet_buffer_very_high
alias run_n_rate "rate NaN;net_splitpacket_maxrate NaN;net_maxcleartime NaN"
alias ragdolls ragdolls_medium
alias gibs gibs_medium
alias water water_high'
the 3 bottom aliases dont seem to work for me, I'm not sure what I've done wrong, if i have at all.
mastercomfig 6, using medium high w/ no tutorial addon
DX level (uncertain)
Launch Options ' -force_vendor_id 0x10de -force_device_id 0x1B80 -novid'
Win 10 OS
GTX1080
i7-4790k
HDD
16GB

**Comment by mastercoms** [comment]
run_n_packet_buffer and run_n_rate are not the module names for mastercomfig 6. 

See here for a list of module names: https://github.com/mastercoms/mastercomfig/blob/release/config/mastercomfig/cfg/comfig/modules-run.cfg

Examples of usage: 

https://github.com/mastercoms/mastercomfig/blob/release/config/mastercomfig/cfg/comfig.cfg#L49
https://github.com/mastercoms/mastercomfig/blob/release/config/cfg/presets/ultra.cfg

Modules do work, or else none of the presets would be functional.

Also, you need to recalculate your rate values.
