### ISSUE TITLE
mastercomfig docs: remove version select and keep only the latest one

### ISSUE THREAD

**Issue by Tiagoquix** [mastercoms/tf2cfg#710]
I don't see any reason why would someone use an old version of mastercomfig.

It isn't an application. It's purely CFG and script tweaks.

And that leads me to believe that it is unnecessary to keep the old versions in the documentations.

If this idea is approved: I would also suggest to remove `/latest/` from the URLs.
For example: `https://docs.mastercomfig.com/latest/customization/modules/` -> `https://docs.mastercomfig.com/customization/modules/`.

That's all. Thanks for your attention.

**Comment by mastercoms** [comment]
Sometimes newer versions have problems that make people want to download an older version. This is the main reason I support older versions on the download page.

For the documentation, many people are stuck with using an older version (breaking changes with their config) and would like to read documentation relevant to them. This is the main reason I support older versions on the documentation page.
