### ISSUE TITLE
Removal of the mod support module + changes to the "Dynamic Background" module

### ISSUE THREAD

**Issue by Tiagoquix** [mastercoms/tf2cfg#711]
Straight to the point:

Mod support module removal - why: the name is somewhat misleading. In the past, the module actually used to break mods, but today it doesn't anymore. The only thing it does now is set `cl_always_flush_models 1` if `mod_support=off` and the user is using the low memory add-on. Maybe we should keep `cl_always_flush_models` always set to `0`?

Dynamic background changes: any dynamic background that isn't itemtest or the preload map is not useful. The Dustbowl background, for example, is lost when joining a server. I think the module should be renamed to "Mod preload" with the options `off` and `on` (`on` being `itemtest`). I don't think it's necessary to support the `preload_room` map; afaik, `itemtest` or `preload_room` as a dynamic background generate the same results.

Thank you for your attention.

**Comment by mastercoms** [comment]
Mod support is a reserved module, in case it breaks with other commands in the future. It's a marker for people who want to keep it compatible.

Dynamic background not restoring on disconnect is fine IMO. People still use the dustbowl level as far as I have seen.
