### ISSUE TITLE
Cloak / Minigun spin up / Sniper zoom / Detonate stickys - MOUSE2 functions not working

### ISSUE THREAD

**Issue by Samg381** [mastercoms/tf2cfg#715]
**Describe the bug**
The bug presents itself upon a fresh installation. Despite adding `bind "MOUSE2" "+attack2"` to `autoexec.cfg` and `game_overrides.cfg` in `tf\cfg\overrides`, none of the class specific secondary weapon functions work, forcing me to manually configure these parameters in the TF2 settings window. Of course, these are quickly overwritten by the VPK addon.

**How you encountered the issue**
Install mastercomfig following instructions on app page. Attempt to use any class-specific secondary weapon functions as listed in title.

* mastercomfig version: mastercomfig version : 9.10.2 | July 9, 2023 
* Preset and addon(s): Ultra, no tutorial
* Custom values (if any):
* DX level: 9.0+
* Launch options: -novid -nojoy -nosteamcontroller -nohltv -particles 1 -precachefontchars -noquicktime
* Operating system (OS): Windows 10
* Graphics card (GPU): RTX 3090
* Graphics driver version: 536.4
* Processor (CPU): i9-12900KF
* TF2 on HDD or SSD: SSD
* Memory (RAM) size in MB or GB: 32GB

**Comment by Samg381** [comment]
Including screenshot of app config
![Screenshot_3](https://github.com/mastercomfig/mastercomfig/assets/3127698/d88591d4-3b5c-490d-b482-581fe3e9968c)

**Comment by mastercoms** [comment]
Can you upload the tf/cfg/app folder

**Comment by Samg381** [comment]
[app.zip](https://github.com/mastercomfig/mastercomfig/files/12065531/app.zip)

**Comment by Samg381** [comment]
somehow `bind MOUSE2 unbind MOUSE2` made it into the `game_overrides.cfg` file in cfg/app... checking if that fixes it..''

**Comment by mastercoms** [comment]
Thanks, I will fix the binds generation in the app to resolve this issue

**Comment by Samg381** [comment]
Even after removing the line, the issue still presents itself. This is completely game breaking.

**Comment by mastercoms** [comment]
I will fix it ASAP

**Comment by mastercoms** [comment]
This should be fixed now! If it isn't, feel free to reopen.

https://github.com/mastercomfig/comfig-app/commit/63b0bd6bc4983a66d27fec8885b71d08f2ef6ffb

**Comment by Samg381** [comment]
![Screenshot_3](https://github.com/mastercomfig/mastercomfig/assets/3127698/fbf1dfb7-38dc-4e2b-8392-bd2d136b9918)

The latest version had no effect. After switching between soldier / spy, the MOUSE2 bindings are still wiped.

After restarting the game...

![Screenshot_4](https://github.com/mastercomfig/mastercomfig/assets/3127698/93039262-5897-45a4-974b-6bef407b81a1)

**Comment by mastercoms** [comment]
Can you share your app folder again?

**Comment by Samg381** [comment]
[app.zip](https://github.com/mastercomfig/mastercomfig/files/12115858/app.zip)

**Comment by mastercoms** [comment]
That's very interesting, because game_overrides.cfg is binding the mouse2 back to secondary attack. I am not sure why it's clearing out after switching to soldier and then back to another class.

**Comment by mastercoms** [comment]
Should be fixed now, sorry for the delay. Please retest and let me know if it's good now.
