### ISSUE TITLE
Discord help channels are inaccessible?

### ISSUE THREAD

**Issue by ShaiAvr** [mastercoms/tf2cfg#721]
I started to use `mastercomfig` this morning and I quite like it. However, I encountered an issue I wanted to address. Not really a bug, but more of a customization issue. The website instructed me to go to the discord server for help, but when I joined the server I couldn't find any channels related to getting help with `matercomfig`. When digging further, I found I have "NoAccess" to these channels:

![Screenshot 2023-07-28 154617](https://github.com/mastercomfig/mastercomfig/assets/35605235/92d685d7-d92e-43e6-ad39-157840a75268)

I know it's probably not the right forum to post this issue but since the discord channels are not available to me, I couldn't find another platform to talk about this. Can you explain how to get access to the help channels on Discord or where to ask for help?

**Comment by mastercoms** [comment]
![Channels & Roles](https://github.com/mastercomfig/mastercomfig/assets/2672245/eb6af1fa-bb43-4945-a0af-91ed81736c2e)

what do you have selected in this menu

I am guessing you have community opt out (also can toggle in the roles channel)

**Comment by ShaiAvr** [comment]
@mastercoms Indeed I had community opt-out selected for some reason. Disabling this allowed me to access the channels again. Thank you.
