### ISSUE TITLE
Crashing while server changing map. On linux

### ISSUE THREAD

**Issue by vdualb** [mastercoms/tf2cfg#725]
**Describe the bug**
game crashes during `retrieving information from server` while server changing map.

**How you encountered the issue**
Play casual until server changes map.

**Desktop (please complete the following information):**
* mastercomfig version: 9.10.2
* Preset and addon(s): Medium Low preset, OpenGL addon, No Soundscapes addon.
* Custom values (if any): idk what's it, probably no
* DX level: not applicable since on linux?
* Launch options: `-novid -nojoy -nosteamcontroller -nohltv -particles 1 -precachefontchars -noquicktime`
* Operating system (OS): Fedora 38. im running Steam from flathub
* Graphics card (GPU): Intel® UHD Graphics (TGL GT2)
* Graphics driver version: Mesa (org.freedesktop.Platform.GL.default) 23.1.4
* Processor (CPU): 11th Gen Intel® Core™ i3-1115G4 × 4
* TF2 on HDD or SSD: SSD
* Memory (RAM) size in MB or GB: 16GB

**Comment by vdualb** [comment]
i tried to avoid this bug by leaving server before map change and queuing another march but game crashes during `retrieving information from server` step too. so it looks like crash happens when you connect to server second time.

**Comment by RocketRide9** [comment]
connecting to server, leaving it right after, connecting to another doesn't result in crash

**Comment by vdualb** [comment]
starting soldier training, playing it a bit, leaving and starting again results in crash

**Comment by qkall** [comment]
I can confirm... when ever I switch maps, the game crashes.

**Comment by ZapExp** [comment]
This also happens to me, on Linux Mint

**Comment by ghost** [comment]
can't replicate, the game works well for me on linux

**Comment by vdualb** [comment]
still crashes. tho it can take two map switches to crash, previously it crashed _every_ map change

**Comment by qkall** [comment]
I'm fairly certain this is related to this bug - unrelated to mastercomfig! 

https://github.com/ValveSoftware/Source-1-Games/issues/5043

**Comment by vdualb** [comment]
I can’t reproduce this issue anymore. Game still crashes randomly but I’m not sure if it’s a mastercomfig fault.

**Comment by Tiagoquix** [comment]
This was probably a game issue rather than a mastercomfig issue, and probably fixed with recent updates.

**Comment by vdualb** [comment]
Game is working way better now. I can't remember last time when it crashed
