### ISSUE TITLE
bind "MOUSE2" "+attack2" ****STILL**** not working.

### ISSUE THREAD

**Issue by Samg381** [mastercoms/tf2cfg#732]
Even after placing `bind "MOUSE2" "+attack2"` in every override, config file and VPK, selecting `spy` and attempting to cloak/uncloak has no effect. Please see my other bug report for my config files.

**Comment by mastercoms** [comment]
Have your config files not changed?

**Comment by Samg381** [comment]
They haven't changed except for the `spy.cfg` override which is currently the following:

```
// Commands here will be run when you select Spy

bind "MOUSE2" "+attack2"
```

When I select spy, my mouse2 is unbound. If I run `exec overrides/spy.cfg` in console, it starts working properly.

**Comment by mastercoms** [comment]
Alright, sorry for the inconvenience but could you share the app folder one more time and also what browser are you using to install mastercomfig?

**Comment by Samg381** [comment]
[cfg-custom.zip](https://github.com/mastercomfig/mastercomfig/files/12889592/cfg-custom.zip)

Firefox 114.0.1 (64-bit)

At this rate I think I should be eligible for contributor status 🤔

**Comment by mastercoms** [comment]
Could you visit the mastercomfig app, press F12 > Storage tab > Indexed DB > keyval and upload a screenshot similar to this one?

![image](https://github.com/mastercomfig/mastercomfig/assets/2672245/478b99be-b9ba-47ab-a925-df9345339be5)

**Comment by Samg381** [comment]
![Screenshot_3](https://github.com/mastercomfig/mastercomfig/assets/3127698/e8794df9-37ff-4293-bed4-b1f06c73f302)

Wrote the CachedData off to a text file in case you need it:

[CachedData.txt](https://github.com/mastercomfig/mastercomfig/files/12923145/CachedData.txt)

**Comment by Samg381** [comment]
Also, I'm not sure if mastercomfig stores the matchmaking ping limit setting, but it doesn't seem to be persisting between game sessions. I can open a new issue if need be.

**Comment by mastercoms** [comment]
It says here that you have Special attack bound to MOUSE2 for Spy. That would be +attack3, and it overrides your +attack2  bind. Would this be correct or is there no bind listed for that in the app?

**Comment by mastercoms** [comment]
mastercomfig removed the option related to matchmaking ping limit in 9.9.0. It should be customizable in-game in the matchmaking settings menu. If it is not saving, make sure your config.cfg is not read-only and that you are exiting the game using the in-game menus.

**Comment by Samg381** [comment]
I have MOUSE2 bound to +attack2 per the following official TF2 Wiki table:

![Screenshot_3](https://github.com/mastercomfig/mastercomfig/assets/3127698/b8abfbee-9ef6-475c-8d72-93706dd5ec65)

**Comment by mastercoms** [comment]
Yes, but in the binds menu, could you screenshot your binds menu? Because in the data, it says +attack3. So maybe it is not being displayed in the binds menu and it is a lingering value.

**Comment by mastercoms** [comment]
So I checked an earlier screenshot you have of your binds menu, and indeed, you do have Special attack bound to mouse2 for Spy. (3rd from the bottom)

![](https://user-images.githubusercontent.com/3127698/253786649-d88591d4-3b5c-490d-b482-581fe3e9968c.png)

**Comment by Samg381** [comment]
> So I checked an earlier screenshot you have of your binds menu, and indeed, you do have Special attack bound to mouse2 for Spy. (3rd from the bottom)

This is the _**correct**_ binding for spy. Per the table above, `SPY: Cloak / Uncloak` is controlled by `+attack2`, which I have bound to `mouse2`. I am unsure how this is an issue, as [this is the default binding for TF2](https://wiki.teamfortress.com/wiki/Spy).
