### ISSUE TITLE
Crash on opening disguise kit. On Linux

### ISSUE THREAD

**Issue by vdualb** [mastercoms/tf2cfg#733]
Describe the bug
game crashes after opening disguise kit while playing as a sniper.

How you encountered the issue
Open disguise kit.

Desktop (please complete the following information):

    mastercomfig version: 9.10.2
    Preset and addon(s): Medium Low preset, OpenGL addon, No Soundscapes addon.
    Custom values (if any): idk what's it, probably no
    DX level: not applicable since on linux?
    Launch options: -novid -nojoy -nosteamcontroller -nohltv -particles 1 -precachefontchars -noquicktime
    Operating system (OS): Fedora 38. im running Steam from flathub
    Graphics card (GPU): Intel® UHD Graphics (TGL GT2)
    Graphics driver version: Mesa (org.freedesktop.Platform.GL.default) 23.1.4
    Processor (CPU): 11th Gen Intel® Core™ i3-1115G4 × 4
    TF2 on HDD or SSD: SSD
    Memory (RAM) size in MB or GB: 16GB

**Comment by Tiagoquix** [comment]
This was probably a game issue rather than a mastercomfig issue, and probably fixed with recent updates.

**Comment by vdualb** [comment]
i probably didn't reset engineer binding properly. my skill issue, def not mastercoms 

EDIT: naming alias an "exit" was a bad idea
