### ISSUE TITLE
Re-add replacing libtcmalloc_minimal.so.4 in the linux OS Optimizations guide

### ISSUE THREAD

**Issue by FizzBuzz3000** [mastercoms/tf2cfg#738]
**Is your feature request related to a problem? Please describe.**
A while back, in commit 6502f38, steps to replace `libtcmalloc_minimal.so.4` were removed, and it should be added back since TF2 will not start if you use an updated SDL library without using the updated tcmalloc library. Do note that the package that the `libtcmalloc_minimal.so.4` library is in are not consistently named across distros due to google-perftools being renamed to gperftools. Fedora calls it `gperftools-libs` while ubuntu I think still has it as `libgoogle-perftools`.

**Describe the solution you'd like**
Add back the steps to install the system libraries of `libtcmalloc_minimal.so.4` and like libSDL2 symlink it in the steam runtime pinned libraries folder.

**Comment by Tiagoquix** [comment]
Not needed anymore, tf2 updated to 64 bits 🎉
