### ISSUE TITLE
incorrect docs ui

### ISSUE THREAD

**Issue by h9lk** [mastercoms/tf2cfg#739]
**Describe the bug**
After the merge pr most of the files remained as is, a version was created for them and they are spelled out everywhere in the files, but they are not accounted for

**How you encountered the issue**
- change lang on ru

**Screenshots**
![image](https://github.com/mastercomfig/mastercomfig/assets/32390006/0c6a5ba3-be39-4ae6-8313-d8d852f89e62)

**Example**
[Contributing](https://docs.comfig.app/latest/ru/contributing/)
[translation](https://github.com/mastercomfig/mastercomfig/blob/develop/docs/contributing.ru.md)
[mkdocs.base.ym](https://github.com/mastercomfig/mastercomfig/blob/42ffafba3b05bc12856192b24a380dcad6651222/mkdocs.base.yml#L175)
[mkdocs.yml](https://github.com/mastercomfig/mastercomfig/blob/42ffafba3b05bc12856192b24a380dcad6651222/mkdocs.yml#L36)

**Comment by mastercoms** [comment]
Docs aren't immediately posted until the dev branch gets promoted to a release.
