### ISSUE TITLE
Rename/remove presets

### ISSUE THREAD

**Issue by Tiagoquix** [mastercoms/tf2cfg#740]
Since the new update dropped, I'm thinking about renaming/removing some of the presets and leave only a few ones.

Such as:

Maximum Quality (High/Ultra)
Balanced (Medium High/High)
Competitive (Medium)
Performance (Low)
Destitute (Very Low)

**Comment by mastercoms** [comment]
This is already being done

**Comment by Tiagoquix** [comment]
Thanks! If there's anything I can help with, please let me know.
