### ISSUE TITLE
Retest lighting_ex=low on GNU/Linux

### ISSUE THREAD

**Issue by Tiagoquix** [mastercoms/tf2cfg#741]
> lighting_ex=low: Better hints to use the lighting fast path (disables bumpmaps, specular and phong). May reduce performance on modern PCs, due to rendering reloads. **Also can cause black rendering artifacts on Linux Mesa graphics drivers.**

The bug probably has been fixed due to the game switching from ToGL to DXVK. Needs retesting.

**Comment by mastercoms** [comment]
You can retest it?

**Comment by Tiagoquix** [comment]
I cannot, because I use the proprietary NVIDIA drivers, and it seems like they don't use Mesa at all:

> Proprietary graphics drivers (e.g., Nvidia GeForce driver and Catalyst) replace all of Mesa, providing their own implementation of a graphics API.

Without them, performance is very poor on my PC. I can technically use Nouveau (the open-source Mesa for NVIDIA), but I don't think it's worth it. I think people that reported this were on AMD or Intel when the graphical glitches were happening.

Considering that several things were fixed with the transition to Vulkan (such as, for example, the transparency of sprays with DXT5 on Linux), I believe that this warning can be safely removed.

It would be interesting to check if there are still people reporting this after the 64-bit + Vulkan update.

**Comment by Tiagoquix** [comment]
I looked for the relevant information and found the following:

https://gitlab.freedesktop.org/mesa/mesa/-/issues/3514 - this is the issue on Mesa's GitLab about the problem. The user who reported uses an AMD graphics card.

https://github.com/ValveSoftware/Source-1-Games/issues/3443 - this appears to be the original issue on Valve's GitHub. It is not possible to access the original reporter's information Gist.

In the same issue above, there is a user who claims that the issue has been fixed - https://github.com/ValveSoftware/Source-1-Games/issues/3443#issuecomment-2067539549 (but without any evidence), while another also suspects, just like me, the problem was fixed because of the ToGL->DXVK transition.

There is also this issue - https://github.com/ValveSoftware/Source-1-Games/issues/5842 - but here the user uses NVIDIA with the proprietary driver, and it seems to be just an NVIDIA driver issue with the XWayland protocol, something NVIDIA said they will correct at the end of May.

--------------

Reconsidering further, *apparently* the problem only occurs in the OpenGL version. As we have neither confirmation nor denial that this occurs in the DXVK version, I believe we can leave the warning there in the docs without any problem, but perhaps clarify that this seems to be only pertinent to OpenGL.

**Comment by delet-this** [comment]
I can't reproduce the issue anymore on 64 bit ToGL or DXVK. RX 590, Mesa 23.1.9, kernel 6.1.90. I used to get the issue on 32 bit ToGL.

e: After more testing I was able to still get the issue on 64 bit ToGL. Having mat_bumpmap 1; mat_specular 1 in autoexec and then disabling them in console didn't result in artifacts, I had to remove the cvars from autoexec to reproduce the issue. I still didn't get the issue on DXVK.

**Comment by Tiagoquix** [comment]
Note that ToGL only exists for 32-bit. The 64-bit version does not have OpenGL, and only has Vulkan.

Closing the issue as deprecated because the 32-bit version (and, therefore, OpenGL) is going to be removed from the game at some point. My suggestion is to remove that text since the default experience for Linux users is Vulkan now, which doesn't suffer from the same problem. Maybe move it to the troubleshooting section if needed.
