### ISSUE TITLE
64Bit update support

### ISSUE THREAD

**Issue by presario42** [mastercoms/tf2cfg#742]
**Is your feature request related to a problem? Please describe.**
TF2 has been recently updated to 64 bits and i wonder if mastercomfig will have support for this new update soon

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by treacherousfiend** [comment]
mastercomfig does not need to be updated to function on the 64 bit update, it works just fine with the current version.
That being said, there are some changes in the works to account for some of the changes made.
here's a few off the top of my head:
- you can remove `-noquicktime` from your launch options, as support for quicktime has been removed
- The player model on the hud has been greatly optimized, so there is now 0 reason to disable it for performance, only if you prefer the 2d images.

There are also some plans to consolidate the presets a bit.

**Comment by Katzenwerfer** [comment]
I do wonder if heapsize values in https://github.com/mastercomfig/mastercomfig/blob/develop/config/mastercomfig/dxsupport_override.cfg need to be adjusted since the game shouldn't be limited to 2 GB of RAM anymore.

**Comment by mastercoms** [comment]
They are indeed a bit smaller than the default, but that's not such a big deal. The upcoming update will fix that too

**Comment by mastercoms** [comment]
I'll be closing this since this doesn't need to be specifically addressed, though a new update is coming.
