### ISSUE TITLE
Comfig Docs says we're on version 9.10.2 and not 9.10.3

### ISSUE THREAD

**Issue by Tiagoquix** [mastercoms/tf2cfg#744]
![image](https://github.com/mastercomfig/mastercomfig/assets/30274161/2660c891-55ef-42e0-be34-c327dec12887)

https://docs.comfig.app/latest/tf2/

**Comment by mastercoms** [comment]
Fixed in f8daf1b47f47db2669e3383bdee8d105e425e78b
