### ISSUE TITLE
Little issue with the preset selection

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [mastercoms/tf2cfg#75]
Well, no real other details to share here. Downloaded the latest package, running it on Elementary OS (Debian based)
![Capture d'écran du 2019-04-22 12 12 18](https://user-images.githubusercontent.com/13170204/56496025-5e126e80-64e7-11e9-9f32-b2eb2d1de8ff.png)

**Comment by mastercoms** [comment]
This is an issue with it fetching available presets more than once sometimes, so it repeats entries.

**Comment by mastercoms** [comment]
Closing because the mastercomfig 7 app is discontinued.
