### ISSUE TITLE
Recommendation for OpenGL users?

### ISSUE THREAD

**Issue by 0CCULTIST** [mastercoms/tf2cfg#752]
Currently there's a critical bug on the Vulkan version of Tf2 for Linux users where the game starts stuttering massively after ~15-30 minutes of gameplay, thus making OpenGL the only, hopefully temporary, solution for the problem. In the mean time, and especially if the fix isn't released soon, should OpenGL 64bit users continue to use modern mastercomfig releases without the OpenGL optimizations, use the OpenGL optimizations along with modern mastercomfig versions, or simply use the last 32 bit release? 

Update: forgot about this issue. The issue resolves itself if you _enable_ the steam overlay. Don't ask me why or how. Either way the performance gain you get from using Vulkan is much more significant than the performance decrease (if it's even measurable) of enabling the steam overlay.

**Comment by Tiagoquix** [comment]
OpenGL is going to be deprecated and removed at some point, so I don't think mastercomfig should focus on OpenGL-related optimizations.

For now, I think mastercomfig can adopt the previous GL optimizations in the comfig.cfg file, then re-add the glbaseshaders files and call it a day. You can also search for issues and answers in the Valve's issue tracker regarding OpenGL performance and problems. Here's two that may help:

https://github.com/ValveSoftware/Source-1-Games/issues/5842#issuecomment-2071379367
https://github.com/ValveSoftware/Source-1-Games/issues/5186#issuecomment-1720390073 (not sure if this exists/works, but you can try)

**Comment by presario42** [comment]
personally i had luck leaving the old OpenGL optimization vpks on the custom folder

**Comment by 0CCULTIST** [comment]
Closing this as there is a fix for the Vulkan version; enabling the steam overlay. Yes, really, and it really does work. Perhaps @mastercoms should suggest enabling the steam overlay for Linux users having stuttering issues in the docs.
