### ISSUE TITLE
Restore default values for some HUD-related ConVars

### ISSUE THREAD

**Issue by Tiagoquix** [mastercoms/tf2cfg#755]
Hi there.

There are some ConVars that have different values compared to TF2 default in mastercomfig, most of them being related to the heads-up display - such as:

- hud_saytext_time
- cl_notifications_move_time
- hud_deathnotice_time

etc.

In the past, I saw then as somewhat interesting to reduce HUD elements and therefore improve FPS somewhat and make the screen cleaner with less elements taking space for too much time. However, now, some years leater, I don't see a reason for us to set different values. I think we should use the default values whenever possible if it doesn't hurt user experience (for example, tf_dashboard_slide_time makes sense to be a lower value due to it improving user experience with fast transitions).

Please let me know what you think. If the suggestion is approved, I'll do a PR myself to change the ConVars' values.

Thanks in advance for your attention.

**Comment by mastercoms** [comment]
I think they're nice adjustments though it's very subjective

**Comment by Tiagoquix** [comment]
I think they're not as useful in present days due to the 64-bit update which massively improved loading times and performance. From my POV, I would prefer to change them back to their default values.

**Comment by mastercoms** [comment]
How is this related?

**Comment by Tiagoquix** [comment]
If by "this" you mean the 64-bit update, then I judge it is related because, as I said in my original comment, "I saw then [the HUD ConVars] as somewhat interesting to reduce HUD elements and therefore improve FPS somewhat and make the screen cleaner with less elements taking space for too much time".

Since we now have more FPS, making HUD elements take less time on the screen would not be much of a help.

However, I now understand that the adjustments are just nice adjustments, and not really FPS-related adjustments.
