### ISSUE TITLE
Question about network ConVars

### ISSUE THREAD

**Issue by Tiagoquix** [mastercoms/tf2cfg#756]
`rate`: considering TF2 updates, can we increase the default `bandwidth` module level to `1.5Mbps`?

`cl_pred_optimize`: should we use `setinfo` for it like we use for `cl_interp` and `cl_interp_ratio`?

**Comment by mastercoms** [comment]
rate is fine where it is. there have been no adjustments to make me feel comfortable with the stability of setting it higher.

cl_pred_optimize isn't a user info cvar. there's no reason to use setinfo for it.
