### ISSUE TITLE
'app/[class].cfg' not present; not executing

### ISSUE THREAD

**Issue by ghzeni** [mastercoms/tf2cfg#758]
**Describe the bug**
class-specific configs do not work unless placed under `tf/cfg/app/` or `tf/cfg/app/overrides`. Other scripts placed in root `tf/cfg/` folder appear to run normally.

**How you encountered the issue**
Typing `exec engineer` into the console.

**Additional context**
I use github to keep track of my class-specific configs, etc. I have a shit-ton of configurations for each class.

I currently swap between two branches: `current` (my current config on my main desktop) and `potato` (my config on my laptop).

I do not want to create copies of my class configs just due to using mastercomfig. Apparently, mastercomfig redirects all `exec [class]` commands to `tf/cfg/app/`. I want to change this so I can use everything related to mastercomfig only on my `potato` branch and not affect anything already set-up on my `current` branch. 

How can I do this? Thanks.

**Console logs**

```
# when swapping to engi/trying to run 'exec engineer' manually

'overrides/engineer.cfg' not present; not executing.
'app/engineer.cfg' not present; not executing.
``` 

```
# when trying to manually navigate outside the app/ folder and back into my root cfg folder

] exec "../engineer.cfg"
exec //MOD/cfg/../engineer.cfg: invalid path.
] exec "../../engineer.cfg"
exec //MOD/cfg/../../engineer.cfg: invalid path.
```

**Desktop (please complete the following information):**
* mastercomfig version: 9.10.3 | May 6, 2024 
* Preset and addon(s): low + tweaks
* Custom values (if any): 
```
fpscap=75
textures=very_low
sheens_tint=low
props=low
decals_art=on
motion_blur=low
particles=very_low
water=very_low
``` 

* DX level: 81
* Launch options: `-dxlevel 81 -fullscreen -w 1600 -h 900 -console -novid -nojoy -nosteamcontroller -nohltv -particles 1 -precachefontchars`
* Operating system (OS): Win 10

**Comment by mastercoms** [comment]
it's tf/cfg/overrides or tf/cfg/app. mastercomfig has its own class configs at tf/cfg so you cant use those. what you can do instead is add a series of class configs just like mastercomfig, which exec overrides/classname.cfg, that way you can keep the actual configs in the same place

I'll close this since this seems more like a support request than a bug, since the actual core function is an intentional feature of the config. Feel free to ask any more questions about it though

**Comment by ghzeni** [comment]
@mastercoms 
> it's tf/cfg/overrides or tf/cfg/app. mastercomfig has its own class configs at tf/cfg so you cant use those. what you can do instead is add a series of class configs just like mastercomfig, which exec overrides/classname.cfg, that way you can keep the actual configs in the same place
> 
> I'll close this since this seems more like a support request than a bug, since the actual core function is an intentional feature of the config. Feel free to ask any more questions about it though

Right. Is there currently a way for me to simply reference my configs at `tf/cfg/` instead of having to maintain a copy? Or perhaps a custom value like "run_configs_in_root_folder" or something? Having duplicates is really impractical and for the current state of the application, I either have to create a copy for each class and manually copy those everytime I want to update my class configs across multiple branches, or I'm forced to use mastercomfig even in branches that I don't intend to.

If not, may I create an issue for this as a feature request? Thanks.

Additionally, why does running any other config files work? This diverging behavior really confused me at first (I have a mvm.cfg file specifically for mvm and running it with `exec` worked flawlessly. This seems restricted to class configs, which is not very intuitive or should be specified somewhere in the docs).

**Comment by mastercoms** [comment]
It is specified in the docs, both in the install guide and the documentation on custom configs. Is there somewhere else it should also be explained?

And the reason this happens is that mastercomfig has configs at that exact location. In Source, 2 files can't be at the same location, so mastercomfig has to execute an alternative location for custom user files.

I gave a workaround for your problem which should work without you needing to copy things around, let me explain it more in depth.

Have your actual class configs in both branches be at tf/cfg/overrides/engineer.cfg for example.

In the branch without mastercomfig, make a new file at tf/cfg/engineer.cfg that contains:

```
exec overrides/engineer.cfg
```
