### ISSUE TITLE
A few ideas for low end mods/additions

### ISSUE THREAD

**Issue by Spyindabox** [mastercoms/tf2cfg#76]
I managed to get nvidia inspector to renable the old lod bias setting by following a guide like this one here for lower end textures https://www.teamfortress.tv/35876/get-quake-like-textures-high-lod-bias-again, not sure how you would do this for invidia or intel though . I also managed to get the low end oldschoolpack lod models to load by preloading and removing the materials files, (it loads with custom materials if you preload but all characters are invisible), you might look into how yttriums view models manages to automate preloading. Also my testing with it has been hit or miss, but if you have a quad core or better priotizing core 0 might be worth it with something like process lazzo. I think that finding a way to automate the tweaks could push the low end config with mastercomfig even further. These are just a few tweaks I made to try to maximize my fps.

Edit: note on the oldschoolpack lod it gives purple textures, the models load correctly if you delete the materials folders then preload, however the materials don't since the oldschool pack used their own textures for their models the game doesn't know what to do with them and defaults to purple/black for their textures. This could be solved by rebaking the default textures onto the lower quality lods, in theory you could decompile and then change the materials to match the normal ones by baking the textures onto the low poly lods. It wouldn't be hard but it would take a while to do them all. You might considered seperating that into a new project if you try it, I might mess around with doing some of that myself but can't promise anything as I'm going to be quite busy this summer. 

Edit 2: to preload just start a training match with bots then quit it and start a normal valve server match for testing, thats what I did since I couldn't figure out how to automate it.

**Comment by mastercoms** [comment]
I don't think most of these suggestions clearly improve performance.
