### ISSUE TITLE
Remove aliases containing non-movement ConVars

### ISSUE THREAD

**Issue by slxdy** [mastercoms/tf2cfg#760]
Since the last summer update, aliases containing ConVars unrelated to movement get discarded.

**Comment by Niterux** [comment]
[they were already removed](https://github.com/mastercomfig/mastercomfig/commit/bc7a63af35b05744d0cc5771ba265d8656d7f089)

**Comment by slxdy** [comment]
Ah, mb. Should've checked commits.
Tho great job on the quick update
