### ISSUE TITLE
mastercomfig app "r_lod -1"

### ISSUE THREAD

**Issue by SupinePandora43** [mastercoms/tf2cfg#77]
how can i set "r_lod" in app to "-1" ?!

**Comment by mastercoms** [comment]
It is the model quality option in the app. You can also use custom.cfg.

**Comment by mastercoms** [comment]
r_lod -1 is the default. It should be affected by the model quality setting, and be set to 0 on ultra. You can use `tf/cfg/custom.cfg` to override values.
