### ISSUE TITLE
indirect module selector for user-injecting into it

### ISSUE THREAD

**Issue by kogirlvent** [mastercoms/tf2cfg#771]
since alias'ing cvars have been disallowed, trying to override a module's setting has been kinda really annoying

so the idea is that, instead of `alias particles=low "alias particles particles_low"` we
```
alias particles=low "alias particles particles_low_inject"
alias particles_low_inject "particles_low; particles_low_override"
```
whereas `particles_low_override` is exposed to customization

this would allow a still simple e.g.
`alias particles_low_override "tf_particles_disable_weather 0"`
replacing the now obsolete
`tf_particles_disable_weather 0; alias tf_particles_disable_weather`

**Comment by mastercoms** [comment]
I haven't heard of this use case before, it's certainly interesting! Though mainly I have expected most people to use autoexec.cfg and just override cvars that way without needing to inject into module levels.

It's also certainly easy enough to create your own module levels with the config hook files. So you could have particles_lowko or something like that and call particles_low then apply your own settings. 

Given these 2 much more robust alternatives that have been officially supported for a long time, I don't think I'll be looking to implement this unless further reasoning is given to explain benefits.
