### ISSUE TITLE
Can't disable motion blur

### ISSUE THREAD

**Issue by DecemAdUnum** [mastercoms/tf2cfg#79]
## Reporting an issue

1. Search [current issues](https://github.com/mastercoms/mastercomfig/issues) and
[troubleshooting](https://github.com/mastercoms/mastercomfig/wiki/Troubleshooting)
to see if your issue is already known.
2. Title your issue with something short but descriptive, like "Missing models
on load", not "i need help" or "hey problem found in your config please fix,
thanks!!"
3. Include the following information in your report:
    * How you encountered the issue
    * Config version (don't say latest, say the actual version, found in the
      startup console output)
    * Config preset and addon(s)
    * Custom values (if any)
    * DX level
    * Launch options
    * Operating system (OS)
    * Graphics card (GPU)
    * Processor (CPU)
    * HDD or SSD
    * RAM size in MB or GB

## Requesting new features

1. Search [current issues](https://github.com/mastercoms/mastercomfig/issues)
   to see if your feature has already been requested.
2. Title your feature request with something short but descriptive, like "Add
   better options for pyrovision", not "cool idea i had" or "please look at this
   one thanks very much".
3. Describe the feature you want as much detail as you can, and also explain why
   the feature should be included.

**Comment by mastercoms** [comment]
Please fill out the required information as part of the issue template.
