### ISSUE TITLE
Config visual rewrite

### ISSUE THREAD

**Issue by JackStanley** [mastercoms/tf2cfg#8]
Im gonna leave a link to pastebin when im done, i left some controversial things to discuss right after "!!!" just like comms.

**Comment by JackStanley** [comment]
Here we go! 
https://pastebin.com/bBRtkveg

**Comment by mastercoms** [comment]
Thank you for this work. However, the problem. I have with changing some of the default values is that it kind of makes the maxframes config useless, no?

**Comment by JackStanley** [comment]
Well, I suppose I just recommended updating some values to make the config more perfomance based,. Still, I haven't done anything to maxframes.cfg so the values may be the same in some parts. These two configs just need to be compared

**Comment by JackStanley** [comment]
Yes now I see some values are just the same except water and sound sections

**Comment by JackStanley** [comment]
Just let me know If you don't want these changes and I edit maxframes.cfg as I did with the main config. It will be just easier to add these options to the bottom and comment them, pretty much just like Comanglia has their config with Disabled shadows and option to enable them just by uncommenting the same cvars with different values for eg

**Comment by mastercoms** [comment]
```
// Add new renderables and compute blends for added renderables asynchronously
cl_threaded_client_leaf_system 1 // optimization for 4 core+ CPUs
//cl_threaded_client_leaf_system 0 // use traditional behavior for CPUs with less cores

// Force multithreaded mode for the material system queue
mat_queue_mode 2 // optimization for 4 core+ CPUs
//mat_queue_mode -1 // let the engine determine the optimal mode otherwise

// Set up bones on animated entities asynchronously
r_threaded_renderables 1 // optimization for 4 core+ CPUs
//r_threaded_renderables 0 // use traditional behavior for CPUs with less cores

// Queue decals to material system
r_queued_decals 0 // Possible crashes and little benefit when decal limit is low
//r_queued_decals 1 // Possible performance improvement if you don't crash
```

Here's how I'm rewriting my config. Any suggestions? I feel like moving all of the comments to the side gives me less room to explain things and won't let me add customization options.

**Comment by JackStanley** [comment]
```
//These settings for quard-core CPUs only, settings for <4-core CPUs are listed below

cl_threaded_client_leaf_system 1 // Add new renderables and compute blends for added renderables asynchronously
mat_queue_mode 2  // Force multithreaded mode for the material system queue
r_threaded_renderables 1 // Set up bones on animated entities asynchronously
r_queued_decals 0 // Queue decals to material system


//cl_threaded_client_leaf_system 0 // use traditional behavior for CPUs with less cores
//mat_queue_mode -1 // let the engine determine the optimal mode otherwise
//r_threaded_renderables 0 // use traditional behavior for CPUs with less cores
//r_queued_decals 1 // Possible performance improvement if you don't crash
```

This is just my vision of the situation

**Comment by JackStanley** [comment]
Hre's the solution if you experiencing room problems:

```
command  x  //blabla
                    //blabla
                    //bla

```

**Comment by mastercoms** [comment]
Why shouldn't the same CVars be together? How did you choose to group them like that?

**Comment by JackStanley** [comment]
Im sorry if this confusing you. Grouping up things like this just gives a cleaner look. Every commented command in the section clearly visible and can be easily fund and uncommented. 

```
// --- Specific section here ---
Here at the top we've got the most compatible values

//Here at the bottom we've got more personalized commands, commented.

```
This is just makes the config user friendly, and if you run it w/o editing, it would be okay to use.
Like I have to change some cvars every time the config being updated because some cvars "are not for every user" (im talking about threading as a 2 core CPU user)

Actually If you you want the config to be more compatible, use threading cvars for 2 core CPUs.

For example Shadows section may look like this:
```

// --- Shadows ---

r_shadows 0					// disable shadows, big performance hit if you enable
r_shadowrendertotexture 0	// render shadows using two materials for each texture, makes shadows look better but uses a lot of RAM
cl_blobbyshadows 1			// don't do a second shadow render pass for sharper shadows
r_threaded_client_shadow_manager 1	// threaded shadow manager
r_flashlightdepthres 32		// the resolution of the shadow depth texture, this only works if depth texturing is enabled
							// this makes shadows more sharp and detailed the higher it is, shadows are fine at 32 or 64 though
r_flashlightdepthtexture 0	// depth texturing for shadows: these shadow calcuations are done mostly. It has a big performance hit on CPU
r_flashlightmodels 0		// disable shading/lighting useless performance hit
r_flashlightrender 0
r_flashlightdrawfrustum 0
nb_shadow_dist 300			// don't render shadows far away (nextbot system)
r_shadowmaxrendered 17		// don't render more shadows than needed


//The same commands to turn on shadows here
```

It's easy to uncomment things rather than edit values and remember the previous ones

Customization only for gibs, shadows, sprays (turn on and off by uncommenting) and threading would be enough for now

Again, im really sorry for wasting your time with these lil things

**Comment by fagoatse** [comment]
Oh, I just replied to the other issues which is about the same topic but yeah I agree with @JackStanley

**Comment by mastercoms** [comment]
I wasn't asking about grouping according to type, but why not have different options for the CVars grouped by CVar?

For example:

```
cl_threaded_client_leaf_system 1 // Asynchronously add new renderables and compute blends for added
                                 // renderables
//cl_threaded_client_leaf_system 0 // Use traditional behavior for CPUs with less than 4 cores

r_threaded_renderables 1 // Asynchronously set up bones on animated entities
//r_threaded_renderables 0 // Use traditional behavior for CPUs with less than 4 cores
```

As opposed to:
```
cl_threaded_client_leaf_system 1 // Asynchronously add new renderables and compute blends for added
                                 // renderables
r_threaded_renderables 1 // Asynchronously set up bones on animated entities

//cl_threaded_client_leaf_system 0 // Use traditional behavior for CPUs with less than 4 cores
//r_threaded_renderables 0 // Use traditional behavior for CPUs with less than 4 cores
```

If you want an easier time setting up the config, I think the better solution is presets (fewcores.cfg, maxframes.cfg, slowcpu.cfg, etc). That way you don't have to uncomment settings you would uncomment anyway.

**Comment by JackStanley** [comment]
Oh wait I remember your config had ~20 .cfg files, it's no way D: Just do as you like, or start staw poll in tf.tv thread :)

**Comment by mastercoms** [comment]
Well, this approach would be different to that. It would basically be a few overrides for a certain user.

In the old system, it was just every category had its own cfg, but in this new system, it will just be for quickly switching settings that you would change anyway if you needed it.

**Comment by JackStanley** [comment]
So are the comments right after cvars will be implemented? W/o any categorizing

**Comment by mastercoms** [comment]
Working on it: https://gist.github.com/mastercoms/44be52f6c070de1a7c2e8a0430e0b257

**Comment by mastercoms** [comment]
See https://github.com/mastercoms/tf2cfg/tree/4.0.0

**Comment by JackStanley** [comment]
Well a lot of work nicely done here!
