### ISSUE TITLE
Very small question about crosshair settings in comfig.cfg

### ISSUE THREAD

**Issue by NekoAlosama** [mastercoms/tf2cfg#80]
Why are the crosshair color settings set to these seemingly random values?

`//cl_crosshair_red 156 // Crosshair red (0 to 255)`
`//cl_crosshair_green 39 // Crosshair green (0 to 255)`
`//cl_crosshair_blue 176 // Crosshair blue (0 to 255)`

**Comment by mastercoms** [comment]
It's not set to that, just a commented example which makes the crosshair purple. If you're curious about those specific values, they are the ones I use.

**Comment by NekoAlosama** [comment]
Ahh, understandable.
Just never saw an explanation for this anywhere, so I had to ask.
