### ISSUE TITLE
I Need The Killfeed Command For Very Low Preset

### ISSUE THREAD

**Issue by HiNxG** [mastercoms/tf2cfg#82]
I dont like my kill feed disappearing so I want it to be shown

**Comment by mastercoms** [comment]
Look at the killfeed [module](https://github.com/mastercoms/mastercomfig/wiki/Modules)

**Comment by HiNxG** [comment]
> Look at the killfeed [module](https://github.com/mastercoms/mastercomfig/wiki/Modules)

Its ok, I found it
