### ISSUE TITLE
Lag on demo recording, class change due to hud_reloadscheme

### ISSUE THREAD

**Issue by Rattlewrench** [mastercoms/tf2cfg#83]
**Every** time I spawn as a new class or starting a demo, distinctive `hud_reloadscheme` lag happens: game freezes for about a second and all hud elements flashing at once for a few frames.

Problem appears with both v6.11.5 and 6.11.6. As far as I can tell the problem is caused by `running hud_reloadscheme on only your first spawn in game` added in v6.11.5.

v6.11.4 doesn't have this problem so I'm sticking with it for a while.

I understand how useful `hud_reloadscheme` may be, but running it so often is overkill. Personally, I prefer to have a bind to call it when needed.

**Comment by mastercoms** [comment]
hud_reloadscheme should only be ran automatically **once** while the game executable is open. It should be running every time you spawn as a new class, or every time you start a demo. You might have exec autoexec or exec finalize somewhere in your configs?

**Comment by Rattlewrench** [comment]
Yep, my bad. Had an `exec autoexec.cfg` in each of the class configs. Took quite a bit of thinking on how exactly I should fix that.

Ended up with moving everything from the `autoexec.cfg` to the `game_overrides.cfg` and leaving `autoexec.cfg` with a single string `game_overrides_c` (???).

**Comment by mastercoms** [comment]
You shouldn't do that. Just move the things you want to run when you spawn as a new class to `game_overrides.cfg`, and put everything else in `autoexec.cfg`. Don't add `game_overrides_c` to your own configs, it's run automatically by mastercomfig.

**Comment by Rattlewrench** [comment]
Okay, got it. Most part of what I was running for all classes were key bindings. So I left them in the `game_overrides.cfg` and moved the rest of commands I had to the `autoexec.cfg`; and also removed all calls to other files from the class configs.
Thanks for the help with fixing my mess!
