### ISSUE TITLE
Unable to join servers on MacOS

### ISSUE THREAD

**Issue by irefl** [mastercoms/tf2cfg#84]
## Reporting an issue

1. Search [current issues](https://github.com/mastercoms/mastercomfig/issues) and
[troubleshooting](https://github.com/mastercoms/mastercomfig/wiki/Troubleshooting)
to see if your issue is already known.
2. Title your issue with something short but descriptive, like "Missing models
on load", not "i need help" or "hey problem found in your config please fix,
thanks!!"
3. Include the following information in your report:
    * How you encountered the issue
Initially after installing the config I tried to join a casual game and initially had some crashing on the loading screen, but after removing other stuff I managed to get past that, yet I would have massive frame drops and then crash very closely to the time i would load in ([video](https://youtu.be/KtWGnqNA578)). I tried this again without any other addons and the result was the same. Thanks for any help!
    * Config version (don't say latest, say the actual version, found in the
      startup console output)
6.12.0
    * Config preset and addon(s)
Medium preset. No Extra Models, No Tutorial, Mouse Tweaks, Bad GPU, Slow I/O addons.
    * Custom values (if any)
    * DX level
92
    * Launch options
`-novid -nojoy -nosteamcontroller -softparticlesdefaultoff -reuse -w 1920 h-1080 -nohltv -dxlevel 92 -nostartupsound -nostartupsound -limitvsconst-novid -nojoy -nosteamcontroller -softparticlesdefaultoff -reuse -w 1920 h-1080 -nohltv -dxlevel 92 -nostartupsound -nostartupsound -limitvsconst`
    * Operating system (OS)
MacOS 10.13.6 (High Sierra)
    * Graphics card (GPU)
Intel HD 5000
    * Processor (CPU)
Intel Core i5 4260u
    * HDD or SSD
HDD
    * RAM size in MB or GB
8gb DDR3 @ 1.6ghz

**Comment by rjaxa301** [comment]
try without the -limitvsconst launch option.
do you have your launch options pasted twice?

**Comment by irefl** [comment]
Double checked the launch options, and tried without limitvsconst, still same behaviour.

**Comment by mastercoms** [comment]
Remove `-w 1920 h-1080` and `-dxlevel 92`.

**Comment by irefl** [comment]
Removed both, still crashing, managed to get a bit further when i tried -dxlevel 90 but then crashed on with an OS out of memory error

**Comment by mastercoms** [comment]
Could you try the low mem addon? And remove the slow IO addon? Just for testing

**Comment by irefl** [comment]
Don't have any other addons in rn, will try with low mem

**Comment by irefl** [comment]
crashed on class select

**Comment by irefl** [comment]
same result with the other addons back (-slowio)

**Comment by irefl** [comment]
Try 6.12.1?

**Comment by mastercoms** [comment]
I don't suspect it'll change much but sure!

**Comment by irefl** [comment]
Got past class select and was able to play some (although it stuttered a ton) before crashing on memory address again

**Comment by mastercoms** [comment]
Can you try with the low preset? And try `-dxlevel 90`, but remove it after launching one and then test it on the second launch.

**Comment by irefl** [comment]
Crashing/stuttering seems to be resolved with that, thanks for all your work!
