### ISSUE TITLE
Put 'm_customaccel 0' on Mouse Tweak Addons

### ISSUE THREAD

**Issue by Tiagoquix** [mastercoms/tf2cfg#85]
Just add the command **m_customaccel 0** to disable custom mouse acceleration on Mouse Tweaks addon. That's it.

**Comment by mastercoms** [comment]
Would you like to submit a pull request for this edit?

**Comment by Tiagoquix** [comment]
> Would you like to submit a pull request for this edit?

Yes. How to proceed?

**Comment by mastercoms** [comment]
Go here to the mouse tweaks file: https://github.com/mastercoms/mastercomfig/blob/release/config/cfg/addons/mouse-tweaks.cfg

Click the pencil icon to edit, and make your change. Type a commit description, like "disabled custom acceleration on mouse tweaks", and then click the green button to commit. It will automatically create a fork for you. After that, it should prompt you to create a pull request on your recently pushed branch.
